# Generated by Django 5.2.17 on 2026-09-23 21:07

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import (
    migrate_credentials,
    restore_credentials,
)
from authentik.crypto.secrets.migrations._permissions import preserve_role_permissions

FIELDS = [("_password", "password_ref", None, "SMTP password")]


def forwards(apps, schema_editor):
    migrate_credentials(apps, schema_editor, "authentik_stages_email", "EmailStage", FIELDS)
    preserve_role_permissions(apps, schema_editor, [("authentik_stages_email", "emailstage")])


def backwards(apps, schema_editor):
    restore_credentials(apps, schema_editor, "authentik_stages_email", "EmailStage", FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0005_delete_userobjectpermission_and_groupobjectpermission"),
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_stages_email", "0006_emailstage_recovery_cache_timeout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailstage",
            name="password",
            field=models.TextField(blank=True, db_column="password", default=""),
        ),
        migrations.RenameField(
            model_name="emailstage",
            old_name="password",
            new_name="_password",
        ),
        migrations.AddField(
            model_name="emailstage",
            name="password_ref",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_stages",
                to="authentik_crypto_secrets.secret",
                verbose_name="SMTP password",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", "SET CONSTRAINTS ALL IMMEDIATE"),
    ]
