/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartialUser } from './PartialUser';
import {
    PartialUserFromJSON,
    PartialUserFromJSONTyped,
    PartialUserToJSON,
    PartialUserToJSONTyped,
} from './PartialUser';

/**
 * Serializer for email authenticator devices
 * @export
 * @interface EmailDevice
 */
export interface EmailDevice {
    /**
     * The human-readable name of this device.
     * @type {string}
     * @memberof EmailDevice
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof EmailDevice
     */
    readonly pk: number;
    /**
     * 
     * @type {string}
     * @memberof EmailDevice
     */
    readonly email: string;
    /**
     * 
     * @type {PartialUser}
     * @memberof EmailDevice
     */
    readonly user: PartialUser;
}

/**
 * Check if a given object implements the EmailDevice interface.
 */
export function instanceOfEmailDevice(value: object): value is EmailDevice {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('pk' in value) || value['pk'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function EmailDeviceFromJSON(json: any): EmailDevice {
    return EmailDeviceFromJSONTyped(json, false);
}

export function EmailDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'pk': json['pk'],
        'email': json['email'],
        'user': PartialUserFromJSON(json['user']),
    };
}

export function EmailDeviceToJSON(json: any): EmailDevice {
    return EmailDeviceToJSONTyped(json, false);
}

export function EmailDeviceToJSONTyped(value?: Omit<EmailDevice, 'pk'|'email'|'user'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

