/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pseudo class for plex response
 * @export
 * @interface PlexAuthenticationChallengeResponseRequest
 */
export interface PlexAuthenticationChallengeResponseRequest {
    /**
     * 
     * @type {string}
     * @memberof PlexAuthenticationChallengeResponseRequest
     */
    component?: string;
}

/**
 * Check if a given object implements the PlexAuthenticationChallengeResponseRequest interface.
 */
export function instanceOfPlexAuthenticationChallengeResponseRequest(value: object): value is PlexAuthenticationChallengeResponseRequest {
    return true;
}

export function PlexAuthenticationChallengeResponseRequestFromJSON(json: any): PlexAuthenticationChallengeResponseRequest {
    return PlexAuthenticationChallengeResponseRequestFromJSONTyped(json, false);
}

export function PlexAuthenticationChallengeResponseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlexAuthenticationChallengeResponseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'component': json['component'] == null ? undefined : json['component'],
    };
}

export function PlexAuthenticationChallengeResponseRequestToJSON(json: any): PlexAuthenticationChallengeResponseRequest {
    return PlexAuthenticationChallengeResponseRequestToJSONTyped(json, false);
}

export function PlexAuthenticationChallengeResponseRequestToJSONTyped(value?: PlexAuthenticationChallengeResponseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'component': value['component'],
    };
}

