// Code generated by go-swagger; DO NOT EDIT.

package stages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/BeryJu/passbook/proxy/pkg/models"
)

// StagesPasswordPartialUpdateReader is a Reader for the StagesPasswordPartialUpdate structure.
type StagesPasswordPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StagesPasswordPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStagesPasswordPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStagesPasswordPartialUpdateOK creates a StagesPasswordPartialUpdateOK with default headers values
func NewStagesPasswordPartialUpdateOK() *StagesPasswordPartialUpdateOK {
	return &StagesPasswordPartialUpdateOK{}
}

/*StagesPasswordPartialUpdateOK handles this case with default header values.

StagesPasswordPartialUpdateOK stages password partial update o k
*/
type StagesPasswordPartialUpdateOK struct {
	Payload *models.PasswordStage
}

func (o *StagesPasswordPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /stages/password/{stage_uuid}/][%d] stagesPasswordPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *StagesPasswordPartialUpdateOK) GetPayload() *models.PasswordStage {
	return o.Payload
}

func (o *StagesPasswordPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PasswordStage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
