---
name: "Prepare docker environment variables"
description: "Prepare docker environment variables"

inputs:
  image-name:
    required: true
    description: "Docker image prefix"
  image-arch:
    required: false
    description: "Docker image arch"

outputs:
  shouldBuild:
    description: "Whether to build image or not"
    value: ${{ steps.ev.outputs.shouldBuild }}

  sha:
    description: "sha"
    value: ${{ steps.ev.outputs.sha }}

  version:
    description: "Version"
    value: ${{ steps.ev.outputs.version }}
  prerelease:
    description: "Prerelease"
    value: ${{ steps.ev.outputs.prerelease }}

  imageTags:
    description: "Docker image tags"
    value: ${{ steps.ev.outputs.imageTags }}
  imageMainTag:
    description: "Docker image main tag"
    value: ${{ steps.ev.outputs.imageMainTag }}

runs:
  using: "composite"
  steps:
    - name: Generate config
      id: ev
      shell: bash
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_ARCH: ${{ inputs.image-arch }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        python3 ${{ github.action_path }}/push_vars.py
