# Generated by Django 3.1.1 on 2020-09-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_crypto", "0002_create_self_signed_kp"),
        ("passbook_providers_proxy", "0004_auto_20200913_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxyprovider",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="passbook_crypto.certificatekeypair",
            ),
        ),
    ]
