# Generated by Django 5.2.17 on 2026-10-10 19:35

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import move_credentials

FIELDS = [("kubeconfig", "kubeconfig_ref", "json", "kubeconfig")]


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0004_role_permissions"),
        ("authentik_rbac", "0011_initialpermissionspermission"),
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_outposts", "0022_outpostprovider_alter_outpost_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="kubernetesserviceconnection",
            name="kubeconfig_ref",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kubernetes_connections",
                to="authentik_crypto_secrets.secret",
                verbose_name="Kubeconfig",
            ),
        ),
        migrations.AlterField(
            model_name="kubernetesserviceconnection",
            name="kubeconfig",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Paste your kubeconfig here. authentik will automatically use the currently selected context.",
            ),
        ),
        move_credentials(
            "authentik_outposts", "KubernetesServiceConnection", FIELDS, value_permission="change"
        ),
    ]
