# Generated by Django 5.1.11 on 2025-07-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_outposts", "0024_proxysession_deleted_at_proxysession_updated_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="proxysession",
            index=models.Index(fields=["deleted_at"], name="authentik_o_deleted_abefff_idx"),
        ),
    ]
