# Generated by Django 5.2.17 on 2026-08-30 21:31

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import (
    migrate_credentials,
    restore_credentials,
)

FIELDS = [("_bot_token", "secret", None, "bot token")]


def migrate_bot_token(apps, schema_editor):
    migrate_credentials(apps, schema_editor, "authentik_sources_telegram", "TelegramSource", FIELDS)


def rollback_bot_token(apps, schema_editor):
    restore_credentials(apps, schema_editor, "authentik_sources_telegram", "TelegramSource", FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_sources_telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramsource",
            name="bot_token",
            field=models.TextField(db_column="bot_token", help_text="Telegram bot token"),
        ),
        migrations.RenameField(
            model_name="telegramsource",
            old_name="bot_token",
            new_name="_bot_token",
        ),
        migrations.AddField(
            model_name="telegramsource",
            name="secret",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Telegram bot token",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="telegram_sources",
                to="authentik_crypto_secrets.secret",
                verbose_name="Bot token",
            ),
        ),
        migrations.RunPython(migrate_bot_token, rollback_bot_token),
    ]
