# Generated by Django 5.1.11 on 2025-07-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0049_alter_token_options"),
        ("authentik_sources_telegram", "0002_alter_telegramsource_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSourcePropertyMapping",
            fields=[
                (
                    "propertymapping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.propertymapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Source Property Mapping",
                "verbose_name_plural": "Telegram Source Property Mappings",
            },
            bases=("authentik_core.propertymapping",),
        ),
    ]
