# Generated by Django 2.2.3 on 2019-07-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
        ('passbook_core', '0024_ssologinpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIDProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='passbook_core.Provider')),
                ('oidc_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client')),
            ],
            bases=('passbook_core.provider',),
        ),
    ]
