// Code generated by go-swagger; DO NOT EDIT.

package core

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/BeryJu/passbook/proxy/pkg/models"
)

// CoreApplicationsReadReader is a Reader for the CoreApplicationsRead structure.
type CoreApplicationsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CoreApplicationsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCoreApplicationsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCoreApplicationsReadOK creates a CoreApplicationsReadOK with default headers values
func NewCoreApplicationsReadOK() *CoreApplicationsReadOK {
	return &CoreApplicationsReadOK{}
}

/*CoreApplicationsReadOK handles this case with default header values.

CoreApplicationsReadOK core applications read o k
*/
type CoreApplicationsReadOK struct {
	Payload *models.Application
}

func (o *CoreApplicationsReadOK) Error() string {
	return fmt.Sprintf("[GET /core/applications/{pbm_uuid}/][%d] coreApplicationsReadOK  %+v", 200, o.Payload)
}

func (o *CoreApplicationsReadOK) GetPayload() *models.Application {
	return o.Payload
}

func (o *CoreApplicationsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
