/* Patternfly's default variable collection; this is what ships with Patternfly 4.
   This file is intended as a check against what the style engine produces.
 */

export const patternflyLightTheme = {
    "--pf-global--BackgroundColor--100": "#fff",
    "--pf-global--BackgroundColor--150": "#fafafa",
    "--pf-global--BackgroundColor--200": "#f0f0f0",
    "--pf-global--BackgroundColor--light-100": "#fff",
    "--pf-global--BackgroundColor--light-200": "#fafafa",
    "--pf-global--BackgroundColor--light-300": "#f0f0f0",
    "--pf-global--BackgroundColor--dark-100": "#151515",
    "--pf-global--BackgroundColor--dark-200": "#3c3f42",
    "--pf-global--BackgroundColor--dark-300": "#212427",
    "--pf-global--BackgroundColor--dark-400": "#4f5255",
    "--pf-global--BackgroundColor--dark-transparent-100": "rgba(3, 3, 3, 0.62)",
    "--pf-global--BackgroundColor--dark-transparent-200": "rgba(3, 3, 3, 0.32)",
    "--pf-global--Color--100": "#151515",
    "--pf-global--Color--200": "#6a6e73",
    "--pf-global--Color--300": "#3c3f42",
    "--pf-global--Color--400": "#8a8d90",
    "--pf-global--Color--light-100": "#fff",
    "--pf-global--Color--light-200": "#f0f0f0",
    "--pf-global--Color--light-300": "#d2d2d2",
    "--pf-global--Color--dark-100": "#151515",
    "--pf-global--Color--dark-200": "#6a6e73",
    "--pf-global--active-color--100": "#06c",
    "--pf-global--active-color--200": "#bee1f4",
    "--pf-global--active-color--300": "#2b9af3",
    "--pf-global--active-color--400": "#73bcf7",
    "--pf-global--disabled-color--100": "#6a6e73",
    "--pf-global--disabled-color--200": "#d2d2d2",
    "--pf-global--disabled-color--300": "#f0f0f0",
    "--pf-global--primary-color--100": "#06c",
    "--pf-global--primary-color--200": "#004080",
    "--pf-global--primary-color--light-100": "#73bcf7",
    "--pf-global--primary-color--dark-100": "#06c",
    "--pf-global--secondary-color--100": "#6a6e73",
    "--pf-global--default-color--100": "#73c5c5",
    "--pf-global--default-color--200": "#009596",
    "--pf-global--default-color--300": "#003737",
    "--pf-global--success-color--100": "#3e8635",
    "--pf-global--success-color--200": "#1e4f18",
    "--pf-global--info-color--100": "#2b9af3",
    "--pf-global--info-color--200": "#002952",
    "--pf-global--warning-color--100": "#f0ab00",
    "--pf-global--warning-color--200": "#795600",
    "--pf-global--danger-color--100": "#c9190b",
    "--pf-global--danger-color--200": "#a30000",
    "--pf-global--danger-color--300": "#470000",
    "--pf-global--BoxShadow--sm":
        "0 0.0625rem 0.125rem 0 rgba(3, 3, 3, 0.12), 0 0 0.125rem 0 rgba(3, 3, 3, 0.06)",
    "--pf-global--BoxShadow--sm-top": "0 -0.125rem 0.25rem -0.0625rem rgba(3, 3, 3, 0.16)",
    "--pf-global--BoxShadow--sm-right": "0.125rem 0 0.25rem -0.0625rem rgba(3, 3, 3, 0.16)",
    "--pf-global--BoxShadow--sm-bottom": "0 0.125rem 0.25rem -0.0625rem rgba(3, 3, 3, 0.16)",
    "--pf-global--BoxShadow--sm-left": "-0.125rem 0 0.25rem -0.0625rem rgba(3, 3, 3, 0.16)",
    "--pf-global--BoxShadow--md":
        "0 0.25rem 0.5rem 0rem rgba(3, 3, 3, 0.12), 0 0 0.25rem 0 rgba(3, 3, 3, 0.06)",
    "--pf-global--BoxShadow--md-top": "0 -0.5rem 0.5rem -0.375rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--md-right": "0.5rem 0 0.5rem -0.375rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--md-bottom": "0 0.5rem 0.5rem -0.375rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--md-left": "-0.5rem 0 0.5rem -0.375rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--lg":
        "0 0.5rem 1rem 0 rgba(3, 3, 3, 0.16), 0 0 0.375rem 0 rgba(3, 3, 3, 0.08)",
    "--pf-global--BoxShadow--lg-top": "0 -0.75rem 0.75rem -0.5rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--lg-right": "0.75rem 0 0.75rem -0.5rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--lg-bottom": "0 0.75rem 0.75rem -0.5rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--lg-left": "-0.75rem 0 0.75rem -0.5rem rgba(3, 3, 3, 0.18)",
    "--pf-global--BoxShadow--xl":
        "0 1rem 2rem 0 rgba(3, 3, 3, 0.16), 0 0 0.5rem 0 rgba(3, 3, 3, 0.1)",
    "--pf-global--BoxShadow--xl-top": "0 -1rem 1rem -0.5rem rgba(3, 3, 3, 0.2)",
    "--pf-global--BoxShadow--xl-right": "1rem 0 1rem -0.5rem rgba(3, 3, 3, 0.2)",
    "--pf-global--BoxShadow--xl-bottom": "0 1rem 1rem -0.5rem rgba(3, 3, 3, 0.2)",
    "--pf-global--BoxShadow--xl-left": "-1rem 0 1rem -0.5rem rgba(3, 3, 3, 0.2)",
    "--pf-global--BoxShadow--inset": "inset 0 0 0.625rem 0 rgba(3, 3, 3, 0.25)",
    "--pf-global--font-path": '"./assets/fonts"',
    "--pf-global--fonticon-path": '"./assets/pficon"',
    "--pf-global--spacer--xs": "0.25rem",
    "--pf-global--spacer--sm": "0.5rem",
    "--pf-global--spacer--md": "1rem",
    "--pf-global--spacer--lg": "1.5rem",
    "--pf-global--spacer--xl": "2rem",
    "--pf-global--spacer--2xl": "3rem",
    "--pf-global--spacer--3xl": "4rem",
    "--pf-global--spacer--4xl": "5rem",
    "--pf-global--spacer--form-element": "0.375rem",
    "--pf-global--gutter": "1rem",
    "--pf-global--gutter--md": "1.5rem",
    "--pf-global--ZIndex--xs": "100",
    "--pf-global--ZIndex--sm": "200",
    "--pf-global--ZIndex--md": "300",
    "--pf-global--ZIndex--lg": "400",
    "--pf-global--ZIndex--xl": "500",
    "--pf-global--ZIndex--2xl": "600",
    "--pf-global--breakpoint--xs": "0",
    "--pf-global--breakpoint--sm": "576px",
    "--pf-global--breakpoint--md": "768px",
    "--pf-global--breakpoint--lg": "992px",
    "--pf-global--breakpoint--xl": "1200px",
    "--pf-global--breakpoint--2xl": "1450px",
    "--pf-global--height-breakpoint--sm": "0",
    "--pf-global--height-breakpoint--md": "40rem",
    "--pf-global--height-breakpoint--lg": "48rem",
    "--pf-global--height-breakpoint--xl": "60rem",
    "--pf-global--height-breakpoint--2xl": "80rem",
    "--pf-global--link--Color": "#06c",
    "--pf-global--link--Color--hover": "#004080",
    "--pf-global--link--Color--light": "#2b9af3",
    "--pf-global--link--Color--light--hover": "#73bcf7",
    "--pf-global--link--Color--dark": "#06c",
    "--pf-global--link--Color--dark--hover": "#004080",
    "--pf-global--link--Color--visited": "#40199a",
    "--pf-global--link--TextDecoration": "none",
    "--pf-global--link--TextDecoration--hover": "underline",
    "--pf-global--BorderWidth--sm": "1px",
    "--pf-global--BorderWidth--md": "2px",
    "--pf-global--BorderWidth--lg": "3px",
    "--pf-global--BorderWidth--xl": "4px",
    "--pf-global--BorderColor--100": "#d2d2d2",
    "--pf-global--BorderColor--200": "#8a8d90",
    "--pf-global--BorderColor--300": "#f0f0f0",
    "--pf-global--BorderColor--dark-100": "#d2d2d2",
    "--pf-global--BorderColor--light-100": "#b8bbbe",
    "--pf-global--BorderRadius--sm": "3px",
    "--pf-global--BorderRadius--lg": "30em",
    "--pf-global--icon--Color--light": "#6a6e73",
    "--pf-global--icon--Color--dark": "#151515",
    "--pf-global--icon--FontSize--sm": "0.625rem",
    "--pf-global--icon--FontSize--md": "1.125rem",
    "--pf-global--icon--FontSize--lg": "1.5rem",
    "--pf-global--icon--FontSize--xl": "3.375rem",
    "--pf-global--FontFamily--sans-serif":
        '"RedHatText", "Overpass", overpass, helvetica, arial, sans-serif"',
    "--pf-global--FontFamily--heading--sans-serif":
        '"RedHatDisplay", "Overpass", overpass, helvetica, arial, sans-serif"',
    "--pf-global--FontFamily--monospace":
        '"Liberation Mono", consolas, "SFMono-Regular", menlo, monaco, "Courier New", monospace"',
    "--pf-global--FontFamily--redhat-updated--sans-serif":
        '"RedHatTextUpdated", "Overpass", overpass, helvetica, arial, sans-serif"',
    "--pf-global--FontFamily--redhat-updated--heading--sans-serif":
        '"RedHatDisplayUpdated", "Overpass", overpass, helvetica, arial, sans-serif"',
    "--pf-global--FontFamily--redhat--monospace":
        '"RedHatMono", "Liberation Mono", consolas, "SFMono-Regular", menlo, monaco, "Courier New", monospace"',
    "--pf-global--FontFamily--redhatVF--sans-serif":
        '"RedHatTextVF", "RedHatText", "Overpass", overpass, helvetica, arial, sans-serif"',
    "--pf-global--FontFamily--redhatVF--heading--sans-serif":
        '"RedHatDisplayVF", "RedHatDisplay", "Overpass", overpass, helvetica, arial, sans-serif"',
    "--pf-global--FontFamily--redhatVF--monospace":
        '"RedHatMonoVF", "RedHatMono", "Liberation Mono", consolas, "SFMono-Regular", menlo, monaco, "Courier New", monospace"',
    "--pf-global--FontFamily--overpass--sans-serif":
        '"overpass", overpass, "open sans", -apple-system, blinkmacsystemfont, "Segoe UI", roboto, "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    "--pf-global--FontFamily--overpass--monospace":
        '"overpass-mono", overpass-mono, "SFMono-Regular", menlo, monaco, consolas, "Liberation Mono", "Courier New", monospace"',
    "--pf-global--FontSize--4xl": "2.25rem",
    "--pf-global--FontSize--3xl": "1.75rem",
    "--pf-global--FontSize--2xl": "1.5rem",
    "--pf-global--FontSize--xl": "1.25rem",
    "--pf-global--FontSize--lg": "1.125rem",
    "--pf-global--FontSize--md": "1rem",
    "--pf-global--FontSize--sm": "0.875rem",
    "--pf-global--FontSize--xs": "0.75rem",
    "--pf-global--FontWeight--light": "300",
    "--pf-global--FontWeight--normal": "400",
    "--pf-global--FontWeight--semi-bold": "700",
    "--pf-global--FontWeight--overpass--semi-bold": "500",
    "--pf-global--FontWeight--bold": "700",
    "--pf-global--FontWeight--overpass--bold": "600",
    "--pf-global--LineHeight--sm": "1.3",
    "--pf-global--LineHeight--md": "1.5",
    "--pf-global--ListStyle": "disc outside",
    "--pf-global--Transition": "all 250ms cubic-bezier(0.42, 0, 0.58, 1)",
    "--pf-global--TimingFunction": "cubic-bezier(0.645, 0.045, 0.355, 1)",
    "--pf-global--TransitionDuration": "250ms",
    "--pf-global--arrow--width": "0.9375rem",
    "--pf-global--arrow--width-lg": "1.5625rem",
    "--pf-global--target-size--MinWidth": "44px",
    "--pf-global--target-size--MinHeight": "44px",
};
