# Generated by Django 4.2.3 on 2023-08-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_core", "0031_alter_user_type"),
        ("authentik_providers_kerberos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KerberosPrincipalMapping",
            fields=[
                (
                    "propertymapping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.propertymapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kerberos Principal Mapping",
                "verbose_name_plural": "Kerberos Principal Mappings",
            },
            bases=("authentik_core.propertymapping",),
        ),
        migrations.AddField(
            model_name="kerberosrealm",
            name="principal_to_user_pm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="kerberosrealm_principaltouser",
                to="authentik_providers_kerberos.kerberosprincipalmapping",
            ),
        ),
        migrations.AddField(
            model_name="kerberosrealm",
            name="user_to_principal_pm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="kerberosrealm_usertoprincipal",
                to="authentik_providers_kerberos.kerberosprincipalmapping",
            ),
        ),
    ]
