git:
  filters:
    - filter_type: file
      # all supported i18n types: https://docs.transifex.com/formats
      file_format: XLIFF
      source_language: en
      source_file: web/xliff/en.xlf
      # path expression to translation files, must contain <lang> placeholder
      translation_files_expression: "web/xliff/<lang>.xlf"
    - filter_type: file
      # all supported i18n types: https://docs.transifex.com/formats
      file_format: PO
      source_language: en
      source_file: locale/en/LC_MESSAGES/django.po
      # path expression to translation files, must contain <lang> placeholder
      translation_files_expression: "locale/<lang>/LC_MESSAGES/django.po"
