---
globalProperties:
  supportingFiles: ""
  apis: ""
  models: ""
  apiDocs: false
  apiTests: false
  modelDocs: false
  modelTests: false
additionalProperties:
  packageName: api
  enumClassPrefix: true
  useOneOfDiscriminatorLookup: true
  disallowAdditionalPropertiesIfNotPresent: false
