/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the UserRecoveryEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserRecoveryEmailRequest{}

// UserRecoveryEmailRequest Payload to create and email a recovery link
type UserRecoveryEmailRequest struct {
	TokenDuration        *string `json:"token_duration,omitempty"`
	EmailStage           string  `json:"email_stage"`
	AdditionalProperties map[string]interface{}
}

type _UserRecoveryEmailRequest UserRecoveryEmailRequest

// NewUserRecoveryEmailRequest instantiates a new UserRecoveryEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRecoveryEmailRequest(emailStage string) *UserRecoveryEmailRequest {
	this := UserRecoveryEmailRequest{}
	this.EmailStage = emailStage
	return &this
}

// NewUserRecoveryEmailRequestWithDefaults instantiates a new UserRecoveryEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRecoveryEmailRequestWithDefaults() *UserRecoveryEmailRequest {
	this := UserRecoveryEmailRequest{}
	return &this
}

// GetTokenDuration returns the TokenDuration field value if set, zero value otherwise.
func (o *UserRecoveryEmailRequest) GetTokenDuration() string {
	if o == nil || IsNil(o.TokenDuration) {
		var ret string
		return ret
	}
	return *o.TokenDuration
}

// GetTokenDurationOk returns a tuple with the TokenDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserRecoveryEmailRequest) GetTokenDurationOk() (*string, bool) {
	if o == nil || IsNil(o.TokenDuration) {
		return nil, false
	}
	return o.TokenDuration, true
}

// HasTokenDuration returns a boolean if a field has been set.
func (o *UserRecoveryEmailRequest) HasTokenDuration() bool {
	if o != nil && !IsNil(o.TokenDuration) {
		return true
	}

	return false
}

// SetTokenDuration gets a reference to the given string and assigns it to the TokenDuration field.
func (o *UserRecoveryEmailRequest) SetTokenDuration(v string) {
	o.TokenDuration = &v
}

// GetEmailStage returns the EmailStage field value
func (o *UserRecoveryEmailRequest) GetEmailStage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailStage
}

// GetEmailStageOk returns a tuple with the EmailStage field value
// and a boolean to check if the value has been set.
func (o *UserRecoveryEmailRequest) GetEmailStageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailStage, true
}

// SetEmailStage sets field value
func (o *UserRecoveryEmailRequest) SetEmailStage(v string) {
	o.EmailStage = v
}

func (o UserRecoveryEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserRecoveryEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TokenDuration) {
		toSerialize["token_duration"] = o.TokenDuration
	}
	toSerialize["email_stage"] = o.EmailStage

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserRecoveryEmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email_stage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserRecoveryEmailRequest := _UserRecoveryEmailRequest{}

	err = json.Unmarshal(data, &varUserRecoveryEmailRequest)

	if err != nil {
		return err
	}

	*o = UserRecoveryEmailRequest(varUserRecoveryEmailRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "token_duration")
		delete(additionalProperties, "email_stage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserRecoveryEmailRequest struct {
	value *UserRecoveryEmailRequest
	isSet bool
}

func (v NullableUserRecoveryEmailRequest) Get() *UserRecoveryEmailRequest {
	return v.value
}

func (v *NullableUserRecoveryEmailRequest) Set(val *UserRecoveryEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRecoveryEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRecoveryEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRecoveryEmailRequest(val *UserRecoveryEmailRequest) *NullableUserRecoveryEmailRequest {
	return &NullableUserRecoveryEmailRequest{value: val, isSet: true}
}

func (v NullableUserRecoveryEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRecoveryEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
