/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedConnectionTokenList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedConnectionTokenList{}

// PaginatedConnectionTokenList struct for PaginatedConnectionTokenList
type PaginatedConnectionTokenList struct {
	Pagination           Pagination             `json:"pagination"`
	Results              []ConnectionToken      `json:"results"`
	Autocomplete         map[string]interface{} `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedConnectionTokenList PaginatedConnectionTokenList

// NewPaginatedConnectionTokenList instantiates a new PaginatedConnectionTokenList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedConnectionTokenList(pagination Pagination, results []ConnectionToken, autocomplete map[string]interface{}) *PaginatedConnectionTokenList {
	this := PaginatedConnectionTokenList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedConnectionTokenListWithDefaults instantiates a new PaginatedConnectionTokenList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedConnectionTokenListWithDefaults() *PaginatedConnectionTokenList {
	this := PaginatedConnectionTokenList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedConnectionTokenList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedConnectionTokenList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedConnectionTokenList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedConnectionTokenList) GetResults() []ConnectionToken {
	if o == nil {
		var ret []ConnectionToken
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedConnectionTokenList) GetResultsOk() ([]ConnectionToken, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedConnectionTokenList) SetResults(v []ConnectionToken) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedConnectionTokenList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedConnectionTokenList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedConnectionTokenList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedConnectionTokenList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedConnectionTokenList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedConnectionTokenList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedConnectionTokenList := _PaginatedConnectionTokenList{}

	err = json.Unmarshal(data, &varPaginatedConnectionTokenList)

	if err != nil {
		return err
	}

	*o = PaginatedConnectionTokenList(varPaginatedConnectionTokenList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedConnectionTokenList struct {
	value *PaginatedConnectionTokenList
	isSet bool
}

func (v NullablePaginatedConnectionTokenList) Get() *PaginatedConnectionTokenList {
	return v.value
}

func (v *NullablePaginatedConnectionTokenList) Set(val *PaginatedConnectionTokenList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedConnectionTokenList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedConnectionTokenList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedConnectionTokenList(val *PaginatedConnectionTokenList) *NullablePaginatedConnectionTokenList {
	return &NullablePaginatedConnectionTokenList{value: val, isSet: true}
}

func (v NullablePaginatedConnectionTokenList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedConnectionTokenList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
