/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the EndpointStageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointStageRequest{}

// EndpointStageRequest EndpointStage Serializer
type EndpointStageRequest struct {
	Name                 string         `json:"name"`
	Connector            string         `json:"connector"`
	Mode                 *StageModeEnum `json:"mode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EndpointStageRequest EndpointStageRequest

// NewEndpointStageRequest instantiates a new EndpointStageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointStageRequest(name string, connector string) *EndpointStageRequest {
	this := EndpointStageRequest{}
	this.Name = name
	this.Connector = connector
	return &this
}

// NewEndpointStageRequestWithDefaults instantiates a new EndpointStageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointStageRequestWithDefaults() *EndpointStageRequest {
	this := EndpointStageRequest{}
	return &this
}

// GetName returns the Name field value
func (o *EndpointStageRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointStageRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointStageRequest) SetName(v string) {
	o.Name = v
}

// GetConnector returns the Connector field value
func (o *EndpointStageRequest) GetConnector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value
// and a boolean to check if the value has been set.
func (o *EndpointStageRequest) GetConnectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connector, true
}

// SetConnector sets field value
func (o *EndpointStageRequest) SetConnector(v string) {
	o.Connector = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *EndpointStageRequest) GetMode() StageModeEnum {
	if o == nil || IsNil(o.Mode) {
		var ret StageModeEnum
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointStageRequest) GetModeOk() (*StageModeEnum, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *EndpointStageRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given StageModeEnum and assigns it to the Mode field.
func (o *EndpointStageRequest) SetMode(v StageModeEnum) {
	o.Mode = &v
}

func (o EndpointStageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointStageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["connector"] = o.Connector
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EndpointStageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"connector",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointStageRequest := _EndpointStageRequest{}

	err = json.Unmarshal(data, &varEndpointStageRequest)

	if err != nil {
		return err
	}

	*o = EndpointStageRequest(varEndpointStageRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "connector")
		delete(additionalProperties, "mode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEndpointStageRequest struct {
	value *EndpointStageRequest
	isSet bool
}

func (v NullableEndpointStageRequest) Get() *EndpointStageRequest {
	return v.value
}

func (v *NullableEndpointStageRequest) Set(val *EndpointStageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointStageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointStageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointStageRequest(val *EndpointStageRequest) *NullableEndpointStageRequest {
	return &NullableEndpointStageRequest{value: val, isSet: true}
}

func (v NullableEndpointStageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointStageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
