/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedUserList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedUserList{}

// PaginatedUserList struct for PaginatedUserList
type PaginatedUserList struct {
	Pagination           Pagination             `json:"pagination"`
	Results              []User                 `json:"results"`
	Autocomplete         map[string]interface{} `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedUserList PaginatedUserList

// NewPaginatedUserList instantiates a new PaginatedUserList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedUserList(pagination Pagination, results []User, autocomplete map[string]interface{}) *PaginatedUserList {
	this := PaginatedUserList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedUserListWithDefaults instantiates a new PaginatedUserList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedUserListWithDefaults() *PaginatedUserList {
	this := PaginatedUserList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedUserList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedUserList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedUserList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedUserList) GetResults() []User {
	if o == nil {
		var ret []User
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedUserList) GetResultsOk() ([]User, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedUserList) SetResults(v []User) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedUserList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedUserList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedUserList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedUserList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedUserList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedUserList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedUserList := _PaginatedUserList{}

	err = json.Unmarshal(data, &varPaginatedUserList)

	if err != nil {
		return err
	}

	*o = PaginatedUserList(varPaginatedUserList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedUserList struct {
	value *PaginatedUserList
	isSet bool
}

func (v NullablePaginatedUserList) Get() *PaginatedUserList {
	return v.value
}

func (v *NullablePaginatedUserList) Set(val *PaginatedUserList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedUserList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedUserList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedUserList(val *PaginatedUserList) *NullablePaginatedUserList {
	return &NullablePaginatedUserList{value: val, isSet: true}
}

func (v NullablePaginatedUserList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedUserList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
