/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the FleetConnectorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FleetConnectorRequest{}

// FleetConnectorRequest FleetConnector Serializer
type FleetConnectorRequest struct {
	ConnectorUuid *string `json:"connector_uuid,omitempty"`
	Name          string  `json:"name"`
	Enabled       *bool   `json:"enabled,omitempty"`
	Url           string  `json:"url"`
	Token         string  `json:"token"`
	// Configure additional headers to be sent. Mapping should return a dictionary of key-value pairs
	HeadersMapping       NullableString `json:"headers_mapping,omitempty"`
	MapUsers             *bool          `json:"map_users,omitempty"`
	MapTeamsAccessGroup  *bool          `json:"map_teams_access_group,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FleetConnectorRequest FleetConnectorRequest

// NewFleetConnectorRequest instantiates a new FleetConnectorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFleetConnectorRequest(name string, url string, token string) *FleetConnectorRequest {
	this := FleetConnectorRequest{}
	this.Name = name
	this.Url = url
	this.Token = token
	return &this
}

// NewFleetConnectorRequestWithDefaults instantiates a new FleetConnectorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFleetConnectorRequestWithDefaults() *FleetConnectorRequest {
	this := FleetConnectorRequest{}
	return &this
}

// GetConnectorUuid returns the ConnectorUuid field value if set, zero value otherwise.
func (o *FleetConnectorRequest) GetConnectorUuid() string {
	if o == nil || IsNil(o.ConnectorUuid) {
		var ret string
		return ret
	}
	return *o.ConnectorUuid
}

// GetConnectorUuidOk returns a tuple with the ConnectorUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetConnectorUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectorUuid) {
		return nil, false
	}
	return o.ConnectorUuid, true
}

// HasConnectorUuid returns a boolean if a field has been set.
func (o *FleetConnectorRequest) HasConnectorUuid() bool {
	if o != nil && !IsNil(o.ConnectorUuid) {
		return true
	}

	return false
}

// SetConnectorUuid gets a reference to the given string and assigns it to the ConnectorUuid field.
func (o *FleetConnectorRequest) SetConnectorUuid(v string) {
	o.ConnectorUuid = &v
}

// GetName returns the Name field value
func (o *FleetConnectorRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FleetConnectorRequest) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *FleetConnectorRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *FleetConnectorRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *FleetConnectorRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetUrl returns the Url field value
func (o *FleetConnectorRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *FleetConnectorRequest) SetUrl(v string) {
	o.Url = v
}

// GetToken returns the Token field value
func (o *FleetConnectorRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *FleetConnectorRequest) SetToken(v string) {
	o.Token = v
}

// GetHeadersMapping returns the HeadersMapping field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FleetConnectorRequest) GetHeadersMapping() string {
	if o == nil || IsNil(o.HeadersMapping.Get()) {
		var ret string
		return ret
	}
	return *o.HeadersMapping.Get()
}

// GetHeadersMappingOk returns a tuple with the HeadersMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FleetConnectorRequest) GetHeadersMappingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HeadersMapping.Get(), o.HeadersMapping.IsSet()
}

// HasHeadersMapping returns a boolean if a field has been set.
func (o *FleetConnectorRequest) HasHeadersMapping() bool {
	if o != nil && o.HeadersMapping.IsSet() {
		return true
	}

	return false
}

// SetHeadersMapping gets a reference to the given NullableString and assigns it to the HeadersMapping field.
func (o *FleetConnectorRequest) SetHeadersMapping(v string) {
	o.HeadersMapping.Set(&v)
}

// SetHeadersMappingNil sets the value for HeadersMapping to be an explicit nil
func (o *FleetConnectorRequest) SetHeadersMappingNil() {
	o.HeadersMapping.Set(nil)
}

// UnsetHeadersMapping ensures that no value is present for HeadersMapping, not even an explicit nil
func (o *FleetConnectorRequest) UnsetHeadersMapping() {
	o.HeadersMapping.Unset()
}

// GetMapUsers returns the MapUsers field value if set, zero value otherwise.
func (o *FleetConnectorRequest) GetMapUsers() bool {
	if o == nil || IsNil(o.MapUsers) {
		var ret bool
		return ret
	}
	return *o.MapUsers
}

// GetMapUsersOk returns a tuple with the MapUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetMapUsersOk() (*bool, bool) {
	if o == nil || IsNil(o.MapUsers) {
		return nil, false
	}
	return o.MapUsers, true
}

// HasMapUsers returns a boolean if a field has been set.
func (o *FleetConnectorRequest) HasMapUsers() bool {
	if o != nil && !IsNil(o.MapUsers) {
		return true
	}

	return false
}

// SetMapUsers gets a reference to the given bool and assigns it to the MapUsers field.
func (o *FleetConnectorRequest) SetMapUsers(v bool) {
	o.MapUsers = &v
}

// GetMapTeamsAccessGroup returns the MapTeamsAccessGroup field value if set, zero value otherwise.
func (o *FleetConnectorRequest) GetMapTeamsAccessGroup() bool {
	if o == nil || IsNil(o.MapTeamsAccessGroup) {
		var ret bool
		return ret
	}
	return *o.MapTeamsAccessGroup
}

// GetMapTeamsAccessGroupOk returns a tuple with the MapTeamsAccessGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetConnectorRequest) GetMapTeamsAccessGroupOk() (*bool, bool) {
	if o == nil || IsNil(o.MapTeamsAccessGroup) {
		return nil, false
	}
	return o.MapTeamsAccessGroup, true
}

// HasMapTeamsAccessGroup returns a boolean if a field has been set.
func (o *FleetConnectorRequest) HasMapTeamsAccessGroup() bool {
	if o != nil && !IsNil(o.MapTeamsAccessGroup) {
		return true
	}

	return false
}

// SetMapTeamsAccessGroup gets a reference to the given bool and assigns it to the MapTeamsAccessGroup field.
func (o *FleetConnectorRequest) SetMapTeamsAccessGroup(v bool) {
	o.MapTeamsAccessGroup = &v
}

func (o FleetConnectorRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FleetConnectorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConnectorUuid) {
		toSerialize["connector_uuid"] = o.ConnectorUuid
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	toSerialize["url"] = o.Url
	toSerialize["token"] = o.Token
	if o.HeadersMapping.IsSet() {
		toSerialize["headers_mapping"] = o.HeadersMapping.Get()
	}
	if !IsNil(o.MapUsers) {
		toSerialize["map_users"] = o.MapUsers
	}
	if !IsNil(o.MapTeamsAccessGroup) {
		toSerialize["map_teams_access_group"] = o.MapTeamsAccessGroup
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FleetConnectorRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFleetConnectorRequest := _FleetConnectorRequest{}

	err = json.Unmarshal(data, &varFleetConnectorRequest)

	if err != nil {
		return err
	}

	*o = FleetConnectorRequest(varFleetConnectorRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connector_uuid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "url")
		delete(additionalProperties, "token")
		delete(additionalProperties, "headers_mapping")
		delete(additionalProperties, "map_users")
		delete(additionalProperties, "map_teams_access_group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFleetConnectorRequest struct {
	value *FleetConnectorRequest
	isSet bool
}

func (v NullableFleetConnectorRequest) Get() *FleetConnectorRequest {
	return v.value
}

func (v *NullableFleetConnectorRequest) Set(val *FleetConnectorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFleetConnectorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFleetConnectorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFleetConnectorRequest(val *FleetConnectorRequest) *NullableFleetConnectorRequest {
	return &NullableFleetConnectorRequest{value: val, isSet: true}
}

func (v NullableFleetConnectorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFleetConnectorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
