/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SCIMProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SCIMProvider{}

// SCIMProvider SCIMProvider Serializer
type SCIMProvider struct {
	Pk               int32    `json:"pk"`
	Name             string   `json:"name"`
	PropertyMappings []string `json:"property_mappings,omitempty"`
	// Property mappings used for group creation/updating.
	PropertyMappingsGroup []string `json:"property_mappings_group,omitempty"`
	// Get object component so that we know how to edit the object
	Component string `json:"component"`
	// Internal application name, used in URLs.
	AssignedBackchannelApplicationSlug NullableString `json:"assigned_backchannel_application_slug"`
	// Application's display Name.
	AssignedBackchannelApplicationName NullableString `json:"assigned_backchannel_application_name"`
	// Return object's verbose_name
	VerboseName string `json:"verbose_name"`
	// Return object's plural verbose_name
	VerboseNamePlural string `json:"verbose_name_plural"`
	// Return internal model name
	MetaModelName string `json:"meta_model_name"`
	// Base URL to SCIM requests, usually ends in /v2
	Url                string `json:"url"`
	VerifyCertificates *bool  `json:"verify_certificates,omitempty"`
	// Authentication token
	Token    *string                     `json:"token,omitempty"`
	AuthMode *SCIMAuthenticationModeEnum `json:"auth_mode,omitempty"`
	// OAuth Source used for authentication
	AuthOauth NullableString `json:"auth_oauth,omitempty"`
	// Additional OAuth parameters, such as grant_type
	AuthOauthParams map[string]interface{} `json:"auth_oauth_params,omitempty"`
	// Alter authentik behavior for vendor-specific SCIM implementations.
	CompatibilityMode *CompatibilityModeEnum `json:"compatibility_mode,omitempty"`
	// Cache duration for ServiceProviderConfig responses. Set minutes=0 to disable.
	ServiceProviderConfigCacheTimeout *string `json:"service_provider_config_cache_timeout,omitempty"`
	ExcludeUsersServiceAccount        *bool   `json:"exclude_users_service_account,omitempty"`
	// Controls the number of objects synced in a single task
	SyncPageSize *int32 `json:"sync_page_size,omitempty"`
	// Timeout for synchronization of a single page
	SyncPageTimeout *string `json:"sync_page_timeout,omitempty"`
	// Group filters used to define sync-scope for groups.
	GroupFilters []string `json:"group_filters,omitempty"`
	// When enabled, provider will not modify or create objects in the remote system.
	DryRun               *bool `json:"dry_run,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SCIMProvider SCIMProvider

// NewSCIMProvider instantiates a new SCIMProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSCIMProvider(pk int32, name string, component string, assignedBackchannelApplicationSlug NullableString, assignedBackchannelApplicationName NullableString, verboseName string, verboseNamePlural string, metaModelName string, url string) *SCIMProvider {
	this := SCIMProvider{}
	this.Pk = pk
	this.Name = name
	this.Component = component
	this.AssignedBackchannelApplicationSlug = assignedBackchannelApplicationSlug
	this.AssignedBackchannelApplicationName = assignedBackchannelApplicationName
	this.VerboseName = verboseName
	this.VerboseNamePlural = verboseNamePlural
	this.MetaModelName = metaModelName
	this.Url = url
	return &this
}

// NewSCIMProviderWithDefaults instantiates a new SCIMProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSCIMProviderWithDefaults() *SCIMProvider {
	this := SCIMProvider{}
	return &this
}

// GetPk returns the Pk field value
func (o *SCIMProvider) GetPk() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetPkOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *SCIMProvider) SetPk(v int32) {
	o.Pk = v
}

// GetName returns the Name field value
func (o *SCIMProvider) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SCIMProvider) SetName(v string) {
	o.Name = v
}

// GetPropertyMappings returns the PropertyMappings field value if set, zero value otherwise.
func (o *SCIMProvider) GetPropertyMappings() []string {
	if o == nil || IsNil(o.PropertyMappings) {
		var ret []string
		return ret
	}
	return o.PropertyMappings
}

// GetPropertyMappingsOk returns a tuple with the PropertyMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetPropertyMappingsOk() ([]string, bool) {
	if o == nil || IsNil(o.PropertyMappings) {
		return nil, false
	}
	return o.PropertyMappings, true
}

// HasPropertyMappings returns a boolean if a field has been set.
func (o *SCIMProvider) HasPropertyMappings() bool {
	if o != nil && !IsNil(o.PropertyMappings) {
		return true
	}

	return false
}

// SetPropertyMappings gets a reference to the given []string and assigns it to the PropertyMappings field.
func (o *SCIMProvider) SetPropertyMappings(v []string) {
	o.PropertyMappings = v
}

// GetPropertyMappingsGroup returns the PropertyMappingsGroup field value if set, zero value otherwise.
func (o *SCIMProvider) GetPropertyMappingsGroup() []string {
	if o == nil || IsNil(o.PropertyMappingsGroup) {
		var ret []string
		return ret
	}
	return o.PropertyMappingsGroup
}

// GetPropertyMappingsGroupOk returns a tuple with the PropertyMappingsGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetPropertyMappingsGroupOk() ([]string, bool) {
	if o == nil || IsNil(o.PropertyMappingsGroup) {
		return nil, false
	}
	return o.PropertyMappingsGroup, true
}

// HasPropertyMappingsGroup returns a boolean if a field has been set.
func (o *SCIMProvider) HasPropertyMappingsGroup() bool {
	if o != nil && !IsNil(o.PropertyMappingsGroup) {
		return true
	}

	return false
}

// SetPropertyMappingsGroup gets a reference to the given []string and assigns it to the PropertyMappingsGroup field.
func (o *SCIMProvider) SetPropertyMappingsGroup(v []string) {
	o.PropertyMappingsGroup = v
}

// GetComponent returns the Component field value
func (o *SCIMProvider) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *SCIMProvider) SetComponent(v string) {
	o.Component = v
}

// GetAssignedBackchannelApplicationSlug returns the AssignedBackchannelApplicationSlug field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SCIMProvider) GetAssignedBackchannelApplicationSlug() string {
	if o == nil || o.AssignedBackchannelApplicationSlug.Get() == nil {
		var ret string
		return ret
	}

	return *o.AssignedBackchannelApplicationSlug.Get()
}

// GetAssignedBackchannelApplicationSlugOk returns a tuple with the AssignedBackchannelApplicationSlug field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMProvider) GetAssignedBackchannelApplicationSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssignedBackchannelApplicationSlug.Get(), o.AssignedBackchannelApplicationSlug.IsSet()
}

// SetAssignedBackchannelApplicationSlug sets field value
func (o *SCIMProvider) SetAssignedBackchannelApplicationSlug(v string) {
	o.AssignedBackchannelApplicationSlug.Set(&v)
}

// GetAssignedBackchannelApplicationName returns the AssignedBackchannelApplicationName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SCIMProvider) GetAssignedBackchannelApplicationName() string {
	if o == nil || o.AssignedBackchannelApplicationName.Get() == nil {
		var ret string
		return ret
	}

	return *o.AssignedBackchannelApplicationName.Get()
}

// GetAssignedBackchannelApplicationNameOk returns a tuple with the AssignedBackchannelApplicationName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMProvider) GetAssignedBackchannelApplicationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssignedBackchannelApplicationName.Get(), o.AssignedBackchannelApplicationName.IsSet()
}

// SetAssignedBackchannelApplicationName sets field value
func (o *SCIMProvider) SetAssignedBackchannelApplicationName(v string) {
	o.AssignedBackchannelApplicationName.Set(&v)
}

// GetVerboseName returns the VerboseName field value
func (o *SCIMProvider) GetVerboseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerboseName
}

// GetVerboseNameOk returns a tuple with the VerboseName field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetVerboseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerboseName, true
}

// SetVerboseName sets field value
func (o *SCIMProvider) SetVerboseName(v string) {
	o.VerboseName = v
}

// GetVerboseNamePlural returns the VerboseNamePlural field value
func (o *SCIMProvider) GetVerboseNamePlural() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerboseNamePlural
}

// GetVerboseNamePluralOk returns a tuple with the VerboseNamePlural field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetVerboseNamePluralOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerboseNamePlural, true
}

// SetVerboseNamePlural sets field value
func (o *SCIMProvider) SetVerboseNamePlural(v string) {
	o.VerboseNamePlural = v
}

// GetMetaModelName returns the MetaModelName field value
func (o *SCIMProvider) GetMetaModelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetaModelName
}

// GetMetaModelNameOk returns a tuple with the MetaModelName field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetMetaModelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaModelName, true
}

// SetMetaModelName sets field value
func (o *SCIMProvider) SetMetaModelName(v string) {
	o.MetaModelName = v
}

// GetUrl returns the Url field value
func (o *SCIMProvider) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SCIMProvider) SetUrl(v string) {
	o.Url = v
}

// GetVerifyCertificates returns the VerifyCertificates field value if set, zero value otherwise.
func (o *SCIMProvider) GetVerifyCertificates() bool {
	if o == nil || IsNil(o.VerifyCertificates) {
		var ret bool
		return ret
	}
	return *o.VerifyCertificates
}

// GetVerifyCertificatesOk returns a tuple with the VerifyCertificates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetVerifyCertificatesOk() (*bool, bool) {
	if o == nil || IsNil(o.VerifyCertificates) {
		return nil, false
	}
	return o.VerifyCertificates, true
}

// HasVerifyCertificates returns a boolean if a field has been set.
func (o *SCIMProvider) HasVerifyCertificates() bool {
	if o != nil && !IsNil(o.VerifyCertificates) {
		return true
	}

	return false
}

// SetVerifyCertificates gets a reference to the given bool and assigns it to the VerifyCertificates field.
func (o *SCIMProvider) SetVerifyCertificates(v bool) {
	o.VerifyCertificates = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *SCIMProvider) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *SCIMProvider) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *SCIMProvider) SetToken(v string) {
	o.Token = &v
}

// GetAuthMode returns the AuthMode field value if set, zero value otherwise.
func (o *SCIMProvider) GetAuthMode() SCIMAuthenticationModeEnum {
	if o == nil || IsNil(o.AuthMode) {
		var ret SCIMAuthenticationModeEnum
		return ret
	}
	return *o.AuthMode
}

// GetAuthModeOk returns a tuple with the AuthMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetAuthModeOk() (*SCIMAuthenticationModeEnum, bool) {
	if o == nil || IsNil(o.AuthMode) {
		return nil, false
	}
	return o.AuthMode, true
}

// HasAuthMode returns a boolean if a field has been set.
func (o *SCIMProvider) HasAuthMode() bool {
	if o != nil && !IsNil(o.AuthMode) {
		return true
	}

	return false
}

// SetAuthMode gets a reference to the given SCIMAuthenticationModeEnum and assigns it to the AuthMode field.
func (o *SCIMProvider) SetAuthMode(v SCIMAuthenticationModeEnum) {
	o.AuthMode = &v
}

// GetAuthOauth returns the AuthOauth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SCIMProvider) GetAuthOauth() string {
	if o == nil || IsNil(o.AuthOauth.Get()) {
		var ret string
		return ret
	}
	return *o.AuthOauth.Get()
}

// GetAuthOauthOk returns a tuple with the AuthOauth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SCIMProvider) GetAuthOauthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthOauth.Get(), o.AuthOauth.IsSet()
}

// HasAuthOauth returns a boolean if a field has been set.
func (o *SCIMProvider) HasAuthOauth() bool {
	if o != nil && o.AuthOauth.IsSet() {
		return true
	}

	return false
}

// SetAuthOauth gets a reference to the given NullableString and assigns it to the AuthOauth field.
func (o *SCIMProvider) SetAuthOauth(v string) {
	o.AuthOauth.Set(&v)
}

// SetAuthOauthNil sets the value for AuthOauth to be an explicit nil
func (o *SCIMProvider) SetAuthOauthNil() {
	o.AuthOauth.Set(nil)
}

// UnsetAuthOauth ensures that no value is present for AuthOauth, not even an explicit nil
func (o *SCIMProvider) UnsetAuthOauth() {
	o.AuthOauth.Unset()
}

// GetAuthOauthParams returns the AuthOauthParams field value if set, zero value otherwise.
func (o *SCIMProvider) GetAuthOauthParams() map[string]interface{} {
	if o == nil || IsNil(o.AuthOauthParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.AuthOauthParams
}

// GetAuthOauthParamsOk returns a tuple with the AuthOauthParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetAuthOauthParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AuthOauthParams) {
		return map[string]interface{}{}, false
	}
	return o.AuthOauthParams, true
}

// HasAuthOauthParams returns a boolean if a field has been set.
func (o *SCIMProvider) HasAuthOauthParams() bool {
	if o != nil && !IsNil(o.AuthOauthParams) {
		return true
	}

	return false
}

// SetAuthOauthParams gets a reference to the given map[string]interface{} and assigns it to the AuthOauthParams field.
func (o *SCIMProvider) SetAuthOauthParams(v map[string]interface{}) {
	o.AuthOauthParams = v
}

// GetCompatibilityMode returns the CompatibilityMode field value if set, zero value otherwise.
func (o *SCIMProvider) GetCompatibilityMode() CompatibilityModeEnum {
	if o == nil || IsNil(o.CompatibilityMode) {
		var ret CompatibilityModeEnum
		return ret
	}
	return *o.CompatibilityMode
}

// GetCompatibilityModeOk returns a tuple with the CompatibilityMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetCompatibilityModeOk() (*CompatibilityModeEnum, bool) {
	if o == nil || IsNil(o.CompatibilityMode) {
		return nil, false
	}
	return o.CompatibilityMode, true
}

// HasCompatibilityMode returns a boolean if a field has been set.
func (o *SCIMProvider) HasCompatibilityMode() bool {
	if o != nil && !IsNil(o.CompatibilityMode) {
		return true
	}

	return false
}

// SetCompatibilityMode gets a reference to the given CompatibilityModeEnum and assigns it to the CompatibilityMode field.
func (o *SCIMProvider) SetCompatibilityMode(v CompatibilityModeEnum) {
	o.CompatibilityMode = &v
}

// GetServiceProviderConfigCacheTimeout returns the ServiceProviderConfigCacheTimeout field value if set, zero value otherwise.
func (o *SCIMProvider) GetServiceProviderConfigCacheTimeout() string {
	if o == nil || IsNil(o.ServiceProviderConfigCacheTimeout) {
		var ret string
		return ret
	}
	return *o.ServiceProviderConfigCacheTimeout
}

// GetServiceProviderConfigCacheTimeoutOk returns a tuple with the ServiceProviderConfigCacheTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetServiceProviderConfigCacheTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceProviderConfigCacheTimeout) {
		return nil, false
	}
	return o.ServiceProviderConfigCacheTimeout, true
}

// HasServiceProviderConfigCacheTimeout returns a boolean if a field has been set.
func (o *SCIMProvider) HasServiceProviderConfigCacheTimeout() bool {
	if o != nil && !IsNil(o.ServiceProviderConfigCacheTimeout) {
		return true
	}

	return false
}

// SetServiceProviderConfigCacheTimeout gets a reference to the given string and assigns it to the ServiceProviderConfigCacheTimeout field.
func (o *SCIMProvider) SetServiceProviderConfigCacheTimeout(v string) {
	o.ServiceProviderConfigCacheTimeout = &v
}

// GetExcludeUsersServiceAccount returns the ExcludeUsersServiceAccount field value if set, zero value otherwise.
func (o *SCIMProvider) GetExcludeUsersServiceAccount() bool {
	if o == nil || IsNil(o.ExcludeUsersServiceAccount) {
		var ret bool
		return ret
	}
	return *o.ExcludeUsersServiceAccount
}

// GetExcludeUsersServiceAccountOk returns a tuple with the ExcludeUsersServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetExcludeUsersServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeUsersServiceAccount) {
		return nil, false
	}
	return o.ExcludeUsersServiceAccount, true
}

// HasExcludeUsersServiceAccount returns a boolean if a field has been set.
func (o *SCIMProvider) HasExcludeUsersServiceAccount() bool {
	if o != nil && !IsNil(o.ExcludeUsersServiceAccount) {
		return true
	}

	return false
}

// SetExcludeUsersServiceAccount gets a reference to the given bool and assigns it to the ExcludeUsersServiceAccount field.
func (o *SCIMProvider) SetExcludeUsersServiceAccount(v bool) {
	o.ExcludeUsersServiceAccount = &v
}

// GetSyncPageSize returns the SyncPageSize field value if set, zero value otherwise.
func (o *SCIMProvider) GetSyncPageSize() int32 {
	if o == nil || IsNil(o.SyncPageSize) {
		var ret int32
		return ret
	}
	return *o.SyncPageSize
}

// GetSyncPageSizeOk returns a tuple with the SyncPageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetSyncPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.SyncPageSize) {
		return nil, false
	}
	return o.SyncPageSize, true
}

// HasSyncPageSize returns a boolean if a field has been set.
func (o *SCIMProvider) HasSyncPageSize() bool {
	if o != nil && !IsNil(o.SyncPageSize) {
		return true
	}

	return false
}

// SetSyncPageSize gets a reference to the given int32 and assigns it to the SyncPageSize field.
func (o *SCIMProvider) SetSyncPageSize(v int32) {
	o.SyncPageSize = &v
}

// GetSyncPageTimeout returns the SyncPageTimeout field value if set, zero value otherwise.
func (o *SCIMProvider) GetSyncPageTimeout() string {
	if o == nil || IsNil(o.SyncPageTimeout) {
		var ret string
		return ret
	}
	return *o.SyncPageTimeout
}

// GetSyncPageTimeoutOk returns a tuple with the SyncPageTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetSyncPageTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.SyncPageTimeout) {
		return nil, false
	}
	return o.SyncPageTimeout, true
}

// HasSyncPageTimeout returns a boolean if a field has been set.
func (o *SCIMProvider) HasSyncPageTimeout() bool {
	if o != nil && !IsNil(o.SyncPageTimeout) {
		return true
	}

	return false
}

// SetSyncPageTimeout gets a reference to the given string and assigns it to the SyncPageTimeout field.
func (o *SCIMProvider) SetSyncPageTimeout(v string) {
	o.SyncPageTimeout = &v
}

// GetGroupFilters returns the GroupFilters field value if set, zero value otherwise.
func (o *SCIMProvider) GetGroupFilters() []string {
	if o == nil || IsNil(o.GroupFilters) {
		var ret []string
		return ret
	}
	return o.GroupFilters
}

// GetGroupFiltersOk returns a tuple with the GroupFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetGroupFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupFilters) {
		return nil, false
	}
	return o.GroupFilters, true
}

// HasGroupFilters returns a boolean if a field has been set.
func (o *SCIMProvider) HasGroupFilters() bool {
	if o != nil && !IsNil(o.GroupFilters) {
		return true
	}

	return false
}

// SetGroupFilters gets a reference to the given []string and assigns it to the GroupFilters field.
func (o *SCIMProvider) SetGroupFilters(v []string) {
	o.GroupFilters = v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *SCIMProvider) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SCIMProvider) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *SCIMProvider) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *SCIMProvider) SetDryRun(v bool) {
	o.DryRun = &v
}

func (o SCIMProvider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SCIMProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["name"] = o.Name
	if !IsNil(o.PropertyMappings) {
		toSerialize["property_mappings"] = o.PropertyMappings
	}
	if !IsNil(o.PropertyMappingsGroup) {
		toSerialize["property_mappings_group"] = o.PropertyMappingsGroup
	}
	toSerialize["component"] = o.Component
	toSerialize["assigned_backchannel_application_slug"] = o.AssignedBackchannelApplicationSlug.Get()
	toSerialize["assigned_backchannel_application_name"] = o.AssignedBackchannelApplicationName.Get()
	toSerialize["verbose_name"] = o.VerboseName
	toSerialize["verbose_name_plural"] = o.VerboseNamePlural
	toSerialize["meta_model_name"] = o.MetaModelName
	toSerialize["url"] = o.Url
	if !IsNil(o.VerifyCertificates) {
		toSerialize["verify_certificates"] = o.VerifyCertificates
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.AuthMode) {
		toSerialize["auth_mode"] = o.AuthMode
	}
	if o.AuthOauth.IsSet() {
		toSerialize["auth_oauth"] = o.AuthOauth.Get()
	}
	if !IsNil(o.AuthOauthParams) {
		toSerialize["auth_oauth_params"] = o.AuthOauthParams
	}
	if !IsNil(o.CompatibilityMode) {
		toSerialize["compatibility_mode"] = o.CompatibilityMode
	}
	if !IsNil(o.ServiceProviderConfigCacheTimeout) {
		toSerialize["service_provider_config_cache_timeout"] = o.ServiceProviderConfigCacheTimeout
	}
	if !IsNil(o.ExcludeUsersServiceAccount) {
		toSerialize["exclude_users_service_account"] = o.ExcludeUsersServiceAccount
	}
	if !IsNil(o.SyncPageSize) {
		toSerialize["sync_page_size"] = o.SyncPageSize
	}
	if !IsNil(o.SyncPageTimeout) {
		toSerialize["sync_page_timeout"] = o.SyncPageTimeout
	}
	if !IsNil(o.GroupFilters) {
		toSerialize["group_filters"] = o.GroupFilters
	}
	if !IsNil(o.DryRun) {
		toSerialize["dry_run"] = o.DryRun
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SCIMProvider) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"name",
		"component",
		"assigned_backchannel_application_slug",
		"assigned_backchannel_application_name",
		"verbose_name",
		"verbose_name_plural",
		"meta_model_name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSCIMProvider := _SCIMProvider{}

	err = json.Unmarshal(data, &varSCIMProvider)

	if err != nil {
		return err
	}

	*o = SCIMProvider(varSCIMProvider)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "name")
		delete(additionalProperties, "property_mappings")
		delete(additionalProperties, "property_mappings_group")
		delete(additionalProperties, "component")
		delete(additionalProperties, "assigned_backchannel_application_slug")
		delete(additionalProperties, "assigned_backchannel_application_name")
		delete(additionalProperties, "verbose_name")
		delete(additionalProperties, "verbose_name_plural")
		delete(additionalProperties, "meta_model_name")
		delete(additionalProperties, "url")
		delete(additionalProperties, "verify_certificates")
		delete(additionalProperties, "token")
		delete(additionalProperties, "auth_mode")
		delete(additionalProperties, "auth_oauth")
		delete(additionalProperties, "auth_oauth_params")
		delete(additionalProperties, "compatibility_mode")
		delete(additionalProperties, "service_provider_config_cache_timeout")
		delete(additionalProperties, "exclude_users_service_account")
		delete(additionalProperties, "sync_page_size")
		delete(additionalProperties, "sync_page_timeout")
		delete(additionalProperties, "group_filters")
		delete(additionalProperties, "dry_run")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSCIMProvider struct {
	value *SCIMProvider
	isSet bool
}

func (v NullableSCIMProvider) Get() *SCIMProvider {
	return v.value
}

func (v *NullableSCIMProvider) Set(val *SCIMProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableSCIMProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableSCIMProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSCIMProvider(val *SCIMProvider) *NullableSCIMProvider {
	return &NullableSCIMProvider{value: val, isSet: true}
}

func (v NullableSCIMProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSCIMProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
