/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthenticatorEndpointGDTCStage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticatorEndpointGDTCStage{}

// AuthenticatorEndpointGDTCStage AuthenticatorEndpointGDTCStage Serializer
type AuthenticatorEndpointGDTCStage struct {
	Pk   string `json:"pk"`
	Name string `json:"name"`
	// Get object type so that we know how to edit the object
	Component string `json:"component"`
	// Return object's verbose_name
	VerboseName string `json:"verbose_name"`
	// Return object's plural verbose_name
	VerboseNamePlural string `json:"verbose_name_plural"`
	// Return internal model name
	MetaModelName string    `json:"meta_model_name"`
	FlowSet       []FlowSet `json:"flow_set"`
	// Flow used by an authenticated user to configure this Stage. If empty, user will not be able to configure this stage.
	ConfigureFlow        NullableString         `json:"configure_flow,omitempty"`
	FriendlyName         *string                `json:"friendly_name,omitempty"`
	Credentials          map[string]interface{} `json:"credentials"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticatorEndpointGDTCStage AuthenticatorEndpointGDTCStage

// NewAuthenticatorEndpointGDTCStage instantiates a new AuthenticatorEndpointGDTCStage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticatorEndpointGDTCStage(pk string, name string, component string, verboseName string, verboseNamePlural string, metaModelName string, flowSet []FlowSet, credentials map[string]interface{}) *AuthenticatorEndpointGDTCStage {
	this := AuthenticatorEndpointGDTCStage{}
	this.Pk = pk
	this.Name = name
	this.Component = component
	this.VerboseName = verboseName
	this.VerboseNamePlural = verboseNamePlural
	this.MetaModelName = metaModelName
	this.FlowSet = flowSet
	this.Credentials = credentials
	return &this
}

// NewAuthenticatorEndpointGDTCStageWithDefaults instantiates a new AuthenticatorEndpointGDTCStage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticatorEndpointGDTCStageWithDefaults() *AuthenticatorEndpointGDTCStage {
	this := AuthenticatorEndpointGDTCStage{}
	return &this
}

// GetPk returns the Pk field value
func (o *AuthenticatorEndpointGDTCStage) GetPk() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetPkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *AuthenticatorEndpointGDTCStage) SetPk(v string) {
	o.Pk = v
}

// GetName returns the Name field value
func (o *AuthenticatorEndpointGDTCStage) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthenticatorEndpointGDTCStage) SetName(v string) {
	o.Name = v
}

// GetComponent returns the Component field value
func (o *AuthenticatorEndpointGDTCStage) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *AuthenticatorEndpointGDTCStage) SetComponent(v string) {
	o.Component = v
}

// GetVerboseName returns the VerboseName field value
func (o *AuthenticatorEndpointGDTCStage) GetVerboseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerboseName
}

// GetVerboseNameOk returns a tuple with the VerboseName field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetVerboseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerboseName, true
}

// SetVerboseName sets field value
func (o *AuthenticatorEndpointGDTCStage) SetVerboseName(v string) {
	o.VerboseName = v
}

// GetVerboseNamePlural returns the VerboseNamePlural field value
func (o *AuthenticatorEndpointGDTCStage) GetVerboseNamePlural() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerboseNamePlural
}

// GetVerboseNamePluralOk returns a tuple with the VerboseNamePlural field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetVerboseNamePluralOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerboseNamePlural, true
}

// SetVerboseNamePlural sets field value
func (o *AuthenticatorEndpointGDTCStage) SetVerboseNamePlural(v string) {
	o.VerboseNamePlural = v
}

// GetMetaModelName returns the MetaModelName field value
func (o *AuthenticatorEndpointGDTCStage) GetMetaModelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetaModelName
}

// GetMetaModelNameOk returns a tuple with the MetaModelName field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetMetaModelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaModelName, true
}

// SetMetaModelName sets field value
func (o *AuthenticatorEndpointGDTCStage) SetMetaModelName(v string) {
	o.MetaModelName = v
}

// GetFlowSet returns the FlowSet field value
func (o *AuthenticatorEndpointGDTCStage) GetFlowSet() []FlowSet {
	if o == nil {
		var ret []FlowSet
		return ret
	}

	return o.FlowSet
}

// GetFlowSetOk returns a tuple with the FlowSet field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetFlowSetOk() ([]FlowSet, bool) {
	if o == nil {
		return nil, false
	}
	return o.FlowSet, true
}

// SetFlowSet sets field value
func (o *AuthenticatorEndpointGDTCStage) SetFlowSet(v []FlowSet) {
	o.FlowSet = v
}

// GetConfigureFlow returns the ConfigureFlow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthenticatorEndpointGDTCStage) GetConfigureFlow() string {
	if o == nil || IsNil(o.ConfigureFlow.Get()) {
		var ret string
		return ret
	}
	return *o.ConfigureFlow.Get()
}

// GetConfigureFlowOk returns a tuple with the ConfigureFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthenticatorEndpointGDTCStage) GetConfigureFlowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigureFlow.Get(), o.ConfigureFlow.IsSet()
}

// HasConfigureFlow returns a boolean if a field has been set.
func (o *AuthenticatorEndpointGDTCStage) HasConfigureFlow() bool {
	if o != nil && o.ConfigureFlow.IsSet() {
		return true
	}

	return false
}

// SetConfigureFlow gets a reference to the given NullableString and assigns it to the ConfigureFlow field.
func (o *AuthenticatorEndpointGDTCStage) SetConfigureFlow(v string) {
	o.ConfigureFlow.Set(&v)
}

// SetConfigureFlowNil sets the value for ConfigureFlow to be an explicit nil
func (o *AuthenticatorEndpointGDTCStage) SetConfigureFlowNil() {
	o.ConfigureFlow.Set(nil)
}

// UnsetConfigureFlow ensures that no value is present for ConfigureFlow, not even an explicit nil
func (o *AuthenticatorEndpointGDTCStage) UnsetConfigureFlow() {
	o.ConfigureFlow.Unset()
}

// GetFriendlyName returns the FriendlyName field value if set, zero value otherwise.
func (o *AuthenticatorEndpointGDTCStage) GetFriendlyName() string {
	if o == nil || IsNil(o.FriendlyName) {
		var ret string
		return ret
	}
	return *o.FriendlyName
}

// GetFriendlyNameOk returns a tuple with the FriendlyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetFriendlyNameOk() (*string, bool) {
	if o == nil || IsNil(o.FriendlyName) {
		return nil, false
	}
	return o.FriendlyName, true
}

// HasFriendlyName returns a boolean if a field has been set.
func (o *AuthenticatorEndpointGDTCStage) HasFriendlyName() bool {
	if o != nil && !IsNil(o.FriendlyName) {
		return true
	}

	return false
}

// SetFriendlyName gets a reference to the given string and assigns it to the FriendlyName field.
func (o *AuthenticatorEndpointGDTCStage) SetFriendlyName(v string) {
	o.FriendlyName = &v
}

// GetCredentials returns the Credentials field value
func (o *AuthenticatorEndpointGDTCStage) GetCredentials() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorEndpointGDTCStage) GetCredentialsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Credentials, true
}

// SetCredentials sets field value
func (o *AuthenticatorEndpointGDTCStage) SetCredentials(v map[string]interface{}) {
	o.Credentials = v
}

func (o AuthenticatorEndpointGDTCStage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticatorEndpointGDTCStage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["name"] = o.Name
	toSerialize["component"] = o.Component
	toSerialize["verbose_name"] = o.VerboseName
	toSerialize["verbose_name_plural"] = o.VerboseNamePlural
	toSerialize["meta_model_name"] = o.MetaModelName
	toSerialize["flow_set"] = o.FlowSet
	if o.ConfigureFlow.IsSet() {
		toSerialize["configure_flow"] = o.ConfigureFlow.Get()
	}
	if !IsNil(o.FriendlyName) {
		toSerialize["friendly_name"] = o.FriendlyName
	}
	toSerialize["credentials"] = o.Credentials

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthenticatorEndpointGDTCStage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"name",
		"component",
		"verbose_name",
		"verbose_name_plural",
		"meta_model_name",
		"flow_set",
		"credentials",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticatorEndpointGDTCStage := _AuthenticatorEndpointGDTCStage{}

	err = json.Unmarshal(data, &varAuthenticatorEndpointGDTCStage)

	if err != nil {
		return err
	}

	*o = AuthenticatorEndpointGDTCStage(varAuthenticatorEndpointGDTCStage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "name")
		delete(additionalProperties, "component")
		delete(additionalProperties, "verbose_name")
		delete(additionalProperties, "verbose_name_plural")
		delete(additionalProperties, "meta_model_name")
		delete(additionalProperties, "flow_set")
		delete(additionalProperties, "configure_flow")
		delete(additionalProperties, "friendly_name")
		delete(additionalProperties, "credentials")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthenticatorEndpointGDTCStage struct {
	value *AuthenticatorEndpointGDTCStage
	isSet bool
}

func (v NullableAuthenticatorEndpointGDTCStage) Get() *AuthenticatorEndpointGDTCStage {
	return v.value
}

func (v *NullableAuthenticatorEndpointGDTCStage) Set(val *AuthenticatorEndpointGDTCStage) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticatorEndpointGDTCStage) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticatorEndpointGDTCStage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticatorEndpointGDTCStage(val *AuthenticatorEndpointGDTCStage) *NullableAuthenticatorEndpointGDTCStage {
	return &NullableAuthenticatorEndpointGDTCStage{value: val, isSet: true}
}

func (v NullableAuthenticatorEndpointGDTCStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticatorEndpointGDTCStage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
