/*
authentik

Making authentication simple.

API version: 2026.8.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the AccountSelectionChallengeUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountSelectionChallengeUser{}

// AccountSelectionChallengeUser Account shown by the account selection stage.
type AccountSelectionChallengeUser struct {
	Uid                  string `json:"uid"`
	Username             string `json:"username"`
	Name                 string `json:"name"`
	Email                string `json:"email"`
	Avatar               string `json:"avatar"`
	IsCurrent            bool   `json:"is_current"`
	IsHint               bool   `json:"is_hint"`
	AdditionalProperties map[string]interface{}
}

type _AccountSelectionChallengeUser AccountSelectionChallengeUser

// NewAccountSelectionChallengeUser instantiates a new AccountSelectionChallengeUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountSelectionChallengeUser(uid string, username string, name string, email string, avatar string, isCurrent bool, isHint bool) *AccountSelectionChallengeUser {
	this := AccountSelectionChallengeUser{}
	this.Uid = uid
	this.Username = username
	this.Name = name
	this.Email = email
	this.Avatar = avatar
	this.IsCurrent = isCurrent
	this.IsHint = isHint
	return &this
}

// NewAccountSelectionChallengeUserWithDefaults instantiates a new AccountSelectionChallengeUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountSelectionChallengeUserWithDefaults() *AccountSelectionChallengeUser {
	this := AccountSelectionChallengeUser{}
	return &this
}

// GetUid returns the Uid field value
func (o *AccountSelectionChallengeUser) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *AccountSelectionChallengeUser) SetUid(v string) {
	o.Uid = v
}

// GetUsername returns the Username field value
func (o *AccountSelectionChallengeUser) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *AccountSelectionChallengeUser) SetUsername(v string) {
	o.Username = v
}

// GetName returns the Name field value
func (o *AccountSelectionChallengeUser) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccountSelectionChallengeUser) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *AccountSelectionChallengeUser) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AccountSelectionChallengeUser) SetEmail(v string) {
	o.Email = v
}

// GetAvatar returns the Avatar field value
func (o *AccountSelectionChallengeUser) GetAvatar() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetAvatarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Avatar, true
}

// SetAvatar sets field value
func (o *AccountSelectionChallengeUser) SetAvatar(v string) {
	o.Avatar = v
}

// GetIsCurrent returns the IsCurrent field value
func (o *AccountSelectionChallengeUser) GetIsCurrent() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCurrent
}

// GetIsCurrentOk returns a tuple with the IsCurrent field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetIsCurrentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCurrent, true
}

// SetIsCurrent sets field value
func (o *AccountSelectionChallengeUser) SetIsCurrent(v bool) {
	o.IsCurrent = v
}

// GetIsHint returns the IsHint field value
func (o *AccountSelectionChallengeUser) GetIsHint() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsHint
}

// GetIsHintOk returns a tuple with the IsHint field value
// and a boolean to check if the value has been set.
func (o *AccountSelectionChallengeUser) GetIsHintOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsHint, true
}

// SetIsHint sets field value
func (o *AccountSelectionChallengeUser) SetIsHint(v bool) {
	o.IsHint = v
}

func (o AccountSelectionChallengeUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountSelectionChallengeUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uid"] = o.Uid
	toSerialize["username"] = o.Username
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	toSerialize["avatar"] = o.Avatar
	toSerialize["is_current"] = o.IsCurrent
	toSerialize["is_hint"] = o.IsHint

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountSelectionChallengeUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uid",
		"username",
		"name",
		"email",
		"avatar",
		"is_current",
		"is_hint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountSelectionChallengeUser := _AccountSelectionChallengeUser{}

	err = json.Unmarshal(data, &varAccountSelectionChallengeUser)

	if err != nil {
		return err
	}

	*o = AccountSelectionChallengeUser(varAccountSelectionChallengeUser)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uid")
		delete(additionalProperties, "username")
		delete(additionalProperties, "name")
		delete(additionalProperties, "email")
		delete(additionalProperties, "avatar")
		delete(additionalProperties, "is_current")
		delete(additionalProperties, "is_hint")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountSelectionChallengeUser struct {
	value *AccountSelectionChallengeUser
	isSet bool
}

func (v NullableAccountSelectionChallengeUser) Get() *AccountSelectionChallengeUser {
	return v.value
}

func (v *NullableAccountSelectionChallengeUser) Set(val *AccountSelectionChallengeUser) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountSelectionChallengeUser) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountSelectionChallengeUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountSelectionChallengeUser(val *AccountSelectionChallengeUser) *NullableAccountSelectionChallengeUser {
	return &NullableAccountSelectionChallengeUser{value: val, isSet: true}
}

func (v NullableAccountSelectionChallengeUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountSelectionChallengeUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
