/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PatchedTenantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedTenantRequest{}

// PatchedTenantRequest Tenant Serializer
type PatchedTenantRequest struct {
	SchemaName           *string `json:"schema_name,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Ready                *bool   `json:"ready,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedTenantRequest PatchedTenantRequest

// NewPatchedTenantRequest instantiates a new PatchedTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedTenantRequest() *PatchedTenantRequest {
	this := PatchedTenantRequest{}
	return &this
}

// NewPatchedTenantRequestWithDefaults instantiates a new PatchedTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedTenantRequestWithDefaults() *PatchedTenantRequest {
	this := PatchedTenantRequest{}
	return &this
}

// GetSchemaName returns the SchemaName field value if set, zero value otherwise.
func (o *PatchedTenantRequest) GetSchemaName() string {
	if o == nil || IsNil(o.SchemaName) {
		var ret string
		return ret
	}
	return *o.SchemaName
}

// GetSchemaNameOk returns a tuple with the SchemaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedTenantRequest) GetSchemaNameOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaName) {
		return nil, false
	}
	return o.SchemaName, true
}

// HasSchemaName returns a boolean if a field has been set.
func (o *PatchedTenantRequest) HasSchemaName() bool {
	if o != nil && !IsNil(o.SchemaName) {
		return true
	}

	return false
}

// SetSchemaName gets a reference to the given string and assigns it to the SchemaName field.
func (o *PatchedTenantRequest) SetSchemaName(v string) {
	o.SchemaName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedTenantRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedTenantRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedTenantRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedTenantRequest) SetName(v string) {
	o.Name = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *PatchedTenantRequest) GetReady() bool {
	if o == nil || IsNil(o.Ready) {
		var ret bool
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedTenantRequest) GetReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *PatchedTenantRequest) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given bool and assigns it to the Ready field.
func (o *PatchedTenantRequest) SetReady(v bool) {
	o.Ready = &v
}

func (o PatchedTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedTenantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SchemaName) {
		toSerialize["schema_name"] = o.SchemaName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedTenantRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedTenantRequest := _PatchedTenantRequest{}

	err = json.Unmarshal(data, &varPatchedTenantRequest)

	if err != nil {
		return err
	}

	*o = PatchedTenantRequest(varPatchedTenantRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schema_name")
		delete(additionalProperties, "name")
		delete(additionalProperties, "ready")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedTenantRequest struct {
	value *PatchedTenantRequest
	isSet bool
}

func (v NullablePatchedTenantRequest) Get() *PatchedTenantRequest {
	return v.value
}

func (v *NullablePatchedTenantRequest) Set(val *PatchedTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedTenantRequest(val *PatchedTenantRequest) *NullablePatchedTenantRequest {
	return &NullablePatchedTenantRequest{value: val, isSet: true}
}

func (v NullablePatchedTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
