/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ExpiringBaseGrantModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpiringBaseGrantModel{}

// ExpiringBaseGrantModel Serializer for BaseGrantModel and ExpiringBaseGrant
type ExpiringBaseGrantModel struct {
	Pk       int32          `json:"pk"`
	Provider OAuth2Provider `json:"provider"`
	User     User           `json:"user"`
	// Check if token is expired yet.
	IsExpired            bool         `json:"is_expired"`
	Expires              NullableTime `json:"expires,omitempty"`
	Scope                []string     `json:"scope"`
	AdditionalProperties map[string]interface{}
}

type _ExpiringBaseGrantModel ExpiringBaseGrantModel

// NewExpiringBaseGrantModel instantiates a new ExpiringBaseGrantModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpiringBaseGrantModel(pk int32, provider OAuth2Provider, user User, isExpired bool, scope []string) *ExpiringBaseGrantModel {
	this := ExpiringBaseGrantModel{}
	this.Pk = pk
	this.Provider = provider
	this.User = user
	this.IsExpired = isExpired
	this.Scope = scope
	return &this
}

// NewExpiringBaseGrantModelWithDefaults instantiates a new ExpiringBaseGrantModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpiringBaseGrantModelWithDefaults() *ExpiringBaseGrantModel {
	this := ExpiringBaseGrantModel{}
	return &this
}

// GetPk returns the Pk field value
func (o *ExpiringBaseGrantModel) GetPk() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pk
}

// GetPkOk returns a tuple with the Pk field value
// and a boolean to check if the value has been set.
func (o *ExpiringBaseGrantModel) GetPkOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pk, true
}

// SetPk sets field value
func (o *ExpiringBaseGrantModel) SetPk(v int32) {
	o.Pk = v
}

// GetProvider returns the Provider field value
func (o *ExpiringBaseGrantModel) GetProvider() OAuth2Provider {
	if o == nil {
		var ret OAuth2Provider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ExpiringBaseGrantModel) GetProviderOk() (*OAuth2Provider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ExpiringBaseGrantModel) SetProvider(v OAuth2Provider) {
	o.Provider = v
}

// GetUser returns the User field value
func (o *ExpiringBaseGrantModel) GetUser() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *ExpiringBaseGrantModel) GetUserOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *ExpiringBaseGrantModel) SetUser(v User) {
	o.User = v
}

// GetIsExpired returns the IsExpired field value
func (o *ExpiringBaseGrantModel) GetIsExpired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsExpired
}

// GetIsExpiredOk returns a tuple with the IsExpired field value
// and a boolean to check if the value has been set.
func (o *ExpiringBaseGrantModel) GetIsExpiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsExpired, true
}

// SetIsExpired sets field value
func (o *ExpiringBaseGrantModel) SetIsExpired(v bool) {
	o.IsExpired = v
}

// GetExpires returns the Expires field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpiringBaseGrantModel) GetExpires() time.Time {
	if o == nil || IsNil(o.Expires.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Expires.Get()
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpiringBaseGrantModel) GetExpiresOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expires.Get(), o.Expires.IsSet()
}

// HasExpires returns a boolean if a field has been set.
func (o *ExpiringBaseGrantModel) HasExpires() bool {
	if o != nil && o.Expires.IsSet() {
		return true
	}

	return false
}

// SetExpires gets a reference to the given NullableTime and assigns it to the Expires field.
func (o *ExpiringBaseGrantModel) SetExpires(v time.Time) {
	o.Expires.Set(&v)
}

// SetExpiresNil sets the value for Expires to be an explicit nil
func (o *ExpiringBaseGrantModel) SetExpiresNil() {
	o.Expires.Set(nil)
}

// UnsetExpires ensures that no value is present for Expires, not even an explicit nil
func (o *ExpiringBaseGrantModel) UnsetExpires() {
	o.Expires.Unset()
}

// GetScope returns the Scope field value
func (o *ExpiringBaseGrantModel) GetScope() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *ExpiringBaseGrantModel) GetScopeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope, true
}

// SetScope sets field value
func (o *ExpiringBaseGrantModel) SetScope(v []string) {
	o.Scope = v
}

func (o ExpiringBaseGrantModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpiringBaseGrantModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pk"] = o.Pk
	toSerialize["provider"] = o.Provider
	toSerialize["user"] = o.User
	toSerialize["is_expired"] = o.IsExpired
	if o.Expires.IsSet() {
		toSerialize["expires"] = o.Expires.Get()
	}
	toSerialize["scope"] = o.Scope

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExpiringBaseGrantModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pk",
		"provider",
		"user",
		"is_expired",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpiringBaseGrantModel := _ExpiringBaseGrantModel{}

	err = json.Unmarshal(data, &varExpiringBaseGrantModel)

	if err != nil {
		return err
	}

	*o = ExpiringBaseGrantModel(varExpiringBaseGrantModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pk")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "user")
		delete(additionalProperties, "is_expired")
		delete(additionalProperties, "expires")
		delete(additionalProperties, "scope")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExpiringBaseGrantModel struct {
	value *ExpiringBaseGrantModel
	isSet bool
}

func (v NullableExpiringBaseGrantModel) Get() *ExpiringBaseGrantModel {
	return v.value
}

func (v *NullableExpiringBaseGrantModel) Set(val *ExpiringBaseGrantModel) {
	v.value = val
	v.isSet = true
}

func (v NullableExpiringBaseGrantModel) IsSet() bool {
	return v.isSet
}

func (v *NullableExpiringBaseGrantModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpiringBaseGrantModel(val *ExpiringBaseGrantModel) *NullableExpiringBaseGrantModel {
	return &NullableExpiringBaseGrantModel{value: val, isSet: true}
}

func (v NullableExpiringBaseGrantModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpiringBaseGrantModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
