/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PatchedKubernetesServiceConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedKubernetesServiceConnectionRequest{}

// PatchedKubernetesServiceConnectionRequest KubernetesServiceConnection Serializer
type PatchedKubernetesServiceConnectionRequest struct {
	Name *string `json:"name,omitempty"`
	// If enabled, use the local connection. Required Docker socket/Kubernetes Integration
	Local *bool `json:"local,omitempty"`
	// Paste your kubeconfig here. authentik will automatically use the currently selected context.
	Kubeconfig map[string]interface{} `json:"kubeconfig,omitempty"`
	// Verify SSL Certificates of the Kubernetes API endpoint
	VerifySsl            *bool `json:"verify_ssl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedKubernetesServiceConnectionRequest PatchedKubernetesServiceConnectionRequest

// NewPatchedKubernetesServiceConnectionRequest instantiates a new PatchedKubernetesServiceConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedKubernetesServiceConnectionRequest() *PatchedKubernetesServiceConnectionRequest {
	this := PatchedKubernetesServiceConnectionRequest{}
	return &this
}

// NewPatchedKubernetesServiceConnectionRequestWithDefaults instantiates a new PatchedKubernetesServiceConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedKubernetesServiceConnectionRequestWithDefaults() *PatchedKubernetesServiceConnectionRequest {
	this := PatchedKubernetesServiceConnectionRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedKubernetesServiceConnectionRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedKubernetesServiceConnectionRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedKubernetesServiceConnectionRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedKubernetesServiceConnectionRequest) SetName(v string) {
	o.Name = &v
}

// GetLocal returns the Local field value if set, zero value otherwise.
func (o *PatchedKubernetesServiceConnectionRequest) GetLocal() bool {
	if o == nil || IsNil(o.Local) {
		var ret bool
		return ret
	}
	return *o.Local
}

// GetLocalOk returns a tuple with the Local field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedKubernetesServiceConnectionRequest) GetLocalOk() (*bool, bool) {
	if o == nil || IsNil(o.Local) {
		return nil, false
	}
	return o.Local, true
}

// HasLocal returns a boolean if a field has been set.
func (o *PatchedKubernetesServiceConnectionRequest) HasLocal() bool {
	if o != nil && !IsNil(o.Local) {
		return true
	}

	return false
}

// SetLocal gets a reference to the given bool and assigns it to the Local field.
func (o *PatchedKubernetesServiceConnectionRequest) SetLocal(v bool) {
	o.Local = &v
}

// GetKubeconfig returns the Kubeconfig field value if set, zero value otherwise.
func (o *PatchedKubernetesServiceConnectionRequest) GetKubeconfig() map[string]interface{} {
	if o == nil || IsNil(o.Kubeconfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.Kubeconfig
}

// GetKubeconfigOk returns a tuple with the Kubeconfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedKubernetesServiceConnectionRequest) GetKubeconfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Kubeconfig) {
		return map[string]interface{}{}, false
	}
	return o.Kubeconfig, true
}

// HasKubeconfig returns a boolean if a field has been set.
func (o *PatchedKubernetesServiceConnectionRequest) HasKubeconfig() bool {
	if o != nil && !IsNil(o.Kubeconfig) {
		return true
	}

	return false
}

// SetKubeconfig gets a reference to the given map[string]interface{} and assigns it to the Kubeconfig field.
func (o *PatchedKubernetesServiceConnectionRequest) SetKubeconfig(v map[string]interface{}) {
	o.Kubeconfig = v
}

// GetVerifySsl returns the VerifySsl field value if set, zero value otherwise.
func (o *PatchedKubernetesServiceConnectionRequest) GetVerifySsl() bool {
	if o == nil || IsNil(o.VerifySsl) {
		var ret bool
		return ret
	}
	return *o.VerifySsl
}

// GetVerifySslOk returns a tuple with the VerifySsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedKubernetesServiceConnectionRequest) GetVerifySslOk() (*bool, bool) {
	if o == nil || IsNil(o.VerifySsl) {
		return nil, false
	}
	return o.VerifySsl, true
}

// HasVerifySsl returns a boolean if a field has been set.
func (o *PatchedKubernetesServiceConnectionRequest) HasVerifySsl() bool {
	if o != nil && !IsNil(o.VerifySsl) {
		return true
	}

	return false
}

// SetVerifySsl gets a reference to the given bool and assigns it to the VerifySsl field.
func (o *PatchedKubernetesServiceConnectionRequest) SetVerifySsl(v bool) {
	o.VerifySsl = &v
}

func (o PatchedKubernetesServiceConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedKubernetesServiceConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Local) {
		toSerialize["local"] = o.Local
	}
	if !IsNil(o.Kubeconfig) {
		toSerialize["kubeconfig"] = o.Kubeconfig
	}
	if !IsNil(o.VerifySsl) {
		toSerialize["verify_ssl"] = o.VerifySsl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedKubernetesServiceConnectionRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedKubernetesServiceConnectionRequest := _PatchedKubernetesServiceConnectionRequest{}

	err = json.Unmarshal(data, &varPatchedKubernetesServiceConnectionRequest)

	if err != nil {
		return err
	}

	*o = PatchedKubernetesServiceConnectionRequest(varPatchedKubernetesServiceConnectionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "local")
		delete(additionalProperties, "kubeconfig")
		delete(additionalProperties, "verify_ssl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedKubernetesServiceConnectionRequest struct {
	value *PatchedKubernetesServiceConnectionRequest
	isSet bool
}

func (v NullablePatchedKubernetesServiceConnectionRequest) Get() *PatchedKubernetesServiceConnectionRequest {
	return v.value
}

func (v *NullablePatchedKubernetesServiceConnectionRequest) Set(val *PatchedKubernetesServiceConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedKubernetesServiceConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedKubernetesServiceConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedKubernetesServiceConnectionRequest(val *PatchedKubernetesServiceConnectionRequest) *NullablePatchedKubernetesServiceConnectionRequest {
	return &NullablePatchedKubernetesServiceConnectionRequest{value: val, isSet: true}
}

func (v NullablePatchedKubernetesServiceConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedKubernetesServiceConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
