/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// LangEnum the model 'LangEnum'
type LangEnum string

// List of LangEnum
const (
	LANGENUM_AF      LangEnum = "af"
	LANGENUM_AR      LangEnum = "ar"
	LANGENUM_AR_DZ   LangEnum = "ar-dz"
	LANGENUM_AST     LangEnum = "ast"
	LANGENUM_AZ      LangEnum = "az"
	LANGENUM_BE      LangEnum = "be"
	LANGENUM_BG      LangEnum = "bg"
	LANGENUM_BN      LangEnum = "bn"
	LANGENUM_BR      LangEnum = "br"
	LANGENUM_BS      LangEnum = "bs"
	LANGENUM_CA      LangEnum = "ca"
	LANGENUM_CKB     LangEnum = "ckb"
	LANGENUM_CS      LangEnum = "cs"
	LANGENUM_CY      LangEnum = "cy"
	LANGENUM_DA      LangEnum = "da"
	LANGENUM_DE      LangEnum = "de"
	LANGENUM_DSB     LangEnum = "dsb"
	LANGENUM_EL      LangEnum = "el"
	LANGENUM_EN      LangEnum = "en"
	LANGENUM_EN_AU   LangEnum = "en-au"
	LANGENUM_EN_GB   LangEnum = "en-gb"
	LANGENUM_EO      LangEnum = "eo"
	LANGENUM_ES      LangEnum = "es"
	LANGENUM_ES_AR   LangEnum = "es-ar"
	LANGENUM_ES_CO   LangEnum = "es-co"
	LANGENUM_ES_MX   LangEnum = "es-mx"
	LANGENUM_ES_NI   LangEnum = "es-ni"
	LANGENUM_ES_VE   LangEnum = "es-ve"
	LANGENUM_ET      LangEnum = "et"
	LANGENUM_EU      LangEnum = "eu"
	LANGENUM_FA      LangEnum = "fa"
	LANGENUM_FI      LangEnum = "fi"
	LANGENUM_FR      LangEnum = "fr"
	LANGENUM_FY      LangEnum = "fy"
	LANGENUM_GA      LangEnum = "ga"
	LANGENUM_GD      LangEnum = "gd"
	LANGENUM_GL      LangEnum = "gl"
	LANGENUM_HE      LangEnum = "he"
	LANGENUM_HI      LangEnum = "hi"
	LANGENUM_HR      LangEnum = "hr"
	LANGENUM_HSB     LangEnum = "hsb"
	LANGENUM_HU      LangEnum = "hu"
	LANGENUM_HY      LangEnum = "hy"
	LANGENUM_IA      LangEnum = "ia"
	LANGENUM_ID      LangEnum = "id"
	LANGENUM_IG      LangEnum = "ig"
	LANGENUM_IO      LangEnum = "io"
	LANGENUM_IS      LangEnum = "is"
	LANGENUM_IT      LangEnum = "it"
	LANGENUM_JA      LangEnum = "ja"
	LANGENUM_KA      LangEnum = "ka"
	LANGENUM_KAB     LangEnum = "kab"
	LANGENUM_KK      LangEnum = "kk"
	LANGENUM_KM      LangEnum = "km"
	LANGENUM_KN      LangEnum = "kn"
	LANGENUM_KO      LangEnum = "ko"
	LANGENUM_KY      LangEnum = "ky"
	LANGENUM_LB      LangEnum = "lb"
	LANGENUM_LT      LangEnum = "lt"
	LANGENUM_LV      LangEnum = "lv"
	LANGENUM_MK      LangEnum = "mk"
	LANGENUM_ML      LangEnum = "ml"
	LANGENUM_MN      LangEnum = "mn"
	LANGENUM_MR      LangEnum = "mr"
	LANGENUM_MS      LangEnum = "ms"
	LANGENUM_MY      LangEnum = "my"
	LANGENUM_NB      LangEnum = "nb"
	LANGENUM_NE      LangEnum = "ne"
	LANGENUM_NL      LangEnum = "nl"
	LANGENUM_NN      LangEnum = "nn"
	LANGENUM_OS      LangEnum = "os"
	LANGENUM_PA      LangEnum = "pa"
	LANGENUM_PL      LangEnum = "pl"
	LANGENUM_PT      LangEnum = "pt"
	LANGENUM_PT_BR   LangEnum = "pt-br"
	LANGENUM_RO      LangEnum = "ro"
	LANGENUM_RU      LangEnum = "ru"
	LANGENUM_SK      LangEnum = "sk"
	LANGENUM_SL      LangEnum = "sl"
	LANGENUM_SQ      LangEnum = "sq"
	LANGENUM_SR      LangEnum = "sr"
	LANGENUM_SR_LATN LangEnum = "sr-latn"
	LANGENUM_SV      LangEnum = "sv"
	LANGENUM_SW      LangEnum = "sw"
	LANGENUM_TA      LangEnum = "ta"
	LANGENUM_TE      LangEnum = "te"
	LANGENUM_TG      LangEnum = "tg"
	LANGENUM_TH      LangEnum = "th"
	LANGENUM_TK      LangEnum = "tk"
	LANGENUM_TR      LangEnum = "tr"
	LANGENUM_TT      LangEnum = "tt"
	LANGENUM_UDM     LangEnum = "udm"
	LANGENUM_UG      LangEnum = "ug"
	LANGENUM_UK      LangEnum = "uk"
	LANGENUM_UR      LangEnum = "ur"
	LANGENUM_UZ      LangEnum = "uz"
	LANGENUM_VI      LangEnum = "vi"
	LANGENUM_ZH_HANS LangEnum = "zh-hans"
	LANGENUM_ZH_HANT LangEnum = "zh-hant"
)

// All allowed values of LangEnum enum
var AllowedLangEnumEnumValues = []LangEnum{
	"af",
	"ar",
	"ar-dz",
	"ast",
	"az",
	"be",
	"bg",
	"bn",
	"br",
	"bs",
	"ca",
	"ckb",
	"cs",
	"cy",
	"da",
	"de",
	"dsb",
	"el",
	"en",
	"en-au",
	"en-gb",
	"eo",
	"es",
	"es-ar",
	"es-co",
	"es-mx",
	"es-ni",
	"es-ve",
	"et",
	"eu",
	"fa",
	"fi",
	"fr",
	"fy",
	"ga",
	"gd",
	"gl",
	"he",
	"hi",
	"hr",
	"hsb",
	"hu",
	"hy",
	"ia",
	"id",
	"ig",
	"io",
	"is",
	"it",
	"ja",
	"ka",
	"kab",
	"kk",
	"km",
	"kn",
	"ko",
	"ky",
	"lb",
	"lt",
	"lv",
	"mk",
	"ml",
	"mn",
	"mr",
	"ms",
	"my",
	"nb",
	"ne",
	"nl",
	"nn",
	"os",
	"pa",
	"pl",
	"pt",
	"pt-br",
	"ro",
	"ru",
	"sk",
	"sl",
	"sq",
	"sr",
	"sr-latn",
	"sv",
	"sw",
	"ta",
	"te",
	"tg",
	"th",
	"tk",
	"tr",
	"tt",
	"udm",
	"ug",
	"uk",
	"ur",
	"uz",
	"vi",
	"zh-hans",
	"zh-hant",
}

func (v *LangEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LangEnum(value)
	for _, existing := range AllowedLangEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LangEnum", value)
}

// NewLangEnumFromValue returns a pointer to a valid LangEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLangEnumFromValue(v string) (*LangEnum, error) {
	ev := LangEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LangEnum: valid values are %v", v, AllowedLangEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LangEnum) IsValid() bool {
	for _, existing := range AllowedLangEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LangEnum value
func (v LangEnum) Ptr() *LangEnum {
	return &v
}

type NullableLangEnum struct {
	value *LangEnum
	isSet bool
}

func (v NullableLangEnum) Get() *LangEnum {
	return v.value
}

func (v *NullableLangEnum) Set(val *LangEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLangEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLangEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLangEnum(val *LangEnum) *NullableLangEnum {
	return &NullableLangEnum{value: val, isSet: true}
}

func (v NullableLangEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLangEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
