/*
authentik

Making authentication simple.

API version: 2026.5.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedSCIMSourceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedSCIMSourceList{}

// PaginatedSCIMSourceList struct for PaginatedSCIMSourceList
type PaginatedSCIMSourceList struct {
	Pagination           Pagination             `json:"pagination"`
	Results              []SCIMSource           `json:"results"`
	Autocomplete         map[string]interface{} `json:"autocomplete"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedSCIMSourceList PaginatedSCIMSourceList

// NewPaginatedSCIMSourceList instantiates a new PaginatedSCIMSourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedSCIMSourceList(pagination Pagination, results []SCIMSource, autocomplete map[string]interface{}) *PaginatedSCIMSourceList {
	this := PaginatedSCIMSourceList{}
	this.Pagination = pagination
	this.Results = results
	this.Autocomplete = autocomplete
	return &this
}

// NewPaginatedSCIMSourceListWithDefaults instantiates a new PaginatedSCIMSourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedSCIMSourceListWithDefaults() *PaginatedSCIMSourceList {
	this := PaginatedSCIMSourceList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedSCIMSourceList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedSCIMSourceList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedSCIMSourceList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedSCIMSourceList) GetResults() []SCIMSource {
	if o == nil {
		var ret []SCIMSource
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedSCIMSourceList) GetResultsOk() ([]SCIMSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedSCIMSourceList) SetResults(v []SCIMSource) {
	o.Results = v
}

// GetAutocomplete returns the Autocomplete field value
func (o *PaginatedSCIMSourceList) GetAutocomplete() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Autocomplete
}

// GetAutocompleteOk returns a tuple with the Autocomplete field value
// and a boolean to check if the value has been set.
func (o *PaginatedSCIMSourceList) GetAutocompleteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Autocomplete, true
}

// SetAutocomplete sets field value
func (o *PaginatedSCIMSourceList) SetAutocomplete(v map[string]interface{}) {
	o.Autocomplete = v
}

func (o PaginatedSCIMSourceList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedSCIMSourceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	toSerialize["autocomplete"] = o.Autocomplete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedSCIMSourceList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"results",
		"autocomplete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedSCIMSourceList := _PaginatedSCIMSourceList{}

	err = json.Unmarshal(data, &varPaginatedSCIMSourceList)

	if err != nil {
		return err
	}

	*o = PaginatedSCIMSourceList(varPaginatedSCIMSourceList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pagination")
		delete(additionalProperties, "results")
		delete(additionalProperties, "autocomplete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedSCIMSourceList struct {
	value *PaginatedSCIMSourceList
	isSet bool
}

func (v NullablePaginatedSCIMSourceList) Get() *PaginatedSCIMSourceList {
	return v.value
}

func (v *NullablePaginatedSCIMSourceList) Set(val *PaginatedSCIMSourceList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedSCIMSourceList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedSCIMSourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedSCIMSourceList(val *PaginatedSCIMSourceList) *NullablePaginatedSCIMSourceList {
	return &NullablePaginatedSCIMSourceList{value: val, isSet: true}
}

func (v NullablePaginatedSCIMSourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedSCIMSourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
