# Generated by Django 3.0.5 on 2020-05-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("passbook_core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthInlet",
            fields=[
                (
                    "inlet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="passbook_core.Inlet",
                    ),
                ),
                ("inlet_type", models.CharField(max_length=255)),
                (
                    "request_token_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Request Token URL"
                    ),
                ),
                (
                    "authorization_url",
                    models.CharField(max_length=255, verbose_name="Authorization URL"),
                ),
                (
                    "access_token_url",
                    models.CharField(max_length=255, verbose_name="Access Token URL"),
                ),
                (
                    "profile_url",
                    models.CharField(max_length=255, verbose_name="Profile URL"),
                ),
                ("consumer_key", models.TextField()),
                ("consumer_secret", models.TextField()),
            ],
            options={
                "verbose_name": "Generic OAuth Inlet",
                "verbose_name_plural": "Generic OAuth Inlets",
            },
            bases=("passbook_core.inlet",),
        ),
        migrations.CreateModel(
            name="UserOAuthInletConnection",
            fields=[
                (
                    "userinletconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="passbook_core.UserInletConnection",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("access_token", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "User OAuth Inlet Connection",
                "verbose_name_plural": "User OAuth Inlet Connections",
            },
            bases=("passbook_core.userinletconnection",),
        ),
    ]
