# This file is used for development and debugging, and should not be used for production instances

version: '3.5'

services:
  flower:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.5.4}
    restart: unless-stopped
    command: worker-status
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    env_file:
      - .env
    ports:
      - "9001:9000"
    depends_on:
      - postgresql
      - redis
  server:
    environment:
      AUTHENTIK_REMOTE_DEBUG: "true"
      PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT: "true"
    ports:
      - 6800:6800
  worker:
    environment:
      CELERY_RDB_HOST: "0.0.0.0"
      CELERY_RDBSIG: "1"
      AUTHENTIK_REMOTE_DEBUG: "true"
      PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT: "true"
    ports:
      - 6900:6900
