FROM python:3.6

COPY ./passbook/ /app/passbook
COPY ./client-packages/ /app/client-packages
COPY ./requirements.txt /app/
COPY ./requirements-dev.txt /app/

WORKDIR /app/

RUN apt-get update && apt-get install libssl-dev libffi-dev libpq-dev -y && \
     pip install -U -r requirements-dev.txt && \
     rm -rf /app/*
