services:
    authentik_proxy:
        build:
            context: .
            dockerfile: ./proxy.Dockerfile
        environment:
            AUTHENTIK_HOST: http://192.168.2.111:9000
            AUTHENTIK_INSECURE: "true"
            AUTHENTIK_TOKEN: 0cAydq2aAzI6kffeG9yoQ744x4e5YQG47d8dX5yPqfMK295ENWnDvDwZJogs
            AUTHENTIK_LOG_LEVEL: trace
            AUTHENTIK_HOST_BROWSER: http://192.168.2.111:9000
        networks:
            - outpost-test

    whoami:
        image: traefik/whoami:latest
        networks:
            - outpost-test
        labels:
            - "traefik.enable=false"

    # Uncomment ONE of the nginx services below to test standalone or embedded outpost
    # Both use port 80, so only run one at a time

    # nginx-standalone:
    #     image: nginx:latest
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./nginx-standalone.conf:/etc/nginx/conf.d/default.conf:ro
    #     networks:
    #         - outpost-test
    #     depends_on:
    #         - whoami
    #         - authentik_proxy
    #     extra_hosts:
    #         - "host.docker.internal:host-gateway"

    nginx-embedded:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx-embedded.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - outpost-test
        depends_on:
            - whoami
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    outpost-test:
