services:
    proxy-test:
      build:
        context: .
        dockerfile: proxy.Dockerfile
      restart: unless-stopped
      environment:
        - AUTHENTIK_HOST=http://192.168.2.50:9000
        - AUTHENTIK_TOKEN=1T7PLASNQu2O1JKuk7kYN2SAlA8UPo5SFaGoVtE4RQESFHbfsqnWqmwCFo5m
        - AUTHENTIK_INSECURE=true
      networks:
        - session-test

    traefik:
      image: traefik:v3.4.4
      restart: unless-stopped
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik.yml:/etc/traefik/traefik.yml:ro
      networks:
          - session-test

    whoami-01:
      image: traefik/whoami:latest
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami-01.rule=Host(`standalone.localhost`)"
        - "traefik.http.routers.whoami-01.entrypoints=web"
        - "traefik.http.routers.whoami-01.middlewares=authentik-standalone"
        - "traefik.http.middlewares.authentik-standalone.forwardauth.address=http://proxy-test:9000/outpost.goauthentik.io/auth/traefik"
        - "traefik.http.middlewares.authentik-standalone.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authentik-standalone.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid"
      networks:
        - session-test

    whoami-02:
      image: traefik/whoami:latest
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami-02.rule=Host(`embedded.localhost`)"
        - "traefik.http.routers.whoami-02.entrypoints=web"
        - "traefik.http.routers.whoami-02.middlewares=authentik-embedded"
        - "traefik.http.middlewares.authentik-embedded.forwardauth.address=http://192.168.2.50:9000/outpost.goauthentik.io/auth/traefik"
        - "traefik.http.middlewares.authentik-embedded.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authentik-embedded.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid"
      networks:
        - session-test

networks:
  session-test: