services:
  whoami:
    image: traefik/whoami:latest
    networks:
      - outpost-test
    labels:
      - "traefik.enable=false"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-outpost-test.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - outpost-test
    depends_on:
      - whoami
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  outpost-test:
    driver: bridge