# Generated by Django 5.2.17 on 2026-09-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_proxy", "0017_proxyprovider_cookie_secret_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proxyprovider",
            name="_cookie_secret",
        ),
    ]
