# Generated by Django 4.2.7 on 2023-11-06 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_events", "0002_alter_notificationtransport_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="tenant",
            new_name="brand",
        ),
    ]
