# Generated by Django 5.1.9 on 2025-06-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_events", "0009_remove_notificationtransport_webhook_mapping_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemTask",
        ),
    ]
