# Generated by Django 5.2.12 on 2026-03-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto", "0006_certificatekeypair_cert_expiry_and_more"),
        ("authentik_events", "0016_alter_event_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtransport",
            name="webhook_ca",
            field=models.ForeignKey(
                default=None,
                help_text="When set, the selected ceritifcate is used to validate the certificate of the webhook server.",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="authentik_crypto.certificatekeypair",
            ),
        ),
    ]
