# Generated by Django 5.2.17 on 2026-08-30 21:31

import django.db.models.deletion
from django.db import migrations, models

import authentik.lib.models


def migrate_webhook_url(apps, schema_editor):
    """Move each transport's webhook_url into a Secret object"""
    db_alias = schema_editor.connection.alias
    NotificationTransport = apps.get_model("authentik_events", "NotificationTransport")
    Secret = apps.get_model("authentik_secrets", "Secret")
    names = set(Secret.objects.using(db_alias).values_list("name", flat=True))
    for transport in NotificationTransport.objects.using(db_alias).exclude(_webhook_url=""):
        base = f"{transport.name} webhook URL"
        name, idx = base, 2
        while name in names:
            name = f"{base} ({idx})"
            idx += 1
        names.add(name)
        transport.secret = Secret.objects.using(db_alias).create(
            name=name,
            value=transport._webhook_url,
            type="multiline" if "\n" in transport._webhook_url else "text",
        )
        transport.save(update_fields=["secret"])


def rollback_webhook_url(apps, schema_editor):
    """Copy secret values back into the legacy column, so a downgrade keeps values
    set or rotated after the upgrade"""
    db_alias = schema_editor.connection.alias
    NotificationTransport = apps.get_model("authentik_events", "NotificationTransport")
    for transport in NotificationTransport.objects.using(db_alias).select_related("secret"):
        transport._webhook_url = transport.secret.value if transport.secret else ""
        transport.save(update_fields=["_webhook_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_events", "0020_alter_event_action"),
        ("authentik_secrets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtransport",
            name="webhook_url",
            field=models.TextField(
                blank=True,
                db_column="webhook_url",
                validators=[authentik.lib.models.DomainlessURLValidator()],
            ),
        ),
        migrations.RenameField(
            model_name="notificationtransport",
            old_name="webhook_url",
            new_name="_webhook_url",
        ),
        migrations.AddField(
            model_name="notificationtransport",
            name="secret",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_transports",
                to="authentik_secrets.secret",
                verbose_name="Webhook URL",
            ),
        ),
        migrations.RunPython(migrate_webhook_url, rollback_webhook_url),
    ]
