# Generated by Django 3.0.5 on 2020-05-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_stages_prompt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={"verbose_name": "Prompt", "verbose_name_plural": "Prompts"},
        ),
        migrations.AlterField(
            model_name="prompt",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("e-mail", "Email"),
                    ("password", "Password"),
                    ("number", "Number"),
                    ("hidden", "Hidden"),
                ],
                max_length=100,
            ),
        ),
    ]
