# Generated by Django 4.1.7 on 2023-03-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_core", "0024_source_icon"),
        ("authentik_providers_scim", "0002_scimuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCIMGroup",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="authentik_core.group"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_scim.scimprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {("id", "group", "provider")},
            },
        ),
    ]
