# Generated by Django 5.1.12 on 2025-09-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_scim", "0013_scimprovidergroup_attributes_and_more"),
        ("authentik_sources_oauth", "0011_useroauthsourceconnection_expires"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scimprovider",
            name="auth_oauth",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="authentik_sources_oauth.oauthsource",
            ),
        ),
        migrations.AddField(
            model_name="scimprovider",
            name="auth_oauth_grant_type",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="scimprovider",
            name="auth_oauth_user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
