# Generated by Django 5.2.17 on 2026-09-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_scim", "0022_scimprovider_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scimprovider",
            name="_token",
        ),
    ]
