# Generated by Django 5.2.15 on 2026-07-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_pam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grantrequest",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grant_requests",
                to="authentik_pam.persona",
            ),
        ),
    ]
