# Generated by Django 5.2.15 on 2026-07-10 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_pam", "0003_persona_actors"),
        ("authentik_policies", "0012_policybinding_expires_policybinding_expiring_and_more"),
        ("authentik_providers_oauth2", "0033_alter_oauth2provider_grant_types"),
        ("authentik_sources_oauth", "0014_migrate_azuread_to_entraid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="actor_providers",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="actor_sources",
        ),
        migrations.CreateModel(
            name="PersonaTemplate",
            fields=[
                (
                    "policybindingmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "actor_providers",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="authentik_providers_oauth2.oauth2provider"
                    ),
                ),
                (
                    "actor_sources",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="authentik_sources_oauth.oauthsource"
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Template",
                "verbose_name_plural": "Persona Templates",
            },
            bases=("authentik_policies.policybindingmodel", models.Model),
        ),
        migrations.AddField(
            model_name="persona",
            name="template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personas",
                to="authentik_pam.personatemplate",
            ),
        ),
    ]
