# Generated by Django 3.0.6 on 2020-05-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("passbook_policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpressionPolicy",
            fields=[
                (
                    "policy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="passbook_policies.Policy",
                    ),
                ),
                ("expression", models.TextField()),
            ],
            options={
                "verbose_name": "Expression Policy",
                "verbose_name_plural": "Expression Policies",
            },
            bases=("passbook_policies.policy",),
        ),
    ]
