# Generated by Django 5.0.7 on 2024-07-25 14:59
from django.apps.registry import Apps

from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from django.db import migrations


def migrate_search_group(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    from guardian.shortcuts import assign_perm
    from authentik.core.models import User

    LDAPProvider = apps.get_model("authentik_providers_ldap", "ldapprovider")

    db_alias = schema_editor.connection.alias
    for provider in LDAPProvider.objects.using(db_alias).all():
        for user_pk in (
            provider.search_group.users.using(db_alias).all().values_list("pk", flat=True)
        ):
            # We need the correct user model instance to assign the permission
            assign_perm("search_full_directory", User.objects.get(pk=user_pk), provider)


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_ldap", "0003_ldapprovider_mfa_support_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ldapprovider",
            options={
                "permissions": [("search_full_directory", "Search full LDAP directory")],
                "verbose_name": "LDAP Provider",
                "verbose_name_plural": "LDAP Providers",
            },
        ),
        migrations.RunPython(migrate_search_group),
        migrations.RemoveField(
            model_name="ldapprovider",
            name="search_group",
        ),
    ]
