# Generated by Django 5.2.15 on 2026-07-19 19:38

import authentik.lib.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_flows", "0031_alter_flow_layout"),
        ("authentik_policies", "0012_alter_policybinding_managers_policybinding_expires_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantRequest",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("expires", models.DateTimeField(default=None, null=True)),
                ("expiring", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("requester_data", models.JSONField(default=dict)),
                ("fulfiller_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("created", "Created"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked"),
                        ],
                        default="created",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="grant_requests_fulfilled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="grant_requests_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant Request",
                "verbose_name_plural": "Grant Requests",
                "permissions": [
                    ("request_grantrequest", "Can create a grant request"),
                    ("fulfill_grantrequest", "Can fulfill (approve/deny) a grant request"),
                    ("revoke_grantrequest", "Can revoke a grant request"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GrantRequestTarget",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "binding",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_policies.policybinding",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_requests.grantrequest",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant Request Target",
                "verbose_name_plural": "Grant Request Targets",
            },
            bases=(authentik.lib.models.InternallyManagedMixin, models.Model),
        ),
        migrations.AddField(
            model_name="grantrequest",
            name="targets",
            field=models.ManyToManyField(
                through="authentik_requests.GrantRequestTarget",
                to="authentik_policies.policybindingmodel",
            ),
        ),
        migrations.CreateModel(
            name="RequestRule",
            fields=[
                (
                    "policybindingmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("min_reviewers", models.PositiveSmallIntegerField(default=1)),
                ("min_reviewers_is_per_group", models.BooleanField(default=False)),
                (
                    "notification_mode",
                    models.TextField(
                        choices=[
                            ("all", "Everyone who can approve"),
                            ("direct", "Only individually-selected reviewers"),
                            (
                                "random_min_reviewers",
                                "A random subset of size min_reviewers, from everyone who can approve",
                            ),
                        ],
                        default="all",
                    ),
                ),
                (
                    "notification_transports",
                    models.ManyToManyField(blank=True, to="authentik_events.notificationtransport"),
                ),
                (
                    "request_flow",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="authentik_flows.flow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Rule",
                "verbose_name_plural": "Request Rules",
            },
            bases=("authentik_policies.policybindingmodel", models.Model),
        ),
        migrations.CreateModel(
            name="RequestRuleBinding",
            fields=[
                (
                    "policybindingmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_requests.requestrule",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_rule_bindings",
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Rule Binding",
                "verbose_name_plural": "Request Rule Bindings",
            },
            bases=("authentik_policies.policybindingmodel", models.Model),
        ),
        migrations.AddField(
            model_name="requestrule",
            name="targets",
            field=models.ManyToManyField(
                related_name="request_rules",
                through="authentik_requests.RequestRuleBinding",
                through_fields=("rule", "target"),
                to="authentik_policies.policybindingmodel",
            ),
        ),
        migrations.CreateModel(
            name="RequestRuleChildBinding",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_requests.requestrulebinding",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Rule Child Binding",
                "verbose_name_plural": "Request Rule Child Bindings",
                "unique_together": {("binding", "target")},
            },
        ),
        migrations.AddField(
            model_name="requestrulebinding",
            name="related",
            field=models.ManyToManyField(
                related_name="request_rule_child_bindings",
                through="authentik_requests.RequestRuleChildBinding",
                to="authentik_policies.policybindingmodel",
            ),
        ),
        migrations.CreateModel(
            name="GrantRequestApproval",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("created", "Created"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked"),
                        ]
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="authentik_requests.grantrequest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant Request Approval",
                "verbose_name_plural": "Grant Request Approvals",
                "unique_together": {("request", "reviewer")},
            },
        ),
    ]
