# Generated by Django 5.2.17 on 2026-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_password", "0011_passworddevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="passworddevice",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passworddevice",
            name="locked_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="passwordstage",
            name="failed_attempts_before_lockout",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many consecutive failed attempts lock the user's password until an administrator unlocks it. Set to 0 to never lock.",
            ),
        ),
        migrations.AddField(
            model_name="passwordstage",
            name="last_attempt_warning_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Warning shown when the user has one password attempt remaining. Leave blank to show no warning.",
            ),
        ),
        migrations.AddField(
            model_name="passwordstage",
            name="lockout_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Message shown when the user's password has been locked. Leave blank to show no message.",
            ),
        ),
        migrations.AlterField(
            model_name="passwordstage",
            name="failed_attempts_before_cancel",
            field=models.IntegerField(
                default=5,
                help_text="How many attempts a user has before the flow is canceled. This only cancels the flow, it does not lock the user's password.",
            ),
        ),
    ]
