# Generated by Django 5.2.15 on 2026-07-23 15:39

from itertools import batched

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

DEFAULT_PASSWORD_STAGE_NAME = "default-authentication-password"
DEFAULT_PASSWORD_STAGE_BACKENDS = [
    "authentik.core.auth.InbuiltBackend",
    "authentik.sources.kerberos.auth.KerberosBackend",
    "authentik.sources.ldap.auth.LDAPBackend",
    "authentik.core.auth.TokenBackend",
]


def migrate_passwords_to_devices(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    User = apps.get_model("authentik_core", "User")
    PasswordStage = apps.get_model("authentik_stages_password", "PasswordStage")
    PasswordDevice = apps.get_model("authentik_stages_password", "PasswordDevice")
    db_alias = schema_editor.connection.alias

    stage, _ = PasswordStage.objects.using(db_alias).get_or_create(
        name=DEFAULT_PASSWORD_STAGE_NAME,
        defaults={"backends": DEFAULT_PASSWORD_STAGE_BACKENDS},
    )
    users = User.objects.using(db_alias).iterator(chunk_size=1000)
    for user_batch in batched(users, 1000):
        PasswordDevice.objects.using(db_alias).bulk_create(
            [
                PasswordDevice(
                    name="Password",
                    user_id=user.pk,
                    stage_id=stage.pk,
                    password=user.password or "!",
                    password_change_date=user.password_change_date,
                )
                for user in user_batch
            ],
            batch_size=1000,
        )


def migrate_devices_to_passwords(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    User = apps.get_model("authentik_core", "User")
    PasswordDevice = apps.get_model("authentik_stages_password", "PasswordDevice")
    db_alias = schema_editor.connection.alias

    devices = PasswordDevice.objects.using(db_alias).iterator(chunk_size=1000)
    for device_batch in batched(devices, 1000):
        User.objects.using(db_alias).bulk_update(
            [
                User(
                    pk=device.user_id,
                    password=device.password,
                    password_change_date=device.password_change_date,
                )
                for device in device_batch
            ],
            fields=["password", "password_change_date"],
            batch_size=1000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_password", "0011_passworddevice"),
        (
            "authentik_core",
            "0062_alter_user_password_alter_user_password_change_date",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_passwords_to_devices, migrate_devices_to_passwords),
    ]
