# Generated by Django 5.2.8 on 2025-11-21 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_endpoints", "0002_alter_device_name"),
        ("authentik_endpoints_connectors_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationToken",
            fields=[
                ("expires", models.DateTimeField(default=None, null=True)),
                ("expiring", models.BooleanField(default=True)),
                (
                    "identifier",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                (
                    "secret",
                    models.TextField(
                        default='u&<Yso!A*|)%aH{rN+=Z/TJvML{"Qg5eN+:xNgmM3U:O~~6{|Hv9bs9TF_*ycQ`HM{&wzHR6w]Z1C,.1qXKMK{|j9;!(\\cKBQD&=BZB%ECGituvrMdixKt)d!kMsb1QT',
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="devicetoken",
            options={"verbose_name": "Device Token", "verbose_name_plural": "Device Tokens"},
        ),
        migrations.RenameField(
            model_name="agentconnector",
            old_name="authentication_flow",
            new_name="authorization_flow",
        ),
        migrations.AddField(
            model_name="agentconnector",
            name="domain_name",
            field=models.TextField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(fields=["key"], name="authentik_e_key_504bbc_idx"),
        ),
        migrations.AddField(
            model_name="authenticationtoken",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentik_endpoints.device"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationtoken",
            index=models.Index(fields=["expires"], name="authentik_e_expires_1755bb_idx"),
        ),
        migrations.AddIndex(
            model_name="authenticationtoken",
            index=models.Index(fields=["expiring"], name="authentik_e_expirin_9d6355_idx"),
        ),
        migrations.AddIndex(
            model_name="authenticationtoken",
            index=models.Index(
                fields=["expiring", "expires"], name="authentik_e_expirin_6bba89_idx"
            ),
        ),
    ]
