# Generated by Django 5.2.11 on 2026-02-20 17:48

import authentik.lib.utils.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_endpoints_connectors_agent",
            "0004_agentconnector_challenge_idle_timeout_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconnector",
            name="ephemeral_device_expiry",
            field=models.TextField(
                default="hours=2", validators=[authentik.lib.utils.time.timedelta_string_validator]
            ),
        ),
    ]
