# Generated by Django 5.2.16 on 2026-08-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_endpoints_connectors_agent",
            "0007_agentconnectorjwtfederationprovider_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconnector",
            name="apple_psso_filevault_policy",
            field=models.TextField(
                choices=[
                    ("none", "None (silent background token only)"),
                    ("attempt", "Attempt authentication (enforced only when online)"),
                    ("require", "Require authentication"),
                ],
                default="none",
            ),
        ),
        migrations.AddField(
            model_name="agentconnector",
            name="apple_psso_login_frequency",
            field=models.PositiveIntegerField(default=64800),
        ),
        migrations.AddField(
            model_name="agentconnector",
            name="apple_psso_login_policy",
            field=models.TextField(
                choices=[
                    ("none", "None (silent background token only)"),
                    ("attempt", "Attempt authentication (enforced only when online)"),
                    ("require", "Require authentication"),
                ],
                default="none",
            ),
        ),
        migrations.AddField(
            model_name="agentconnector",
            name="apple_psso_unlock_policy",
            field=models.TextField(
                choices=[
                    ("none", "None (silent background token only)"),
                    ("attempt", "Attempt authentication (enforced only when online)"),
                    ("require", "Require authentication"),
                ],
                default="none",
            ),
        ),
    ]
