# Generated by Django 5.2.17 on 2026-09-23 21:07

import django.db.models.deletion
from django.db import migrations, models

import authentik.lib.generators
from authentik.crypto.secrets.migrations._credential_values import (
    migrate_credentials,
    restore_credentials,
)
from authentik.crypto.secrets.migrations._permissions import preserve_role_permissions

FIELDS = [("_shared_secret", "shared_secret_ref", "text", "shared secret")]


def forwards(apps, schema_editor):
    migrate_credentials(
        apps,
        schema_editor,
        "authentik_providers_radius",
        "RadiusProvider",
        FIELDS,
        include_empty=True,
    )
    preserve_role_permissions(
        apps, schema_editor, [("authentik_providers_radius", "radiusprovider")]
    )


def backwards(apps, schema_editor):
    restore_credentials(apps, schema_editor, "authentik_providers_radius", "RadiusProvider", FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0005_delete_userobjectpermission_and_groupobjectpermission"),
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_providers_radius", "0005_radiusprovider_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiusprovider",
            name="shared_secret",
            field=models.TextField(
                db_column="shared_secret",
                default=authentik.lib.generators.generate_id,
                help_text="Shared secret between clients and server to hash packets.",
            ),
        ),
        migrations.RenameField(
            model_name="radiusprovider",
            old_name="shared_secret",
            new_name="_shared_secret",
        ),
        migrations.AddField(
            model_name="radiusprovider",
            name="shared_secret_ref",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Shared secret between clients and server to hash packets.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radius_providers",
                to="authentik_crypto_secrets.secret",
                verbose_name="Shared Secret",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", "SET CONSTRAINTS ALL IMMEDIATE"),
    ]
