# Generated by Django 2.1.7 on 2019-03-08 10:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0017_propertymapping'),
        ('passbook_saml_idp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLPropertyMapping',
            fields=[
                ('propertymapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='passbook_core.PropertyMapping')),
                ('saml_name', models.TextField()),
                ('friendly_name', models.TextField(blank=True, default=None, null=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'verbose_name': 'SAML Property Mapping',
                'verbose_name_plural': 'SAML Property Mappings',
            },
            bases=('passbook_core.propertymapping',),
        ),
    ]
