# Generated by Django 5.2.7 on 2025-10-20 14:01

import authentik.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_endpoints", "0001_initial"),
        ("authentik_flows", "0028_flowtoken_revoke_on_execution"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentToken",
            fields=[
                ("expires", models.DateTimeField(default=None, null=True)),
                ("expiring", models.BooleanField(default=True)),
                (
                    "token_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.TextField(default=authentik.core.models.default_token_key)),
            ],
            options={
                "verbose_name": "Enrollment Token",
                "verbose_name_plural": "Enrollment Tokens",
                "permissions": [("view_token_key", "View token's key")],
                "indexes": [
                    models.Index(fields=["expires"], name="authentik_e_expires_98b99c_idx"),
                    models.Index(fields=["expiring"], name="authentik_e_expirin_9a17f7_idx"),
                    models.Index(
                        fields=["expiring", "expires"], name="authentik_e_expirin_7ad82a_idx"
                    ),
                    models.Index(fields=["key"], name="authentik_e_key_8dafaf_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentConnector",
            fields=[
                (
                    "connector_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_endpoints.connector",
                    ),
                ),
                ("nss_uid_offset", models.PositiveIntegerField(default=1000)),
                ("nss_gid_offset", models.PositiveIntegerField(default=1000)),
                (
                    "authentication_flow",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="authentik_flows.flow",
                    ),
                ),
                (
                    "tokens",
                    models.ManyToManyField(
                        to="authentik_endpoints_connectors_agent.enrollmenttoken"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("authentik_endpoints.connector",),
        ),
    ]
