name: Bug report
description: Create a report to help us improve
labels: ["bug", "triage"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "The behavior that I expect to see is [...]"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
      placeholder: "Also note that [...]"
    validations:
      required: false
  - type: dropdown
    id: deployment-method
    attributes:
      label: Deployment Method
      description: "What deployment method are you using for authentik? Only Docker, Kubernetes and AWS CloudFormation are supported."
      options:
        - Docker
        - Kubernetes
        - AWS CloudFormation
        - Other (please specify)
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "What version of authentik are you using?"
      placeholder: "[e.g. 2025.10.1]"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell
    validations:
      required: false
