name: Feature request
description: Suggest an idea for a feature
labels: ["enhancement", "triage"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I'd like authentik to have [...]"
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives that you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I've tried this but [...]"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Also note that [...]"
    validations:
      required: false
