name: Question
description: Have a question?
title: ""
labels: []
projects:
assignees:
type:
body:
  - type: markdown
    attributes:
      value: |
        Rather than creating an issue, please ask and answer questions via [GitHub Discussions](https://github.com/goauthentik/authentik/discussions) or our [Discord](https://discord.com/invite/jg33eMhnj6).
