# Generated by Django 5.0.12 on 2025-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_brands", "0007_brand_default_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="branding_default_flow_background",
            field=models.TextField(default="/static/dist/assets/images/flow_background.jpg"),
        ),
    ]
