# Generated by Django 5.1.9 on 2025-05-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_brands", "0009_brand_branding_default_flow_background"),
        ("authentik_crypto", "0004_alter_certificatekeypair_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="client_certificates",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Certificates used for client authentication.",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="web_certificate",
            field=models.ForeignKey(
                default=None,
                help_text="Web Certificate used by the authentik Core webserver.",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
    ]
