# Generated by Django 5.2.15 on 2026-06-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_brands", "0013_brand_flow_user_selection"),
        ("authentik_flows", "0032_alter_flow_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="flow_account_switch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand_account_switch",
                to="authentik_flows.flow",
            ),
        ),
    ]
