# Generated by Django 3.1.1 on 2020-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_flows", "0012_auto_20200830_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage", name="name", field=models.TextField(unique=True),
        ),
    ]
