name: 'ci-prepare'
description: 'Prepares requirements and dependencies'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash -xe
        docker-compose -f scripts/ci.docker-compose.yml up -d
        sudo apt update
        sudo apt install -y libxmlsec1-dev pkg-config gettext
        sudo pip install -U wheel pipenv
        if [[ "$INSTALL" != "true" ]]; then
            pipenv install --dev
        fi
    - shell: pipenv run python {0}
      run: |
        """Utility script to generate a config for CI runs"""
        from yaml import safe_dump
        import string
        from random import SystemRandom


        def generate_id(length=40):
            """Generate a random client ID"""
            rand = SystemRandom()
            return "".join(rand.choice(string.ascii_letters + string.digits) for x in range(length))

        with open("local.env.yml", "w") as _config:
            safe_dump({
                "log_level": "debug",
                "secret_key": generate_id(),
            }, _config, default_flow_style=False)
