# Generated by Django 3.2.6 on 2021-09-01 12:11

from django.db import migrations, models

import authentik.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_invitation", "0004_invitation_single_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expiring",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="expires",
            field=models.DateTimeField(default=authentik.core.models.default_token_duration),
        ),
    ]
