/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AuthenticatorStaticStage Serializer
 * @export
 * @interface AuthenticatorStaticStageRequest
 */
export interface AuthenticatorStaticStageRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorStaticStageRequest
     */
    name: string;
    /**
     * Flow used by an authenticated user to configure this Stage. If empty, user will not be able to configure this stage.
     * @type {string}
     * @memberof AuthenticatorStaticStageRequest
     */
    configureFlow?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorStaticStageRequest
     */
    friendlyName?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthenticatorStaticStageRequest
     */
    tokenCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AuthenticatorStaticStageRequest
     */
    tokenLength?: number;
}

/**
 * Check if a given object implements the AuthenticatorStaticStageRequest interface.
 */
export function instanceOfAuthenticatorStaticStageRequest(value: object): value is AuthenticatorStaticStageRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthenticatorStaticStageRequestFromJSON(json: any): AuthenticatorStaticStageRequest {
    return AuthenticatorStaticStageRequestFromJSONTyped(json, false);
}

export function AuthenticatorStaticStageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatorStaticStageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'configureFlow': json['configure_flow'] == null ? undefined : json['configure_flow'],
        'friendlyName': json['friendly_name'] == null ? undefined : json['friendly_name'],
        'tokenCount': json['token_count'] == null ? undefined : json['token_count'],
        'tokenLength': json['token_length'] == null ? undefined : json['token_length'],
    };
}

export function AuthenticatorStaticStageRequestToJSON(json: any): AuthenticatorStaticStageRequest {
    return AuthenticatorStaticStageRequestToJSONTyped(json, false);
}

export function AuthenticatorStaticStageRequestToJSONTyped(value?: AuthenticatorStaticStageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'configure_flow': value['configureFlow'],
        'friendly_name': value['friendlyName'],
        'token_count': value['tokenCount'],
        'token_length': value['tokenLength'],
    };
}

