/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Minimal ring serializer (owner-less).
 *
 * - bindings: read-only (use set-bindings to update)
 * @export
 * @interface CertificateKeyPairRing
 */
export interface CertificateKeyPairRing {
    /**
     *
     */
    readonly ringUuid: string;
    /**
     *
     */
    name?: string;
    /**
     *
     */
    readonly bindings: Array<{ [key: string]: any }>;
}

/**
 * Check if a given object implements the CertificateKeyPairRing interface.
 */
export function instanceOfCertificateKeyPairRing(value: object): value is CertificateKeyPairRing {
    if (
        (!("ringUuid" in (value as Record<string, any>)) &&
            !("ring_uuid" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["ringUuid"] === undefined &&
            (value as Record<string, any>)["ring_uuid"] === undefined)
    )
        return false;
    if (!("bindings" in value) || value["bindings"] === undefined) return false;
    return true;
}

export function CertificateKeyPairRingFromJSON(json: any): CertificateKeyPairRing {
    return CertificateKeyPairRingFromJSONTyped(json, false);
}

export function CertificateKeyPairRingFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CertificateKeyPairRing {
    if (json == null) {
        return json;
    }
    return {
        ringUuid: json["ring_uuid"],
        name: json["name"] == null ? undefined : json["name"],
        bindings: json["bindings"],
    };
}

export function CertificateKeyPairRingToJSON(json: any): CertificateKeyPairRing {
    return CertificateKeyPairRingToJSONTyped(json, false);
}

export function CertificateKeyPairRingToJSONTyped(
    value?: Omit<CertificateKeyPairRing, "ringUuid" | "bindings"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
