/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConditionGroupNodeTypeEnum } from "./ConditionGroupNodeTypeEnum";
import {
    ConditionGroupNodeTypeEnumFromJSON,
    ConditionGroupNodeTypeEnumToJSON,
} from "./ConditionGroupNodeTypeEnum";
import type { ConditionGroupOp } from "./ConditionGroupOp";
import { ConditionGroupOpFromJSON, ConditionGroupOpToJSON } from "./ConditionGroupOp";
import type { ConditionNode } from "./ConditionNode";
import { ConditionNodeFromJSON, ConditionNodeToJSON } from "./ConditionNode";

/**
 * Combine the results of multiple conditions
 *
 * @export
 * @interface ConditionGroupNode
 */
export interface ConditionGroupNode {
    type: ConditionGroupNodeTypeEnum;
    op: ConditionGroupOp;
    children: Array<ConditionNode>;
}

/**
 * Check if a given object implements the ConditionGroupNode interface.
 */
export function instanceOfConditionGroupNode(value: object): value is ConditionGroupNode {
    if (!("type" in value) || value["type"] === undefined) return false;
    if (!("op" in value) || value["op"] === undefined) return false;
    if (!("children" in value) || value["children"] === undefined) return false;
    return true;
}

export function ConditionGroupNodeFromJSON(json: any): ConditionGroupNode {
    return ConditionGroupNodeFromJSONTyped(json, false);
}

export function ConditionGroupNodeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ConditionGroupNode {
    if (json == null) {
        return json;
    }
    return {
        type: ConditionGroupNodeTypeEnumFromJSON(json["type"]),
        op: ConditionGroupOpFromJSON(json["op"]),
        children: (json["children"] as Array<any>).map(ConditionNodeFromJSON),
    };
}

export function ConditionGroupNodeToJSON(json: any): ConditionGroupNode {
    return ConditionGroupNodeToJSONTyped(json, false);
}

export function ConditionGroupNodeToJSONTyped(
    value?: ConditionGroupNode | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        type: ConditionGroupNodeTypeEnumToJSON(value["type"]),
        op: ConditionGroupOpToJSON(value["op"]),
        children: (value["children"] as Array<any>).map(ConditionNodeToJSON),
    };
}
