/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const IssuerModeEnum = {
    Global: "global",
    PerProvider: "per_provider",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type IssuerModeEnum = (typeof IssuerModeEnum)[keyof typeof IssuerModeEnum];

export function instanceOfIssuerModeEnum(value: any): boolean {
    for (const key in IssuerModeEnum) {
        if (Object.prototype.hasOwnProperty.call(IssuerModeEnum, key)) {
            if (IssuerModeEnum[key as keyof typeof IssuerModeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IssuerModeEnumFromJSON(json: any): IssuerModeEnum {
    return IssuerModeEnumFromJSONTyped(json, false);
}

export function IssuerModeEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): IssuerModeEnum {
    return json as IssuerModeEnum;
}

export function IssuerModeEnumToJSON(value?: IssuerModeEnum | null): any {
    return value as any;
}

export function IssuerModeEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): IssuerModeEnum {
    return value as IssuerModeEnum;
}
