/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LDAPSourceSyncStatusEnum = {
    Running: "running",
    Error: "error",
    Warning: "warning",
    Done: "done",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type LDAPSourceSyncStatusEnum =
    (typeof LDAPSourceSyncStatusEnum)[keyof typeof LDAPSourceSyncStatusEnum];

export function instanceOfLDAPSourceSyncStatusEnum(value: any): boolean {
    for (const key in LDAPSourceSyncStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(LDAPSourceSyncStatusEnum, key)) {
            if (LDAPSourceSyncStatusEnum[key as keyof typeof LDAPSourceSyncStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LDAPSourceSyncStatusEnumFromJSON(json: any): LDAPSourceSyncStatusEnum {
    return LDAPSourceSyncStatusEnumFromJSONTyped(json, false);
}

export function LDAPSourceSyncStatusEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): LDAPSourceSyncStatusEnum {
    return json as LDAPSourceSyncStatusEnum;
}

export function LDAPSourceSyncStatusEnumToJSON(value?: LDAPSourceSyncStatusEnum | null): any {
    return value as any;
}

export function LDAPSourceSyncStatusEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): LDAPSourceSyncStatusEnum {
    return value as LDAPSourceSyncStatusEnum;
}
