/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LocaleCatalogMessagesValue } from "./LocaleCatalogMessagesValue";
import {
    LocaleCatalogMessagesValueFromJSON,
    LocaleCatalogMessagesValueToJSON,
} from "./LocaleCatalogMessagesValue";

/**
 * LocaleCatalog Serializer
 *
 * @export
 * @interface LocaleCatalogRequest
 */
export interface LocaleCatalogRequest {
    name: string;
    /**
     * Locale code, for example `de` or `de-DE`.
     */
    locale: string;
    enabled?: boolean;
    /**
     * Maps a source string (or a web interface message ID) to its translation. A list of plural
     * forms may be given instead of a single translation.
     */
    messages?: { [key: string]: LocaleCatalogMessagesValue };
}

/**
 * Check if a given object implements the LocaleCatalogRequest interface.
 */
export function instanceOfLocaleCatalogRequest(value: object): value is LocaleCatalogRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("locale" in value) || value["locale"] === undefined) return false;
    return true;
}

export function LocaleCatalogRequestFromJSON(json: any): LocaleCatalogRequest {
    return LocaleCatalogRequestFromJSONTyped(json, false);
}

export function LocaleCatalogRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): LocaleCatalogRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        locale: json["locale"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        messages:
            json["messages"] == null
                ? undefined
                : mapValues(json["messages"], LocaleCatalogMessagesValueFromJSON),
    };
}

export function LocaleCatalogRequestToJSON(json: any): LocaleCatalogRequest {
    return LocaleCatalogRequestToJSONTyped(json, false);
}

export function LocaleCatalogRequestToJSONTyped(
    value?: LocaleCatalogRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        locale: value["locale"],
        enabled: value["enabled"],
        messages:
            value["messages"] == null
                ? undefined
                : mapValues(value["messages"], LocaleCatalogMessagesValueToJSON),
    };
}
