/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { DuoDevice } from './DuoDevice';
import {
    DuoDeviceFromJSON,
    DuoDeviceFromJSONTyped,
    DuoDeviceToJSON,
    DuoDeviceToJSONTyped,
} from './DuoDevice';

/**
 * 
 * @export
 * @interface PaginatedDuoDeviceList
 */
export interface PaginatedDuoDeviceList {
    /**
     * 
     * @type {Pagination}
     * @memberof PaginatedDuoDeviceList
     */
    pagination: Pagination;
    /**
     * 
     * @type {Array<DuoDevice>}
     * @memberof PaginatedDuoDeviceList
     */
    results: Array<DuoDevice>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedDuoDeviceList
     */
    autocomplete: { [key: string]: any; };
}

/**
 * Check if a given object implements the PaginatedDuoDeviceList interface.
 */
export function instanceOfPaginatedDuoDeviceList(value: object): value is PaginatedDuoDeviceList {
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('autocomplete' in value) || value['autocomplete'] === undefined) return false;
    return true;
}

export function PaginatedDuoDeviceListFromJSON(json: any): PaginatedDuoDeviceList {
    return PaginatedDuoDeviceListFromJSONTyped(json, false);
}

export function PaginatedDuoDeviceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDuoDeviceList {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': PaginationFromJSON(json['pagination']),
        'results': ((json['results'] as Array<any>).map(DuoDeviceFromJSON)),
        'autocomplete': json['autocomplete'],
    };
}

export function PaginatedDuoDeviceListToJSON(json: any): PaginatedDuoDeviceList {
    return PaginatedDuoDeviceListToJSONTyped(json, false);
}

export function PaginatedDuoDeviceListToJSONTyped(value?: PaginatedDuoDeviceList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': PaginationToJSON(value['pagination']),
        'results': ((value['results'] as Array<any>).map(DuoDeviceToJSON)),
        'autocomplete': value['autocomplete'],
    };
}

