/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";
import type { Schedule } from "./Schedule";
import { ScheduleFromJSON, ScheduleToJSON } from "./Schedule";

/**
 *
 * @export
 * @interface PaginatedScheduleList
 */
export interface PaginatedScheduleList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedScheduleList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<Schedule>}
     * @memberof PaginatedScheduleList
     */
    results: Array<Schedule>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedScheduleList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedScheduleList interface.
 */
export function instanceOfPaginatedScheduleList(value: object): value is PaginatedScheduleList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedScheduleListFromJSON(json: any): PaginatedScheduleList {
    return PaginatedScheduleListFromJSONTyped(json, false);
}

export function PaginatedScheduleListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedScheduleList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(ScheduleFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedScheduleListToJSON(json: any): PaginatedScheduleList {
    return PaginatedScheduleListToJSONTyped(json, false);
}

export function PaginatedScheduleListToJSONTyped(
    value?: PaginatedScheduleList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(ScheduleToJSON),
        autocomplete: value["autocomplete"],
    };
}
