/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { GroupKerberosSourceConnection } from './GroupKerberosSourceConnection';
import {
    GroupKerberosSourceConnectionFromJSON,
    GroupKerberosSourceConnectionFromJSONTyped,
    GroupKerberosSourceConnectionToJSON,
    GroupKerberosSourceConnectionToJSONTyped,
} from './GroupKerberosSourceConnection';

/**
 * 
 * @export
 * @interface PaginatedGroupKerberosSourceConnectionList
 */
export interface PaginatedGroupKerberosSourceConnectionList {
    /**
     * 
     * @type {Pagination}
     * @memberof PaginatedGroupKerberosSourceConnectionList
     */
    pagination: Pagination;
    /**
     * 
     * @type {Array<GroupKerberosSourceConnection>}
     * @memberof PaginatedGroupKerberosSourceConnectionList
     */
    results: Array<GroupKerberosSourceConnection>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedGroupKerberosSourceConnectionList
     */
    autocomplete: { [key: string]: any; };
}

/**
 * Check if a given object implements the PaginatedGroupKerberosSourceConnectionList interface.
 */
export function instanceOfPaginatedGroupKerberosSourceConnectionList(value: object): value is PaginatedGroupKerberosSourceConnectionList {
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('autocomplete' in value) || value['autocomplete'] === undefined) return false;
    return true;
}

export function PaginatedGroupKerberosSourceConnectionListFromJSON(json: any): PaginatedGroupKerberosSourceConnectionList {
    return PaginatedGroupKerberosSourceConnectionListFromJSONTyped(json, false);
}

export function PaginatedGroupKerberosSourceConnectionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGroupKerberosSourceConnectionList {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': PaginationFromJSON(json['pagination']),
        'results': ((json['results'] as Array<any>).map(GroupKerberosSourceConnectionFromJSON)),
        'autocomplete': json['autocomplete'],
    };
}

export function PaginatedGroupKerberosSourceConnectionListToJSON(json: any): PaginatedGroupKerberosSourceConnectionList {
    return PaginatedGroupKerberosSourceConnectionListToJSONTyped(json, false);
}

export function PaginatedGroupKerberosSourceConnectionListToJSONTyped(value?: PaginatedGroupKerberosSourceConnectionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': PaginationToJSON(value['pagination']),
        'results': ((value['results'] as Array<any>).map(GroupKerberosSourceConnectionToJSON)),
        'autocomplete': value['autocomplete'],
    };
}

