/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DeviceClassesEnum } from "./DeviceClassesEnum";
import { DeviceClassesEnumFromJSON, DeviceClassesEnumToJSON } from "./DeviceClassesEnum";
import type { NotConfiguredActionEnum } from "./NotConfiguredActionEnum";
import {
    NotConfiguredActionEnumFromJSON,
    NotConfiguredActionEnumToJSON,
} from "./NotConfiguredActionEnum";
import type { UserVerificationEnum } from "./UserVerificationEnum";
import { UserVerificationEnumFromJSON, UserVerificationEnumToJSON } from "./UserVerificationEnum";
import type { WebAuthnHintEnum } from "./WebAuthnHintEnum";
import { WebAuthnHintEnumFromJSON, WebAuthnHintEnumToJSON } from "./WebAuthnHintEnum";

/**
 * AuthenticatorValidateStage Serializer
 * @export
 * @interface PatchedAuthenticatorValidateStageRequest
 */
export interface PatchedAuthenticatorValidateStageRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    name?: string;
    /**
     *
     * @type {NotConfiguredActionEnum}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    notConfiguredAction?: NotConfiguredActionEnum;
    /**
     * Device classes which can be used to authenticate
     * @type {Array<DeviceClassesEnum>}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    deviceClasses?: Array<DeviceClassesEnum>;
    /**
     * Stages used to configure Authenticator when user doesn't have any compatible devices. After this configuration Stage passes, the user is not prompted again.
     * @type {Array<string>}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    configurationStages?: Array<string>;
    /**
     * If any of the user's device has been used within this threshold, this stage will be skipped
     * @type {string}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    lastAuthThreshold?: string;
    /**
     * Enforce user verification for WebAuthn devices.
     * @type {UserVerificationEnum}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    webauthnUserVerification?: UserVerificationEnum;
    /**
     *
     * @type {Array<WebAuthnHintEnum>}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    webauthnHints?: Array<WebAuthnHintEnum>;
    /**
     *
     * @type {Array<string>}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    webauthnAllowedDeviceTypes?: Array<string>;
    /**
     *
     * @type {number}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    emailOtpThrottlingFactor?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    smsOtpThrottlingFactor?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    totpOtpThrottlingFactor?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedAuthenticatorValidateStageRequest
     */
    staticOtpThrottlingFactor?: number;
}

/**
 * Check if a given object implements the PatchedAuthenticatorValidateStageRequest interface.
 */
export function instanceOfPatchedAuthenticatorValidateStageRequest(
    value: object,
): value is PatchedAuthenticatorValidateStageRequest {
    return true;
}

export function PatchedAuthenticatorValidateStageRequestFromJSON(
    json: any,
): PatchedAuthenticatorValidateStageRequest {
    return PatchedAuthenticatorValidateStageRequestFromJSONTyped(json, false);
}

export function PatchedAuthenticatorValidateStageRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedAuthenticatorValidateStageRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        notConfiguredAction:
            json["not_configured_action"] == null
                ? undefined
                : NotConfiguredActionEnumFromJSON(json["not_configured_action"]),
        deviceClasses:
            json["device_classes"] == null
                ? undefined
                : (json["device_classes"] as Array<any>).map(DeviceClassesEnumFromJSON),
        configurationStages:
            json["configuration_stages"] == null ? undefined : json["configuration_stages"],
        lastAuthThreshold:
            json["last_auth_threshold"] == null ? undefined : json["last_auth_threshold"],
        webauthnUserVerification:
            json["webauthn_user_verification"] == null
                ? undefined
                : UserVerificationEnumFromJSON(json["webauthn_user_verification"]),
        webauthnHints:
            json["webauthn_hints"] == null
                ? undefined
                : (json["webauthn_hints"] as Array<any>).map(WebAuthnHintEnumFromJSON),
        webauthnAllowedDeviceTypes:
            json["webauthn_allowed_device_types"] == null
                ? undefined
                : json["webauthn_allowed_device_types"],
        emailOtpThrottlingFactor:
            json["email_otp_throttling_factor"] == null
                ? undefined
                : json["email_otp_throttling_factor"],
        smsOtpThrottlingFactor:
            json["sms_otp_throttling_factor"] == null
                ? undefined
                : json["sms_otp_throttling_factor"],
        totpOtpThrottlingFactor:
            json["totp_otp_throttling_factor"] == null
                ? undefined
                : json["totp_otp_throttling_factor"],
        staticOtpThrottlingFactor:
            json["static_otp_throttling_factor"] == null
                ? undefined
                : json["static_otp_throttling_factor"],
    };
}

export function PatchedAuthenticatorValidateStageRequestToJSON(
    json: any,
): PatchedAuthenticatorValidateStageRequest {
    return PatchedAuthenticatorValidateStageRequestToJSONTyped(json, false);
}

export function PatchedAuthenticatorValidateStageRequestToJSONTyped(
    value?: PatchedAuthenticatorValidateStageRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        not_configured_action: NotConfiguredActionEnumToJSON(value["notConfiguredAction"]),
        device_classes:
            value["deviceClasses"] == null
                ? undefined
                : (value["deviceClasses"] as Array<any>).map(DeviceClassesEnumToJSON),
        configuration_stages: value["configurationStages"],
        last_auth_threshold: value["lastAuthThreshold"],
        webauthn_user_verification: UserVerificationEnumToJSON(value["webauthnUserVerification"]),
        webauthn_hints:
            value["webauthnHints"] == null
                ? undefined
                : (value["webauthnHints"] as Array<any>).map(WebAuthnHintEnumToJSON),
        webauthn_allowed_device_types: value["webauthnAllowedDeviceTypes"],
        email_otp_throttling_factor: value["emailOtpThrottlingFactor"],
        sms_otp_throttling_factor: value["smsOtpThrottlingFactor"],
        totp_otp_throttling_factor: value["totpOtpThrottlingFactor"],
        static_otp_throttling_factor: value["staticOtpThrottlingFactor"],
    };
}
