/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * TelegramSourcePropertyMapping Serializer
 * @export
 * @interface PatchedTelegramSourcePropertyMappingRequest
 */
export interface PatchedTelegramSourcePropertyMappingRequest {
    /**
     * Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
     * @type {string}
     * @memberof PatchedTelegramSourcePropertyMappingRequest
     */
    managed?: string | null;
    /**
     *
     * @type {string}
     * @memberof PatchedTelegramSourcePropertyMappingRequest
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedTelegramSourcePropertyMappingRequest
     */
    expression?: string;
}

/**
 * Check if a given object implements the PatchedTelegramSourcePropertyMappingRequest interface.
 */
export function instanceOfPatchedTelegramSourcePropertyMappingRequest(
    value: object,
): value is PatchedTelegramSourcePropertyMappingRequest {
    return true;
}

export function PatchedTelegramSourcePropertyMappingRequestFromJSON(
    json: any,
): PatchedTelegramSourcePropertyMappingRequest {
    return PatchedTelegramSourcePropertyMappingRequestFromJSONTyped(json, false);
}

export function PatchedTelegramSourcePropertyMappingRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedTelegramSourcePropertyMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        managed: json["managed"] == null ? undefined : json["managed"],
        name: json["name"] == null ? undefined : json["name"],
        expression: json["expression"] == null ? undefined : json["expression"],
    };
}

export function PatchedTelegramSourcePropertyMappingRequestToJSON(
    json: any,
): PatchedTelegramSourcePropertyMappingRequest {
    return PatchedTelegramSourcePropertyMappingRequestToJSONTyped(json, false);
}

export function PatchedTelegramSourcePropertyMappingRequestToJSONTyped(
    value?: PatchedTelegramSourcePropertyMappingRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        managed: value["managed"],
        name: value["name"],
        expression: value["expression"],
    };
}
