/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClientTypeEnum } from "./ClientTypeEnum";
import { ClientTypeEnumFromJSON, ClientTypeEnumToJSON } from "./ClientTypeEnum";
import type { GrantTypesEnum } from "./GrantTypesEnum";
import { GrantTypesEnumFromJSON, GrantTypesEnumToJSON } from "./GrantTypesEnum";
import type { IssuerModeEnum } from "./IssuerModeEnum";
import { IssuerModeEnumFromJSON, IssuerModeEnumToJSON } from "./IssuerModeEnum";
import type { OAuth2ProviderLogoutMethodEnum } from "./OAuth2ProviderLogoutMethodEnum";
import {
    OAuth2ProviderLogoutMethodEnumFromJSON,
    OAuth2ProviderLogoutMethodEnumToJSON,
} from "./OAuth2ProviderLogoutMethodEnum";
import type { RedirectURIRequest } from "./RedirectURIRequest";
import { RedirectURIRequestFromJSON, RedirectURIRequestToJSON } from "./RedirectURIRequest";
import type { SubModeEnum } from "./SubModeEnum";
import { SubModeEnumFromJSON, SubModeEnumToJSON } from "./SubModeEnum";

/**
 * OAuth2Provider Serializer
 * @export
 * @interface PatchedOAuth2ProviderRequest
 */
export interface PatchedOAuth2ProviderRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    name?: string;
    /**
     * Flow used for authentication when the associated application is accessed by an un-authenticated user.
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    authenticationFlow?: string | null;
    /**
     * Flow used when authorizing this provider.
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    authorizationFlow?: string;
    /**
     * Flow used ending the session from a provider.
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    invalidationFlow?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof PatchedOAuth2ProviderRequest
     */
    propertyMappings?: Array<string>;
    /**
     * Confidential clients are capable of maintaining the confidentiality of their credentials. Public clients are incapable
     * @type {ClientTypeEnum}
     * @memberof PatchedOAuth2ProviderRequest
     */
    clientType?: ClientTypeEnum;
    /**
     *
     * @type {Array<GrantTypesEnum>}
     * @memberof PatchedOAuth2ProviderRequest
     */
    grantTypes?: Array<GrantTypesEnum>;
    /**
     *
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    clientSecret?: string;
    /**
     * Access codes not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    accessCodeValidity?: string;
    /**
     * Tokens not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    accessTokenValidity?: string;
    /**
     * Tokens not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    refreshTokenValidity?: string;
    /**
     * When refreshing a token, if the refresh token is valid for less than this duration, it will be renewed. When set to seconds=0, token will always be renewed. (Format: hours=1;minutes=2;seconds=3).
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    refreshTokenThreshold?: string;
    /**
     * Include User claims from scopes in the id_token, for applications that don't access the userinfo endpoint.
     * @type {boolean}
     * @memberof PatchedOAuth2ProviderRequest
     */
    includeClaimsInIdToken?: boolean;
    /**
     * Key used to sign the tokens.
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    signingKey?: string | null;
    /**
     * Key used to encrypt the tokens. When set, tokens will be encrypted and returned as JWEs.
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    encryptionKey?: string | null;
    /**
     *
     * @type {Array<RedirectURIRequest>}
     * @memberof PatchedOAuth2ProviderRequest
     */
    redirectUris?: Array<RedirectURIRequest>;
    /**
     *
     * @type {string}
     * @memberof PatchedOAuth2ProviderRequest
     */
    logoutUri?: string;
    /**
     * Backchannel logs out with server to server calls. Frontchannel uses iframes in your browser
     * @type {OAuth2ProviderLogoutMethodEnum}
     * @memberof PatchedOAuth2ProviderRequest
     */
    logoutMethod?: OAuth2ProviderLogoutMethodEnum;
    /**
     * Configure what data should be used as unique User Identifier. For most cases, the default should be fine.
     * @type {SubModeEnum}
     * @memberof PatchedOAuth2ProviderRequest
     */
    subMode?: SubModeEnum;
    /**
     * Configure how the issuer field of the ID Token should be filled.
     * @type {IssuerModeEnum}
     * @memberof PatchedOAuth2ProviderRequest
     */
    issuerMode?: IssuerModeEnum;
    /**
     *
     * @type {Array<string>}
     * @memberof PatchedOAuth2ProviderRequest
     */
    jwtFederationSources?: Array<string>;
    /**
     *
     * @type {Array<number>}
     * @memberof PatchedOAuth2ProviderRequest
     */
    jwtFederationProviders?: Array<number>;
}

/**
 * Check if a given object implements the PatchedOAuth2ProviderRequest interface.
 */
export function instanceOfPatchedOAuth2ProviderRequest(
    value: object,
): value is PatchedOAuth2ProviderRequest {
    return true;
}

export function PatchedOAuth2ProviderRequestFromJSON(json: any): PatchedOAuth2ProviderRequest {
    return PatchedOAuth2ProviderRequestFromJSONTyped(json, false);
}

export function PatchedOAuth2ProviderRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedOAuth2ProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        authenticationFlow:
            json["authentication_flow"] == null ? undefined : json["authentication_flow"],
        authorizationFlow:
            json["authorization_flow"] == null ? undefined : json["authorization_flow"],
        invalidationFlow: json["invalidation_flow"] == null ? undefined : json["invalidation_flow"],
        propertyMappings: json["property_mappings"] == null ? undefined : json["property_mappings"],
        clientType:
            json["client_type"] == null ? undefined : ClientTypeEnumFromJSON(json["client_type"]),
        grantTypes:
            json["grant_types"] == null
                ? undefined
                : (json["grant_types"] as Array<any>).map(GrantTypesEnumFromJSON),
        clientId: json["client_id"] == null ? undefined : json["client_id"],
        clientSecret: json["client_secret"] == null ? undefined : json["client_secret"],
        accessCodeValidity:
            json["access_code_validity"] == null ? undefined : json["access_code_validity"],
        accessTokenValidity:
            json["access_token_validity"] == null ? undefined : json["access_token_validity"],
        refreshTokenValidity:
            json["refresh_token_validity"] == null ? undefined : json["refresh_token_validity"],
        refreshTokenThreshold:
            json["refresh_token_threshold"] == null ? undefined : json["refresh_token_threshold"],
        includeClaimsInIdToken:
            json["include_claims_in_id_token"] == null
                ? undefined
                : json["include_claims_in_id_token"],
        signingKey: json["signing_key"] == null ? undefined : json["signing_key"],
        encryptionKey: json["encryption_key"] == null ? undefined : json["encryption_key"],
        redirectUris:
            json["redirect_uris"] == null
                ? undefined
                : (json["redirect_uris"] as Array<any>).map(RedirectURIRequestFromJSON),
        logoutUri: json["logout_uri"] == null ? undefined : json["logout_uri"],
        logoutMethod:
            json["logout_method"] == null
                ? undefined
                : OAuth2ProviderLogoutMethodEnumFromJSON(json["logout_method"]),
        subMode: json["sub_mode"] == null ? undefined : SubModeEnumFromJSON(json["sub_mode"]),
        issuerMode:
            json["issuer_mode"] == null ? undefined : IssuerModeEnumFromJSON(json["issuer_mode"]),
        jwtFederationSources:
            json["jwt_federation_sources"] == null ? undefined : json["jwt_federation_sources"],
        jwtFederationProviders:
            json["jwt_federation_providers"] == null ? undefined : json["jwt_federation_providers"],
    };
}

export function PatchedOAuth2ProviderRequestToJSON(json: any): PatchedOAuth2ProviderRequest {
    return PatchedOAuth2ProviderRequestToJSONTyped(json, false);
}

export function PatchedOAuth2ProviderRequestToJSONTyped(
    value?: PatchedOAuth2ProviderRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        authentication_flow: value["authenticationFlow"],
        authorization_flow: value["authorizationFlow"],
        invalidation_flow: value["invalidationFlow"],
        property_mappings: value["propertyMappings"],
        client_type: ClientTypeEnumToJSON(value["clientType"]),
        grant_types:
            value["grantTypes"] == null
                ? undefined
                : (value["grantTypes"] as Array<any>).map(GrantTypesEnumToJSON),
        client_id: value["clientId"],
        client_secret: value["clientSecret"],
        access_code_validity: value["accessCodeValidity"],
        access_token_validity: value["accessTokenValidity"],
        refresh_token_validity: value["refreshTokenValidity"],
        refresh_token_threshold: value["refreshTokenThreshold"],
        include_claims_in_id_token: value["includeClaimsInIdToken"],
        signing_key: value["signingKey"],
        encryption_key: value["encryptionKey"],
        redirect_uris:
            value["redirectUris"] == null
                ? undefined
                : (value["redirectUris"] as Array<any>).map(RedirectURIRequestToJSON),
        logout_uri: value["logoutUri"],
        logout_method: OAuth2ProviderLogoutMethodEnumToJSON(value["logoutMethod"]),
        sub_mode: SubModeEnumToJSON(value["subMode"]),
        issuer_mode: IssuerModeEnumToJSON(value["issuerMode"]),
        jwt_federation_sources: value["jwtFederationSources"],
        jwt_federation_providers: value["jwtFederationProviders"],
    };
}
