/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Group Source Connection
 * @export
 * @interface PatchedGroupSourceConnectionRequest
 */
export interface PatchedGroupSourceConnectionRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedGroupSourceConnectionRequest
     */
    source?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedGroupSourceConnectionRequest
     */
    identifier?: string;
}

/**
 * Check if a given object implements the PatchedGroupSourceConnectionRequest interface.
 */
export function instanceOfPatchedGroupSourceConnectionRequest(
    value: object,
): value is PatchedGroupSourceConnectionRequest {
    return true;
}

export function PatchedGroupSourceConnectionRequestFromJSON(
    json: any,
): PatchedGroupSourceConnectionRequest {
    return PatchedGroupSourceConnectionRequestFromJSONTyped(json, false);
}

export function PatchedGroupSourceConnectionRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedGroupSourceConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        source: json["source"] == null ? undefined : json["source"],
        identifier: json["identifier"] == null ? undefined : json["identifier"],
    };
}

export function PatchedGroupSourceConnectionRequestToJSON(
    json: any,
): PatchedGroupSourceConnectionRequest {
    return PatchedGroupSourceConnectionRequestToJSONTyped(json, false);
}

export function PatchedGroupSourceConnectionRequestToJSONTyped(
    value?: PatchedGroupSourceConnectionRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        source: value["source"],
        identifier: value["identifier"],
    };
}
