/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PolicyEngineMode } from "./PolicyEngineMode";
import { PolicyEngineModeFromJSON, PolicyEngineModeToJSON } from "./PolicyEngineMode";

/**
 * Mixin to validate that a valid enterprise license
 * exists before allowing to save the object
 * @export
 * @interface PersonaTemplate
 */
export interface PersonaTemplate {
    /**
     *
     * @type {string}
     * @memberof PersonaTemplate
     */
    uuid?: string;
    /**
     *
     * @type {PolicyEngineMode}
     * @memberof PersonaTemplate
     */
    policyEngineMode?: PolicyEngineMode;
    /**
     *
     * @type {string}
     * @memberof PersonaTemplate
     */
    name: string;
    /**
     *
     * @type {Array<number>}
     * @memberof PersonaTemplate
     */
    actorProviders?: Array<number>;
    /**
     *
     * @type {Array<string>}
     * @memberof PersonaTemplate
     */
    actorSources?: Array<string>;
}

/**
 * Check if a given object implements the PersonaTemplate interface.
 */
export function instanceOfPersonaTemplate(value: object): value is PersonaTemplate {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function PersonaTemplateFromJSON(json: any): PersonaTemplate {
    return PersonaTemplateFromJSONTyped(json, false);
}

export function PersonaTemplateFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PersonaTemplate {
    if (json == null) {
        return json;
    }
    return {
        uuid: json["uuid"] == null ? undefined : json["uuid"],
        policyEngineMode:
            json["policy_engine_mode"] == null
                ? undefined
                : PolicyEngineModeFromJSON(json["policy_engine_mode"]),
        name: json["name"],
        actorProviders: json["actor_providers"] == null ? undefined : json["actor_providers"],
        actorSources: json["actor_sources"] == null ? undefined : json["actor_sources"],
    };
}

export function PersonaTemplateToJSON(json: any): PersonaTemplate {
    return PersonaTemplateToJSONTyped(json, false);
}

export function PersonaTemplateToJSONTyped(
    value?: PersonaTemplate | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        uuid: value["uuid"],
        policy_engine_mode: PolicyEngineModeToJSON(value["policyEngineMode"]),
        name: value["name"],
        actor_providers: value["actorProviders"],
        actor_sources: value["actorSources"],
    };
}
