/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for Service connection state
 * @export
 * @interface ServiceConnectionState
 */
export interface ServiceConnectionState {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceConnectionState
     */
    readonly healthy: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceConnectionState
     */
    readonly version: string;
}

/**
 * Check if a given object implements the ServiceConnectionState interface.
 */
export function instanceOfServiceConnectionState(value: object): value is ServiceConnectionState {
    if (!('healthy' in value) || value['healthy'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ServiceConnectionStateFromJSON(json: any): ServiceConnectionState {
    return ServiceConnectionStateFromJSONTyped(json, false);
}

export function ServiceConnectionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceConnectionState {
    if (json == null) {
        return json;
    }
    return {
        
        'healthy': json['healthy'],
        'version': json['version'],
    };
}

export function ServiceConnectionStateToJSON(json: any): ServiceConnectionState {
    return ServiceConnectionStateToJSONTyped(json, false);
}

export function ServiceConnectionStateToJSONTyped(value?: Omit<ServiceConnectionState, 'healthy'|'version'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

