/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const SyncStatusEnum = {
    Running: "running",
    Error: "error",
    Warning: "warning",
    Done: "done",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type SyncStatusEnum = (typeof SyncStatusEnum)[keyof typeof SyncStatusEnum];

export function instanceOfSyncStatusEnum(value: any): boolean {
    for (const key in SyncStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(SyncStatusEnum, key)) {
            if (SyncStatusEnum[key as keyof typeof SyncStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SyncStatusEnumFromJSON(json: any): SyncStatusEnum {
    return SyncStatusEnumFromJSONTyped(json, false);
}

export function SyncStatusEnumFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SyncStatusEnum {
    return json as SyncStatusEnum;
}

export function SyncStatusEnumToJSON(value?: SyncStatusEnum | null): any {
    return value as any;
}

export function SyncStatusEnumToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): SyncStatusEnum {
    return value as SyncStatusEnum;
}
