/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PartialUser } from "./PartialUser";
import { PartialUserFromJSON } from "./PartialUser";
import type { Source } from "./Source";
import { SourceFromJSON } from "./Source";

/**
 * User source connection
 * @export
 * @interface UserLDAPSourceConnection
 */
export interface UserLDAPSourceConnection {
    /**
     *
     * @type {number}
     * @memberof UserLDAPSourceConnection
     */
    readonly pk: number;
    /**
     *
     * @type {number}
     * @memberof UserLDAPSourceConnection
     */
    user: number;
    /**
     *
     * @type {string}
     * @memberof UserLDAPSourceConnection
     */
    source: string;
    /**
     *
     * @type {Source}
     * @memberof UserLDAPSourceConnection
     */
    readonly sourceObj: Source;
    /**
     *
     * @type {string}
     * @memberof UserLDAPSourceConnection
     */
    identifier: string;
    /**
     *
     * @type {Date}
     * @memberof UserLDAPSourceConnection
     */
    readonly created: Date;
    /**
     *
     * @type {Date}
     * @memberof UserLDAPSourceConnection
     */
    readonly lastUpdated: Date;
    /**
     *
     * @type {PartialUser}
     * @memberof UserLDAPSourceConnection
     */
    readonly userObj: PartialUser;
}

/**
 * Check if a given object implements the UserLDAPSourceConnection interface.
 */
export function instanceOfUserLDAPSourceConnection(
    value: object,
): value is UserLDAPSourceConnection {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("user" in value) || value["user"] === undefined) return false;
    if (!("source" in value) || value["source"] === undefined) return false;
    if (!("sourceObj" in value) || value["sourceObj"] === undefined) return false;
    if (!("identifier" in value) || value["identifier"] === undefined) return false;
    if (!("created" in value) || value["created"] === undefined) return false;
    if (!("lastUpdated" in value) || value["lastUpdated"] === undefined) return false;
    if (!("userObj" in value) || value["userObj"] === undefined) return false;
    return true;
}

export function UserLDAPSourceConnectionFromJSON(json: any): UserLDAPSourceConnection {
    return UserLDAPSourceConnectionFromJSONTyped(json, false);
}

export function UserLDAPSourceConnectionFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserLDAPSourceConnection {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        user: json["user"],
        source: json["source"],
        sourceObj: SourceFromJSON(json["source_obj"]),
        identifier: json["identifier"],
        created: new Date(json["created"]),
        lastUpdated: new Date(json["last_updated"]),
        userObj: PartialUserFromJSON(json["user_obj"]),
    };
}

export function UserLDAPSourceConnectionToJSON(json: any): UserLDAPSourceConnection {
    return UserLDAPSourceConnectionToJSONTyped(json, false);
}

export function UserLDAPSourceConnectionToJSONTyped(
    value?: Omit<
        UserLDAPSourceConnection,
        "pk" | "source_obj" | "created" | "last_updated" | "user_obj"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        user: value["user"],
        source: value["source"],
        identifier: value["identifier"],
    };
}
