name: "Process test results"
description: Convert test results to JUnit, add them to GitHub Actions and codecov

inputs:
  flags:
    description: Codecov flags

runs:
  using: "composite"
  steps:
    - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
      with:
        flags: ${{ inputs.flags }}
        use_oidc: true
    - uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
      with:
        flags: ${{ inputs.flags }}
        file: unittest.xml
        use_oidc: true
    - name: PostgreSQL Logs
      shell: bash
      run: |
        if [[ $ACTIONS_RUNNER_DEBUG == 'true' || $ACTIONS_STEP_DEBUG == 'true' ]]; then
          docker stop setup-postgresql-1
          echo "::group::PostgreSQL Logs"
          docker logs setup-postgresql-1
          echo "::endgroup::"
        fi
