# Generated by Django 5.2.12 on 2026-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_ssf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="stream",
            name="delivery_method",
            field=models.TextField(
                choices=[
                    ("https://schemas.openid.net/secevent/risc/delivery-method/push", "Risc Push"),
                    ("https://schemas.openid.net/secevent/risc/delivery-method/poll", "Risc Poll"),
                    ("urn:ietf:rfc:8935", "Rfc Push"),
                    ("urn:ietf:rfc:8936", "Rfc Pull"),
                ]
            ),
        ),
    ]
