# Generated by Django 5.2.15 on 2026-06-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0035_oauth2providerjwtfederationprovider_and_more"),
        ("authentik_providers_ssf", "0002_ssfprovider_push_verify_certificates_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="SSFProviderOIDCAuthProvider",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "oauth2_provider",
                            models.ForeignKey(
                                db_column="oauth2provider_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_providers_oauth2.oauth2provider",
                            ),
                        ),
                        (
                            "ssf_provider",
                            models.ForeignKey(
                                db_column="ssfprovider_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_providers_ssf.ssfprovider",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authentik_providers_ssf_ssfprovider_oidc_auth_providers",
                        "unique_together": {("ssf_provider", "oauth2_provider")},
                        "verbose_name": "SSF Provider OIDC Auth Provider",
                        "verbose_name_plural": "SSF Provider OIDC Auth Providers",
                    },
                ),
                migrations.AlterField(
                    model_name="ssfprovider",
                    name="oidc_auth_providers",
                    field=models.ManyToManyField(
                        blank=True,
                        default=None,
                        through="authentik_providers_ssf.SSFProviderOIDCAuthProvider",
                        to="authentik_providers_oauth2.oauth2provider",
                    ),
                ),
            ],
        ),
    ]
