# Generated by Django 5.2.15 on 2026-06-23 15:35

import django.db.models.deletion
from django.db import migrations, models

SQL = """
ALTER TABLE authentik_stages_mtls_mutualtlsstage_certificate_authorities RENAME TO authentik_stages_mtls_mutualtlsstagecertificateauthority;
ALTER TABLE authentik_stages_mtls_mutualtlsstagecertificateauthority RENAME COLUMN mutualtlsstage_id to mutual_tls_stage_id;
ALTER TABLE authentik_stages_mtls_mutualtlsstagecertificateauthority RENAME COLUMN certificatekeypair_id to certificate_key_pair_id;
"""

REVERSE_SQL = """
ALTER TABLE authentik_stages_mtls_mutualtlsstagecertificateauthority RENAME COLUMN certificate_key_pair_id to certificatekeypair_id;
ALTER TABLE authentik_stages_mtls_mutualtlsstagecertificateauthority RENAME COLUMN mutual_tls_stage_id to mutualtlsstage_id;
ALTER TABLE authentik_stages_mtls_mutualtlsstagecertificateauthority RENAME TO authentik_stages_mtls_mutualtlsstage_certificate_authorities;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto", "0006_certificatekeypair_cert_expiry_and_more"),
        ("authentik_stages_mtls", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=SQL,
                    reverse_sql=REVERSE_SQL,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="MutualTLSStageCertificateAuthority",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "certificate_key_pair",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_crypto.certificatekeypair",
                            ),
                        ),
                        (
                            "mutual_tls_stage",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_stages_mtls.mutualtlsstage",
                            ),
                        ),
                    ],
                    options={
                        "unique_together": {("mutual_tls_stage", "certificate_key_pair")},
                    },
                ),
                migrations.AlterField(
                    model_name="mutualtlsstage",
                    name="certificate_authorities",
                    field=models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="Configure certificate authorities to validate the certificate against. This option has a higher priority than the `client_certificate` option on `Brand`.",
                        through="authentik_stages_mtls.MutualTLSStageCertificateAuthority",
                        to="authentik_crypto.certificatekeypair",
                    ),
                ),
            ],
        ),
    ]
