# Generated by Django 3.0.8 on 2020-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_policies_hibp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="haveibeenpwendpolicy",
            name="password_field",
            field=models.TextField(
                default="password",
                help_text="Field key to check, field keys defined in Prompt stages are available.",
            ),
        ),
    ]
