# Generated by Django 4.0.2 on 2022-02-26 21:14

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from authentik.flows.models import FlowDesignation
from authentik.stages.identification.models import UserFields
from authentik.stages.password import BACKEND_APP_PASSWORD, BACKEND_INBUILT, BACKEND_LDAP

# Generated by Django 3.0.3 on 2020-05-08 14:30


def create_default_user_settings_flow(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    from authentik.stages.prompt.models import FieldTypes

    db_alias = schema_editor.connection.alias

    Tenant = apps.get_model("authentik_tenants", "Tenant")

    Flow = apps.get_model("authentik_flows", "Flow")
    FlowStageBinding = apps.get_model("authentik_flows", "FlowStageBinding")

    UserLoginStage = apps.get_model("authentik_stages_user_login", "UserLoginStage")
    UserWriteStage = apps.get_model("authentik_stages_user_write", "UserWriteStage")
    PromptStage = apps.get_model("authentik_stages_prompt", "PromptStage")
    Prompt = apps.get_model("authentik_stages_prompt", "Prompt")

    prompt_username, _ = Prompt.objects.using(db_alias).update_or_create(
        field_key="username",
        defaults={
            "label": "Username",
            "type": FieldTypes.USERNAME,
            "placeholder": "Username",
            "order": 100,
        },
    )
    prompt_name, _ = Prompt.objects.using(db_alias).update_or_create(
        field_key="name",
        defaults={
            "label": "Username",
            "type": FieldTypes.TEXT,
            "placeholder": "Name",
            "order": 101,
        },
    )
    prompt_email, _ = Prompt.objects.using(db_alias).update_or_create(
        field_key="email",
        defaults={
            "label": "Email",
            "type": FieldTypes.EMAIL,
            "placeholder": "Email",
            "order": 102,
        },
    )
    prompt_locale, _ = Prompt.objects.using(db_alias).update_or_create(
        field_key="locale",
        defaults={
            "label": "Locale",
            "type": FieldTypes.TEXT,
            "placeholder": "Locale",
            "order": 103,
        },
    )

    prompt_stage, _ = PromptStage.objects.using(db_alias).update_or_create(
        name="default-user-settings",
    )
    prompt_stage.fields.set([prompt_username, prompt_name, prompt_email, prompt_locale])
    prompt_stage.save()
    user_write, _ = UserWriteStage.objects.using(db_alias).update_or_create(
        name="default-user-settings-write"
    )

    flow, _ = Flow.objects.using(db_alias).update_or_create(
        slug="default-user-settings-flow",
        designation=FlowDesignation.STAGE_CONFIGURATION,
        defaults={
            "name": "Update your info",
        },
    )
    FlowStageBinding.objects.using(db_alias).update_or_create(
        target=flow,
        stage=prompt_stage,
        defaults={
            "order": 10,
        },
    )
    FlowStageBinding.objects.using(db_alias).update_or_create(
        target=flow,
        stage=user_write,
        defaults={
            "order": 100,
        },
    )

    tenant = Tenant.objects.using(db_alias).filter(default=True).first()
    if not tenant:
        return
    tenant.flow_user_settings = flow
    tenant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_flows", "0021_auto_20211227_2103"),
        ("authentik_tenants", "0001_squashed_0005_tenant_web_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="flow_user_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_user_settings",
                to="authentik_flows.flow",
            ),
        ),
        migrations.RunPython(create_default_user_settings_flow),
    ]
