# Generated by Django 5.0.1 on 2024-01-24 14:27

from django.db import migrations, models

import authentik.tenants.models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="user_directory_attributes",
            field=models.JSONField(
                blank=True, default=list, help_text="Attributes to show in the user directory."
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="user_directory_fields",
            field=models.JSONField(
                blank=True,
                default=authentik.tenants.models._default_user_directory_fields,
                help_text="Fields to show in the user directory.",
            ),
        ),
    ]
