# Generated by Django 3.2.5 on 2021-07-24 17:06

from django.db import migrations, models

import authentik.lib.utils.time


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tenants", "0003_tenant_branding_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="event_retention",
            field=models.TextField(
                default="days=365",
                help_text="Events will be deleted after this duration.(Format: weeks=3;days=2;hours=3,seconds=2).",
                validators=[authentik.lib.utils.time.timedelta_string_validator],
            ),
        ),
    ]
