# Generated by Django 5.2.9 on 2025-12-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tenants", "0009_remove_tenant_panic_button_security_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="panic_button_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable the account lockdown feature for administrators."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="panic_button_notify_admins",
            field=models.BooleanField(
                default=True,
                help_text="Send email notification to administrators when account lockdown is triggered.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="panic_button_notify_security",
            field=models.BooleanField(
                default=False,
                help_text="Send email notification to security email address when account lockdown is triggered.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="panic_button_notify_user",
            field=models.BooleanField(
                default=True,
                help_text="Send email notification to the affected user when account lockdown is triggered.",
            ),
        ),
    ]
