#!/bin/sh
# config maintainer script for passbook
set -e

# source debconf stuff
. /usr/share/debconf/confmodule

dbc_first_version=1.0.0
dbc_dbuser=passbook
dbc_dbname=passbook

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
    . /usr/share/dbconfig-common/dpkg/config.pgsql
    dbc_go passbook "$@"
fi

#DEBHELPER#

exit 0
