#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.pgsql
    dbc_go passbook "$@"
fi


if [ "$1" = "purge" ]; then
    if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/passbook/config.d/database.yml
        ucfr --purge passbook /etc/passbook/config.d/database.yml
    fi
    rm -rf /etc/passbook/
    rm -rf /usr/share/passbook/
fi

#DEBHELPER#

