# Generated by Django 3.1 on 2020-08-24 16:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("passbook_core", "0008_auto_20200824_1532"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outpost",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("providers", models.ManyToManyField(to="passbook_core.Provider")),
            ],
        ),
    ]
