# Generated by Django 5.2.17 on 2026-09-23 19:30

import authentik.policies.conditional.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_policies", "0012_alter_policybinding_managers_policybinding_expires_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionalPolicy",
            fields=[
                (
                    "policy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_policies.policy",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=authentik.policies.conditional.models.default_conditions
                    ),
                ),
                (
                    "missing_behavior",
                    models.TextField(
                        choices=[
                            ("fail", "Fail the policy"),
                            ("false", "Evaluate the condition as false"),
                        ],
                        default="fail",
                        help_text="How to handle conditions whose variable is not available in the request.",
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Message shown to the user when the policy does not pass.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conditional Policy",
                "verbose_name_plural": "Conditional Policies",
                "indexes": [
                    models.Index(fields=["policy_ptr_id"], name="authentik_p_policy__639963_idx")
                ],
            },
            bases=("authentik_policies.policy",),
        ),
    ]
