# Generated by Django 5.0.1 on 2024-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_ldap", "0003_ldapsource_client_certificate_ldapsource_sni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldapsource",
            name="password_login_update_internal_password",
            field=models.BooleanField(
                default=True,
                help_text="Update internal authentik password when login succeeds with LDAP",
            ),
        ),
        migrations.AlterField(
            model_name="ldapsource",
            name="password_login_update_internal_password",
            field=models.BooleanField(
                default=False,
                help_text="Update internal authentik password when login succeeds with LDAP",
            ),
        ),
    ]
