# Generated by Django 5.0.2 on 2024-03-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0036_alter_group_name"),
        ("authentik_sources_ldap", "0004_remove_ldappropertymapping_object_field_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LDAPPropertyMapping",
            new_name="LDAPSourcePropertyMapping",
        ),
    ]
