# Generated by Django 5.2.15 on 2026-06-15 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_ldap", "0011_ldapsource_sync_outgoing_trigger_mode"),
        ("authentik_tasks", "0007_task_dependencies_alter_task_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPSourceSync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("expires", models.DateTimeField(default=None, null=True)),
                ("expiring", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("users_count", models.PositiveBigIntegerField(default=0)),
                ("groups_count", models.PositiveBigIntegerField(default=0)),
                ("membership_count", models.PositiveBigIntegerField(default=0)),
                ("user_deletions_count", models.PositiveBigIntegerField(default=0)),
                ("group_deletions_count", models.PositiveBigIntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_sources_ldap.ldapsource",
                    ),
                ),
                ("tasks", models.ManyToManyField(related_name="+", to="authentik_tasks.task")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
