# Generated by Django 5.2.14 on 2026-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_ldap", "0012_ldapsource_sync_just_in_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldapsource",
            name="sync_users_just_in_time",
            field=models.BooleanField(
                default=False,
                help_text="Enable this option to automatically sync users Just In Time into Authentik as they login/authenticate.",
            ),
        ),
    ]
