# Generated by Django 5.2.17 on 2026-10-10 19:20

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import move_credentials

FIELDS = [("bind_password", "bind_password_ref", "text", "bind password")]


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0004_role_permissions"),
        ("authentik_rbac", "0011_initialpermissionspermission"),
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_sources_ldap", "0013_ldapsource_service_bind_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldapsource",
            name="bind_password_ref",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ldap_sources",
                to="authentik_crypto_secrets.secret",
                verbose_name="Bind password",
            ),
        ),
        move_credentials("authentik_sources_ldap", "LDAPSource", FIELDS),
    ]
