# Generated by Django 5.2.15 on 2026-06-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0060_sourcegrouppropertymapping_and_more"),
        (
            "authentik_providers_microsoft_entra",
            "0004_microsoftentraprovider_sync_page_size_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="MicrosoftEntraProviderPropertyMappingsGroup",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "microsoft_entra_provider",
                            models.ForeignKey(
                                db_column="microsoftentraprovider_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_providers_microsoft_entra.microsoftentraprovider",
                            ),
                        ),
                        (
                            "property_mapping",
                            models.ForeignKey(
                                db_column="propertymapping_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_core.propertymapping",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authentik_providers_microsoft_entra_microsoftentraprovider_9f0b",
                        "unique_together": {("microsoft_entra_provider", "property_mapping")},
                        "verbose_name": "Microsoft Entra Provider Property Mappings Group",
                        "verbose_name_plural": "Microsoft Entra Provider Property Mappings Groups",
                    },
                ),
                migrations.AlterField(
                    model_name="microsoftentraprovider",
                    name="property_mappings_group",
                    field=models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="Property mappings used for group creation/updating.",
                        through="authentik_providers_microsoft_entra.MicrosoftEntraProviderPropertyMappingsGroup",
                        to="authentik_core.propertymapping",
                    ),
                ),
            ],
        ),
    ]
