# Generated by Django 5.2.17 on 2026-09-23 21:07

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import (
    migrate_credentials,
    restore_credentials,
)
from authentik.crypto.secrets.migrations._permissions import preserve_role_permissions

FIELDS = [("_client_secret", "client_secret_ref", None, "client secret")]


def forwards(apps, schema_editor):
    migrate_credentials(
        apps, schema_editor, "authentik_providers_microsoft_entra", "MicrosoftEntraProvider", FIELDS
    )
    preserve_role_permissions(
        apps, schema_editor, [("authentik_providers_microsoft_entra", "microsoftentraprovider")]
    )


def backwards(apps, schema_editor):
    restore_credentials(
        apps, schema_editor, "authentik_providers_microsoft_entra", "MicrosoftEntraProvider", FIELDS
    )


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0005_delete_userobjectpermission_and_groupobjectpermission"),
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_providers_microsoft_entra", "0006_microsoftentraprovider_discovery_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microsoftentraprovider",
            name="client_secret",
            field=models.TextField(db_column="client_secret"),
        ),
        migrations.RenameField(
            model_name="microsoftentraprovider",
            old_name="client_secret",
            new_name="_client_secret",
        ),
        migrations.AddField(
            model_name="microsoftentraprovider",
            name="client_secret_ref",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="microsoft_entra_providers",
                to="authentik_crypto_secrets.secret",
                verbose_name="Client Secret",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", "SET CONSTRAINTS ALL IMMEDIATE"),
    ]
