# Generated by Django 5.2.17 on 2026-09-09 18:46

from importlib import import_module

from django.db import migrations


def preserve_role_permissions(apps, schema_editor):
    migration = import_module("authentik.secrets.migrations.0002_preserve_role_permissions")
    migration.preserve_role_permissions(
        apps, schema_editor, [("authentik_providers_microsoft_entra", "microsoftentraprovider")]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_secrets", "0002_preserve_role_permissions"),
        ("authentik_providers_microsoft_entra", "0007_microsoftentraprovider_secret"),
    ]

    operations = [migrations.RunPython(preserve_role_permissions, migrations.RunPython.noop)]
