# Generated by Django 5.2.17 on 2026-09-23 21:07

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import (
    migrate_credentials,
    restore_credentials,
)
from authentik.crypto.secrets.migrations._permissions import preserve_role_permissions

FIELDS = [("credentials", "credentials_ref", "multiline", "credentials")]


def forwards(apps, schema_editor):
    migrate_credentials(
        apps,
        schema_editor,
        "authentik_endpoints_connectors_google_chrome",
        "googlechromeconnector",
        FIELDS,
    )
    preserve_role_permissions(
        apps,
        schema_editor,
        [("authentik_endpoints_connectors_google_chrome", "googlechromeconnector")],
    )


def backwards(apps, schema_editor):
    restore_credentials(
        apps,
        schema_editor,
        "authentik_endpoints_connectors_google_chrome",
        "googlechromeconnector",
        FIELDS,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0005_delete_userobjectpermission_and_groupobjectpermission"),
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_endpoints_connectors_google_chrome", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlechromeconnector",
            name="credentials_ref",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="google_chrome_connectors",
                to="authentik_crypto_secrets.secret",
                verbose_name="Google credentials",
            ),
        ),
        migrations.AlterField(
            model_name="googlechromeconnector",
            name="credentials",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", "SET CONSTRAINTS ALL IMMEDIATE"),
    ]
