# Generated by Django 3.0.3 on 2020-05-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policybindingmodel",
            options={
                "verbose_name": "Policy Binding Model",
                "verbose_name_plural": "Policy Binding Models",
            },
        ),
    ]
