// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointDevice {
    #[serde(rename = "device_uuid", skip_serializing_if = "Option::is_none")]
    pub device_uuid: Option<uuid::Uuid>,
    #[serde(rename = "pbm_uuid")]
    pub pbm_uuid: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "access_group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub access_group: Option<Option<uuid::Uuid>>,
    #[serde(rename = "access_group_obj", skip_serializing_if = "Option::is_none")]
    pub access_group_obj: Option<models::DeviceAccessGroup>,
    #[serde(rename = "expiring", skip_serializing_if = "Option::is_none")]
    pub expiring: Option<bool>,
    #[serde(
        rename = "expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires: Option<Option<String>>,
    #[serde(rename = "facts")]
    pub facts: models::DeviceFactSnapshot,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl EndpointDevice {
    pub fn new(
        pbm_uuid: uuid::Uuid,
        name: String,
        facts: models::DeviceFactSnapshot,
    ) -> EndpointDevice {
        EndpointDevice {
            device_uuid: None,
            pbm_uuid,
            name,
            access_group: None,
            access_group_obj: None,
            expiring: None,
            expires: None,
            facts,
            attributes: None,
        }
    }
}
