// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// FlowStageBindingRequest : FlowStageBinding Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowStageBindingRequest {
    #[serde(rename = "target")]
    pub target: uuid::Uuid,
    #[serde(rename = "stage")]
    pub stage: uuid::Uuid,
    /// Evaluate policies during the Flow planning process.
    #[serde(rename = "evaluate_on_plan", skip_serializing_if = "Option::is_none")]
    pub evaluate_on_plan: Option<bool>,
    /// Evaluate policies when the Stage is presented to the user.
    #[serde(
        rename = "re_evaluate_policies",
        skip_serializing_if = "Option::is_none"
    )]
    pub re_evaluate_policies: Option<bool>,
    #[serde(rename = "order")]
    pub order: i32,
    #[serde(rename = "policy_engine_mode", skip_serializing_if = "Option::is_none")]
    pub policy_engine_mode: Option<models::PolicyEngineMode>,
    /// Configure how the flow executor should handle an invalid response to a challenge. RETRY
    /// returns the error message and a similar challenge to the executor. RESTART restarts the
    /// flow from the beginning, and RESTART_WITH_CONTEXT restarts the flow while keeping the
    /// current context.
    #[serde(
        rename = "invalid_response_action",
        skip_serializing_if = "Option::is_none"
    )]
    pub invalid_response_action: Option<models::InvalidResponseActionEnum>,
}

impl FlowStageBindingRequest {
    /// FlowStageBinding Serializer
    pub fn new(target: uuid::Uuid, stage: uuid::Uuid, order: i32) -> FlowStageBindingRequest {
        FlowStageBindingRequest {
            target,
            stage,
            evaluate_on_plan: None,
            re_evaluate_policies: None,
            order,
            policy_engine_mode: None,
            invalid_response_action: None,
        }
    }
}
