// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

/// GroupLdapSourceConnectionRequest : Group Source Connection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupLdapSourceConnectionRequest {
    #[serde(rename = "group")]
    pub group: uuid::Uuid,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl GroupLdapSourceConnectionRequest {
    /// Group Source Connection
    pub fn new(
        group: uuid::Uuid,
        source: uuid::Uuid,
        identifier: String,
    ) -> GroupLdapSourceConnectionRequest {
        GroupLdapSourceConnectionRequest {
            group,
            source,
            identifier,
        }
    }
}
