/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedAuthenticatorStaticStageRequest : AuthenticatorStaticStage Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedAuthenticatorStaticStageRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Flow used by an authenticated user to configure this Stage. If empty, user will not be able to configure this stage.
    #[serde(
        rename = "configure_flow",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub configure_flow: Option<Option<uuid::Uuid>>,
    #[serde(rename = "friendly_name", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<String>,
    #[serde(rename = "token_count", skip_serializing_if = "Option::is_none")]
    pub token_count: Option<u32>,
    #[serde(rename = "token_length", skip_serializing_if = "Option::is_none")]
    pub token_length: Option<u8>,
}

impl PatchedAuthenticatorStaticStageRequest {
    /// AuthenticatorStaticStage Serializer
    pub fn new() -> PatchedAuthenticatorStaticStageRequest {
        PatchedAuthenticatorStaticStageRequest {
            name: None,
            configure_flow: None,
            friendly_name: None,
            token_count: None,
            token_length: None,
        }
    }
}
