/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScopeMappingRequest : ScopeMapping Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScopeMappingRequest {
    /// Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
    #[serde(
        rename = "managed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub managed: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "expression")]
    pub expression: String,
    /// Scope name requested by the client
    #[serde(rename = "scope_name")]
    pub scope_name: String,
    /// Description shown to the user when consenting. If left empty, the user won't be informed.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ScopeMappingRequest {
    /// ScopeMapping Serializer
    pub fn new(name: String, expression: String, scope_name: String) -> ScopeMappingRequest {
        ScopeMappingRequest {
            managed: None,
            name,
            expression,
            scope_name,
            description: None,
        }
    }
}
