/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserServiceAccountRequest : Payload to create a service account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserServiceAccountRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "create_group", skip_serializing_if = "Option::is_none")]
    pub create_group: Option<bool>,
    #[serde(rename = "expiring", skip_serializing_if = "Option::is_none")]
    pub expiring: Option<bool>,
    /// If not provided, valid for 360 days
    #[serde(rename = "expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<String>,
}

impl UserServiceAccountRequest {
    /// Payload to create a service account
    pub fn new(name: String) -> UserServiceAccountRequest {
        UserServiceAccountRequest {
            name,
            create_group: None,
            expiring: None,
            expires: None,
        }
    }
}
