// authentik
//
// Making authentication simple.
//
// The version of the OpenAPI document: 2026.5.0-rc1
// Contact: hello@goauthentik.io
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAgentResponse {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "user_uid")]
    pub user_uid: String,
    #[serde(rename = "user_pk")]
    pub user_pk: i32,
}

impl UserAgentResponse {
    pub fn new(
        username: String,
        token: String,
        user_uid: String,
        user_pk: i32,
    ) -> UserAgentResponse {
        UserAgentResponse {
            username,
            token,
            user_uid,
            user_pk,
        }
    }
}
