/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserPasswordSetRequest : Payload to set a users' password directly
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPasswordSetRequest {
    #[serde(rename = "password")]
    pub password: String,
}

impl UserPasswordSetRequest {
    /// Payload to set a users' password directly
    pub fn new(password: String) -> UserPasswordSetRequest {
        UserPasswordSetRequest { password }
    }
}
