# Generated by Django 2.2.6 on 2019-10-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_core", "0002_auto_20191010_1058"),
        ("passbook_core", "0002_nonce_description"),
    ]

    operations = []
