# Generated by Django 2.1.3 on 2018-11-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0003_rule_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='passbook_core.Rule')),
                ('url', models.URLField()),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('patch', 'patch'), ('delete', 'delete'), ('put', 'put')], max_length=10)),
                ('json_body', models.TextField()),
                ('json_headers', models.TextField()),
                ('result_jsonpath', models.TextField()),
                ('result_json_value', models.TextField()),
            ],
            options={
                'verbose_name': 'Webhook Rule',
                'verbose_name_plural': 'Webhook Rules',
            },
            bases=('passbook_core.rule',),
        ),
        migrations.AlterModelOptions(
            name='fieldmatcherrule',
            options={'verbose_name': 'Field matcher Rule', 'verbose_name_plural': 'Field matcher Rules'},
        ),
        migrations.AlterField(
            model_name='fieldmatcherrule',
            name='match_action',
            field=models.CharField(choices=[('startswith', 'Starts with'), ('endswith', 'Ends with'), ('endswith', 'Contains'), ('regexp', 'Regexp'), ('exact', 'Exact')], max_length=50),
        ),
    ]
