# Generated by Django 2.1.4 on 2018-12-09 17:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0005_auto_20181127_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
