# Generated by Django 2.1.4 on 2018-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0005_auto_20181226_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
    ]
