# Generated by Django 2.1.7 on 2019-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0012_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='needs_confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
