# Generated by Django 3.0.5 on 2020-05-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_core", "0012_delete_factor"),
    ]

    operations = []
