# Generated by Django 2.1.7 on 2019-02-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0014_auto_20190226_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordpolicy',
            name='error_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
