# Generated by Django 2.1.7 on 2019-03-10 16:15

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passbook_core', '0018_provider_property_mappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='extra_data',
        ),
        HStoreExtension(),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
