# Generated by Django 3.1.1 on 2020-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_sources_ldap", "0006_auto_20200915_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldapsource",
            name="sync_users_password",
            field=models.BooleanField(
                default=True,
                help_text="When a user changes their password, sync it back to LDAP. This can only be enabled on a single LDAP source.",
                unique=True,
            ),
        ),
    ]
