# Generated by Django 5.2.17 on 2026-09-09 18:57

from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models

from authentik.secrets.migrations._credential_values import migrate_credentials, restore_credentials

FIELDS = [("credentials", "secret", "multiline")]


def forwards(apps, schema_editor):
    migrate_credentials(
        apps,
        schema_editor,
        "authentik_stages_authenticator_endpoint_gdtc",
        "authenticatorendpointgdtcstage",
        FIELDS,
    )
    migration = import_module("authentik.secrets.migrations.0002_preserve_role_permissions")
    migration.preserve_role_permissions(
        apps,
        schema_editor,
        [("authentik_stages_authenticator_endpoint_gdtc", "authenticatorendpointgdtcstage")],
    )


def backwards(apps, schema_editor):
    restore_credentials(
        apps,
        schema_editor,
        "authentik_stages_authenticator_endpoint_gdtc",
        "authenticatorendpointgdtcstage",
        FIELDS,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_secrets", "0002_preserve_role_permissions"),
        (
            "authentik_stages_authenticator_endpoint_gdtc",
            "0002_alter_authenticatorendpointgdtcstage_friendly_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticatorendpointgdtcstage",
            name="secret",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gdtc_stages",
                to="authentik_secrets.secret",
                verbose_name="Google credentials",
            ),
        ),
        migrations.AlterField(
            model_name="authenticatorendpointgdtcstage",
            name="credentials",
            field=models.JSONField(default=dict),
        ),
        # Finish foreign-key checks before the schema editor creates the new indexes.
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE", "SET CONSTRAINTS ALL IMMEDIATE"),
        migrations.RunPython(forwards, backwards),
    ]
