# Generated by Django 5.2.17 on 2026-09-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_stages_authenticator_endpoint_gdtc",
            "0003_authenticatorendpointgdtcstage_secret_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authenticatorendpointgdtcstage",
            name="credentials",
        ),
    ]
