# Generated by Django 4.2.4 on 2023-09-03 00:55

from django.db import migrations, models

import authentik.stages.authenticator_totp.models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_stages_authenticator_totp", "0009_auto_20190420_0723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpdevice",
            name="key",
            field=models.CharField(
                default=authentik.stages.authenticator_totp.models.default_key,
                help_text="A hex-encoded secret key of up to 40 bytes.",
                max_length=80,
                validators=[authentik.stages.authenticator_totp.models.key_validator],
            ),
        ),
        migrations.AlterModelOptions(
            name="totpdevice",
            options={"verbose_name": "TOTP device", "verbose_name_plural": "TOTP devices"},
        ),
    ]
