# Generated by Django 5.2.14 on 2026-05-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_flows", "0032_alter_flow_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSelectionStage",
            fields=[
                (
                    "stage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_flows.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Selection Stage",
                "verbose_name_plural": "User Selection Stages",
            },
            bases=("authentik_flows.stage",),
        ),
    ]
