# Generated by Django 5.1.11 on 2025-06-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_stages_authenticator_webauthn",
            "0012_webauthndevice_created_webauthndevice_last_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticatorwebauthnstage",
            name="max_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
