# Generated by Django 5.2.11 on 2026-03-04 02:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_stages_authenticator_webauthn",
            "0014_alter_authenticatorwebauthnstage_friendly_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticatorwebauthnstage",
            name="hints",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("security-key", "Security Key"),
                        ("client-device", "Client Device"),
                        ("hybrid", "Hybrid"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
