# Generated by Django 5.2.7 on 2025-10-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0051_group_authentik_c_is_supe_1e5a97_idx"),
        ("authentik_endpoints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentToken",
            fields=[
                (
                    "token_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.token",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("authentik_core.token",),
        ),
        migrations.AddField(
            model_name="devicegroup",
            name="tokens",
            field=models.ManyToManyField(to="authentik_endpoints.enrollmenttoken"),
        ),
    ]
