# Generated by Django 5.2.8 on 2025-11-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_endpoints", "0001_initial"),
        ("authentik_policies", "0011_policybinding_failure_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicegroup",
            name="policybindingmodel_ptr",
        ),
        migrations.RemoveField(
            model_name="device",
            name="group",
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "Device", "verbose_name_plural": "Devices"},
        ),
        migrations.AlterModelOptions(
            name="deviceconnection",
            options={
                "verbose_name": "Device connection",
                "verbose_name_plural": "Device connections",
            },
        ),
        migrations.AlterModelOptions(
            name="devicefactsnapshot",
            options={
                "verbose_name": "Device fact snapshot",
                "verbose_name_plural": "Device fact snapshots",
            },
        ),
        migrations.AlterModelOptions(
            name="deviceuserbinding",
            options={
                "verbose_name": "Device User binding",
                "verbose_name_plural": "Device User bindings",
            },
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name="DeviceTag",
            fields=[
                (
                    "policybindingmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_endpoints.connector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device tag",
                "verbose_name_plural": "Device tags",
            },
            bases=("authentik_policies.policybindingmodel",),
        ),
        migrations.AddField(
            model_name="device",
            name="tags",
            field=models.ManyToManyField(blank=True, to="authentik_endpoints.devicetag"),
        ),
    ]
