# Generated by Django 5.2.8 on 2025-11-16 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_endpoints", "0003_deviceconnection_last_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceconnection",
            name="data",
        ),
        migrations.RemoveField(
            model_name="deviceconnection",
            name="last_update",
        ),
        migrations.CreateModel(
            name="DeviceFactSnapshot",
            fields=[
                (
                    "snapshot_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_endpoints.deviceconnection",
                    ),
                ),
            ],
        ),
    ]
