# Generated by Django 5.2.8 on 2025-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_endpoints", "0007_alter_connector_enabled"),
        ("authentik_policies", "0011_policybinding_failure_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="expires",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="expiring",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["expires"], name="authentik_e_expires_f533f5_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["expiring"], name="authentik_e_expirin_038503_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["expiring", "expires"], name="authentik_e_expirin_b26ba1_idx"
            ),
        ),
    ]
