# Generated by Django 2.2.6 on 2019-10-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("passbook_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyFactor",
            fields=[
                (
                    "factor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="passbook_core.Factor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dummy Factor",
                "verbose_name_plural": "Dummy Factors",
            },
            bases=("passbook_core.factor",),
        ),
    ]
