# Generated by Django 5.1.12 on 2025-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_stages_authenticator_static",
            "0010_staticdevice_created_staticdevice_last_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="authenticatorstaticstage",
            name="friendly_name",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
