# Generated by Django 5.2.17 on 2026-08-30 21:31

import django.db.models.deletion
from django.db import migrations, models

from authentik.crypto.secrets.migrations._credential_values import (
    migrate_credentials,
    restore_credentials,
)

FIELDS = [("_consumer_secret", "secret", None, "consumer secret")]


def migrate_consumer_secret(apps, schema_editor):
    migrate_credentials(apps, schema_editor, "authentik_sources_oauth", "OAuthSource", FIELDS)


def rollback_consumer_secret(apps, schema_editor):
    restore_credentials(apps, schema_editor, "authentik_sources_oauth", "OAuthSource", FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto_secrets", "0001_initial"),
        ("authentik_sources_oauth", "0015_oauthsource_url_textfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthsource",
            name="consumer_secret",
            field=models.TextField(db_column="consumer_secret"),
        ),
        migrations.RenameField(
            model_name="oauthsource",
            old_name="consumer_secret",
            new_name="_consumer_secret",
        ),
        migrations.AddField(
            model_name="oauthsource",
            name="secret",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oauth_sources",
                to="authentik_crypto_secrets.secret",
                verbose_name="Consumer secret",
            ),
        ),
        migrations.RunPython(migrate_consumer_secret, rollback_consumer_secret),
    ]
