# Generated by Django 5.2.15 on 2026-06-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0060_sourcegrouppropertymapping_and_more"),
        ("authentik_stages_identification", "0017_identificationstage_webauthn_stage"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="IdentificationStageSource",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "identification_stage",
                            models.ForeignKey(
                                db_column="identificationstage_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_stages_identification.identificationstage",
                            ),
                        ),
                        (
                            "source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentik_core.source",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authentik_stages_identification_identificationstage_sources",
                        "unique_together": {("identification_stage", "source")},
                        "verbose_name": "Identification Stage Source",
                        "verbose_name_plural": "Identification Stage Sources",
                    },
                ),
                migrations.AlterField(
                    model_name="identificationstage",
                    name="sources",
                    field=models.ManyToManyField(
                        blank=True,
                        default=list,
                        help_text="Specify which sources should be shown.",
                        through="authentik_stages_identification.IdentificationStageSource",
                        to="authentik_core.source",
                    ),
                ),
            ],
        ),
    ]
