// Taken from the https://fdc.nal.usda.gov/data-documentation.html database of "Foundational Foods."

export const nutritionDbUSDA = [
    {
        name: "Hummus",
        calories: 229,
        sugar: "0.34g",
        fiber: "5.4g",
        protein: "7.35g",
        group: "processed",
    },
    {
        name: "Onion Rings, breaded",
        calories: 288,
        sugar: "4.5g",
        fiber: "2.4g",
        protein: "4.52g",
        group: "processed",
    },
    {
        name: "Bread, white",
        calories: 270,
        sugar: "5.34g",
        fiber: "2.3g",
        protein: "9.43g",
        group: "processed",
    },
    {
        name: "Sweet and Sour Pork, frozen",
        calories: 260,
        sugar: "10.3g",
        fiber: "1g",
        protein: "8.88g",
        group: "processed",
    },
    {
        name: "Almonds",
        calories: 620,
        sugar: "4.17g",
        fiber: "11g",
        protein: "20.4g",
        group: "organic",
    },
    {
        name: "Kale",
        calories: 35,
        sugar: "0.8g",
        fiber: "4.1g",
        protein: "2.92g",
        group: "organic",
    },
    {
        name: "Pickles",
        calories: 12,
        sugar: "1.28g",
        fiber: "1g",
        protein: "0.48g",
        group: "organic",
    },
    {
        name: "Kiwifruit",
        calories: 58,
        sugar: "8.99g",
        fiber: "3g",
        protein: "1.06g",
        group: "organic",
    },
    {
        name: "Sunflower Seeds",
        calories: 612,
        sugar: "3.14g",
        fiber: "10.3g",
        protein: "21g",
        group: "organic",
    },

    {
        name: "Nectarines",
        calories: 39,
        sugar: "7.89g",
        fiber: "1.5g",
        protein: "1.06g",
        group: "organic",
    },
    {
        name: "Oatmeal Cookies",
        calories: 430,
        sugar: "34.8g",
        fiber: "3.3g",
        protein: "5.79g",
        group: "processed",
    },
    {
        name: "Carrots",
        calories: 37,
        sugar: "4.2g",
        fiber: "3.2g",
        protein: "0.81g",
        group: "organic",
    },
    {
        name: "Figs",
        calories: 249,
        sugar: "47.9g",
        fiber: "9.8g",
        protein: "3.3g",
        group: "organic",
    },
    {
        name: "Lettuce",
        calories: 17,
        sugar: "1.19g",
        fiber: "1.8g",
        protein: "1.24g",
        group: "organic",
    },
    {
        name: "Cantaloupe",
        calories: 34,
        sugar: "7.88g",
        fiber: "0.8g",
        protein: "0.82g",
        group: "organic",
    },
    {
        name: "Oranges",
        calories: 47,
        sugar: "8.57g",
        fiber: "2g",
        protein: "0.91g",
        group: "organic",
    },
    {
        name: "Pears",
        calories: 57,
        sugar: "9.69g",
        fiber: "3.1g",
        protein: "0.38g",
        group: "organic",
    },
    {
        name: "Broccoli",
        calories: 31,
        sugar: "1.4g",
        fiber: "2.4g",
        protein: "2.57g",
        group: "organic",
    },
    {
        name: "Eggs",
        calories: 148,
        sugar: "0.2g",
        fiber: "0g",
        protein: "12.4g",
        group: "organic",
    },
    {
        name: "Onions",
        calories: 44,
        sugar: "5.76g",
        fiber: "2.2g",
        protein: "0.94g",
        group: "organic",
    },
    {
        name: "Bananas",
        calories: 97,
        sugar: "15.8g",
        fiber: "1.7g",
        protein: "0.74g",
        group: "organic",
    },
    {
        name: "Apples",
        calories: 64.7,
        sugar: "13.3g",
        fiber: "2.08g",
        protein: "0.148g",
        group: "organic",
    },
    {
        name: "Pineapple",
        calories: 60.1,
        sugar: "11.4g",
        fiber: "0.935g",
        protein: "0.461g",
        group: "organic",
    },
    {
        name: "Snap Green Beans",
        calories: 40,
        sugar: "2.33g",
        fiber: "3.01g",
        protein: "1.97g",
        group: "organic",
    },
    {
        name: "Beets",
        calories: 44.6,
        sugar: "5.1g",
        fiber: "3.12g",
        protein: "1.69g",
        group: "organic",
    },
    {
        name: "Eggplant",
        calories: 26.1,
        sugar: "2.35g",
        fiber: "2.45g",
        protein: "0.852g",
        group: "organic",
    },
];
