# Generated by Django 3.0.6 on 2020-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_flows", "0009_source_flows"),
    ]

    operations = []
