# Generated by Django 3.1 on 2020-08-28 13:14
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_flows", "0010_provider_flows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flow",
            options={
                "permissions": [("export_flow", "Can export a Flow")],
                "verbose_name": "Flow",
                "verbose_name_plural": "Flows",
            },
        ),
        migrations.AddField(
            model_name="flow",
            name="title",
            field=models.TextField(default="", blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flow",
            name="title",
            field=models.TextField(),
        ),
    ]
