# Generated by Django 3.2.3 on 2021-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_flows", "0018_oob_flows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="background",
            field=models.FileField(
                default=None,
                help_text="Background shown during execution",
                null=True,
                upload_to="flow-backgrounds/",
            ),
        ),
    ]
