# Generated by Django 3.2.5 on 2021-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_flows", "0022_alter_flowstagebinding_invalid_response_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="background",
            field=models.FileField(
                default=None,
                help_text="Background shown during execution",
                max_length=500,
                null=True,
                upload_to="flow-backgrounds/",
            ),
        ),
    ]
