# Generated by Django 5.2.8 on 2025-11-26 13:27

import authentik.admin.files.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_flows", "0029_alter_flow_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="background",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Background shown during execution",
                validators=[authentik.admin.files.validation.validate_file_name],
            ),
        ),
    ]
