# Generated by Django 3.0.3 on 2020-05-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passbook_crypto", "0001_initial"),
        ("passbook_providers_saml", "0008_auto_20200305_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlprovider",
            name="require_signing",
            field=models.BooleanField(
                default=False,
                help_text="Require Requests to be signed by an X509 Certificate. Must match the Certificate selected in `Singing Keypair`.",
            ),
        ),
        migrations.AlterField(
            model_name="samlprovider",
            name="issuer",
            field=models.TextField(help_text="Also known as EntityID"),
        ),
        migrations.AlterField(
            model_name="samlprovider",
            name="signing_kp",
            field=models.ForeignKey(
                default=None,
                help_text="Singing is enabled upon selection of a Key Pair.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="passbook_crypto.CertificateKeyPair",
                verbose_name="Signing Keypair",
            ),
        ),
    ]
