# Generated by Django 5.1.9 on 2025-06-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0001_initial"),
        ("authentik_tenants", "0005_tenant_reputation_lower_limit_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="schedule_uid",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.RemoveField(
            model_name="task",
            name="uid",
        ),
        migrations.AddField(
            model_name="task",
            name="rel_obj_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="rel_obj_id",
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["rel_obj_content_type", "rel_obj_id"], name="authentik_t_rel_obj_3a177a_idx"
            ),
        ),
    ]
