# Generated by Django 5.2.7 on 2025-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0002_alter_task_aggregated_status_alter_task_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="eta",
            field=models.DateTimeField(help_text="Planned execution time", null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="retries",
            field=models.PositiveBigIntegerField(default=0, help_text="Number of retries"),
        ),
    ]
