# Generated by Django 5.1.11 on 2025-06-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0003_task__previous_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "default_permissions": ("view",),
                "permissions": [("retry_task", "Retry failed task")],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
