# Generated by Django 5.1.10 on 2025-06-10 14:19

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0003_remove_task_update_aggregated_status_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="task",
            name="update_aggregated_status",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="task",
            trigger=pgtrigger.compiler.Trigger(
                name="update_aggregated_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    constraint="CONSTRAINT",
                    declare="DECLARE aggregated_status TEXT; max_log_level TEXT;",
                    func="\n                    NEW.aggregated_status := CASE\n                        WHEN NEW.state != 'done' THEN NEW.state\n                        ELSE COALESCE((\n                            SELECT CASE\n                                WHEN bool_or(msg->>'log_level' = 'error') THEN 'error'\n                                WHEN bool_or(msg->>'log_level' = 'warning') THEN 'warning'\n                                WHEN bool_or(msg->>'log_level' = 'info') THEN 'info'\n                                ELSE 'done'\n                            END\n                            FROM jsonb_array_elements(NEW._messages) AS msg\n                        ), 'done')\n                    END;\n\n                    RETURN NEW;\n                ",
                    hash="6f01e43ff57b11081bff98b7e7b296ccaaa7cf7f",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_update_aggregated_status_f18c4",
                    table="authentik_tasks_task",
                    timing="DEFERRABLE INITIALLY IMMEDIATE",
                    when="AFTER",
                ),
            ),
        ),
    ]
