# Generated by Django 5.1.11 on 2025-06-25 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0004_alter_task_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerStatus",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("hostname", models.TextField()),
                ("version", models.TextField()),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Worker status",
                "verbose_name_plural": "Worker statuses",
            },
        ),
    ]
