# Generated by Django 5.0.13 on 2025-03-24 12:49

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0004_alter_task_message"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="task",
            name="notify_enqueueing",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="task",
            trigger=pgtrigger.compiler.Trigger(
                name="notify_enqueueing",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.\"state\" = 'queued')",
                    constraint="CONSTRAINT",
                    func="\n                    PERFORM pg_notify(\n                        'authentik.tasks.' || NEW.queue_name || '.enqueue',\n                        NEW.message_id::text\n                    );\n                    RETURN NEW;\n                ",
                    hash="0a9ee3db61e4d63fd72b31322fbb821706dd8a78",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_notify_enqueueing_0bc94",
                    table="authentik_tasks_task",
                    timing="DEFERRABLE INITIALLY DEFERRED",
                    when="AFTER",
                ),
            ),
        ),
    ]
