# Generated by Django 5.2.15 on 2026-06-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_tasks", "0006_task_authentik_t_queue_n_099d0d_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tenant",
        ),
    ]
