# Generated by Django 3.1.7 on 2021-03-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0017_managed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={
                "permissions": (("view_token_key", "View token's key"),),
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
    ]
