# Generated by Django 4.2.3 on 2023-07-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_core", "0032_user_krb5_keys_user_krb5_kvno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="krb5_kvno",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
