# Generated by Django 5.0.8 on 2024-08-08 12:09

from django.db import migrations, models

from authentik.lib.migrations import fallback_names


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0039_source_group_matching_mode_alter_group_name_and_more"),
    ]

    operations = [
        migrations.RunPython(fallback_names("authentik_core", "group", "name")),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.TextField(unique=True, verbose_name="name"),
        ),
    ]
