# Generated by Django 5.0.10 on 2024-12-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0043_session_authenticatedsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authenticatedsession",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="authenticatedsession",
            name="session_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="authentik_core.session",
            ),
        ),
    ]
