# Generated by Django 5.0.10 on 2024-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0044_remove_authenticatedsession_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={},
        ),
        migrations.RemoveField(
            model_name="session",
            name="expire_date",
        ),
        migrations.AddField(
            model_name="session",
            name="expires",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="expiring",
            field=models.BooleanField(default=True),
        ),
    ]
