# Generated by Django 5.1.11 on 2025-07-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentik_core", "0049_alter_token_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_updated"], name="authentik_c_last_up_ed7486_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["date_joined"], name="authentik_c_date_jo_58c256_idx"),
        ),
    ]
