# Generated by Django 5.2.10 on 2026-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0056_user_roles"),
        ("authentik_rbac", "0010_remove_role_group_alter_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="group",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="authentik_rbac.role"
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="ak_groups",
            new_name="groups",
        ),
    ]
