# Generated by Django 5.2.15 on 2026-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0059_add_application_meta_hide"),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticatedsession",
            name="browser_key",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="authenticatedsession",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="authenticatedsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("browser_key__isnull", False), ("is_current", True)),
                fields=("browser_key",),
                name="authentik_core_authenticatedsession_current_browser_key",
            ),
        ),
    ]
