# Generated by Django 5.2.16 on 2026-08-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0063_actor"),
        ("authentik_stages_password", "0012_migrate_user_passwords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
