# Generated by Django 5.2.17 on 2026-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0059_add_application_meta_hide"),
        ("authentik_rbac", "0010_remove_role_group_alter_role_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "is_active", "type"], name="authentik_c_usernam_2f0e4b_idx"
            ),
        ),
    ]
