# Generated by Django 3.1.4 on 2020-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0007_auto_20201016_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2provider",
            name="issuer_mode",
            field=models.TextField(
                choices=[
                    ("global", "Same identifier is used for all providers"),
                    (
                        "per_provider",
                        "Each provider has a different issuer, based on the application slug.",
                    ),
                ],
                default="per_provider",
                help_text="Configure how the issuer field of the ID Token should be filled.",
            ),
        ),
    ]
