# Generated by Django 4.1.7 on 2023-02-22 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_providers_oauth2", "0014_alter_refreshtoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="auth_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Authentication time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authorizationcode",
            name="auth_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Authentication time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="auth_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Authentication time",
            ),
            preserve_default=False,
        ),
    ]
