# Generated by Django 5.0.9 on 2024-09-26 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0018_alter_accesstoken_expires_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Original preserved
    # See https://github.com/goauthentik/authentik/issues/11874
    # operations = [
    #     migrations.AddIndex(
    #         model_name="accesstoken",
    #         index=models.Index(fields=["token"], name="authentik_p_token_4bc870_idx"),
    #     ),
    #     migrations.AddIndex(
    #         model_name="refreshtoken",
    #         index=models.Index(fields=["token"], name="authentik_p_token_1a841f_idx"),
    #     ),
    # ]
    operations = []
