# Generated by Django 5.0.11 on 2025-01-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_core", "0044_authenticatedsession"),
        ("authentik_providers_oauth2", "0028_rename_session_accesstoken_old_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesstoken",
            name="old_session",
        ),
        migrations.RemoveField(
            model_name="authorizationcode",
            name="old_session",
        ),
        migrations.RemoveField(
            model_name="devicetoken",
            name="old_session",
        ),
        migrations.RemoveField(
            model_name="refreshtoken",
            name="old_session",
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentik_core.authenticatedsession",
            ),
        ),
        migrations.AddField(
            model_name="authorizationcode",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentik_core.authenticatedsession",
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="authentik_core.authenticatedsession",
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="authentik_core.authenticatedsession",
            ),
        ),
    ]
