# Generated by Django 5.1.12 on 2025-09-30 10:07

import authentik.lib.models
from django.db import migrations, models


def migrate_backchannel_logout_uri(apps, schema_editor):
    """Copy backchannel_logout_uri to logout_uri and set logout_method"""
    OAuth2Provider = apps.get_model("authentik_providers_oauth2", "OAuth2Provider")
    for provider in OAuth2Provider.objects.all():
        if hasattr(provider, "backchannel_logout_uri") and provider.backchannel_logout_uri:
            provider.logout_uri = provider.backchannel_logout_uri
            provider.logout_method = "backchannel"
            provider.save(update_fields=["logout_uri", "logout_method"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0030_oauth2provider_refresh_token_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2provider",
            name="logout_method",
            field=models.TextField(
                blank=True,
                choices=[("backchannel", "Back-channel"), ("frontchannel", "Front-channel")],
                help_text="Backchannel logs out with server to server calls. Frontchannel uses iframes in your browser",
                verbose_name="Logout Method",
            ),
        ),
        migrations.AddField(
            model_name="oauth2provider",
            name="logout_uri",
            field=models.TextField(
                blank=True,
                validators=[authentik.lib.models.DomainlessURLValidator(schemes=("http", "https"))],
                verbose_name="Logout URI",
            ),
        ),
        # Copy data from old field to new field before removing
        migrations.RunPython(migrate_backchannel_logout_uri, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="oauth2provider",
            name="backchannel_logout_uri",
        ),
    ]
