# Generated by Django 5.2.15 on 2026-07-22 19:46

import authentik.lib.utils.time
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_flows", "0031_alter_flow_layout"),
        ("authentik_policies", "0012_alter_policybinding_managers_policybinding_expires_and_more"),
        ("authentik_providers_oauth2", "0035_oauth2providerjwtfederationprovider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuth2DynamicClientRegistration",
            fields=[
                (
                    "policybindingmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
                (
                    "create_application",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create an Application object for each registered client.",
                        verbose_name="Create application",
                    ),
                ),
                (
                    "default_application_group",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Group to assign to automatically created applications.",
                        verbose_name="Default application group",
                    ),
                ),
                (
                    "default_client_type",
                    models.TextField(
                        choices=[("confidential", "Confidential"), ("public", "Public")],
                        default="confidential",
                        verbose_name="Default client type",
                    ),
                ),
                (
                    "access_token_validity",
                    models.TextField(
                        default="hours=1",
                        help_text="Maximum access token validity for registered clients (Format: hours=1;minutes=2;seconds=3).",
                        validators=[authentik.lib.utils.time.timedelta_string_validator],
                        verbose_name="Access token validity",
                    ),
                ),
                (
                    "refresh_token_validity",
                    models.TextField(
                        default="days=30",
                        help_text="Maximum refresh token validity for registered clients (Format: hours=1;minutes=2;seconds=3).",
                        validators=[authentik.lib.utils.time.timedelta_string_validator],
                        verbose_name="Refresh token validity",
                    ),
                ),
                (
                    "allowed_grant_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(
                            choices=[
                                ("authorization_code", "Authorization Code"),
                                ("implicit", "Implicit"),
                                ("hybrid", "Hybrid"),
                                ("refresh_token", "Refresh Token"),
                                ("client_credentials", "Client Credentials"),
                                ("password", "Password"),
                                ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                                (
                                    "urn:ietf:params:oauth:grant-type:token-exchange",
                                    "Token Exchange",
                                ),
                            ]
                        ),
                        blank=True,
                        default=list,
                        help_text="If empty, all grant types are allowed.",
                        size=None,
                        verbose_name="Allowed grant types",
                    ),
                ),
                (
                    "default_authorization_flow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authorization flow applied to dynamically registered clients.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dcr_default_authorization_flow",
                        to="authentik_flows.flow",
                        verbose_name="Default authorization flow",
                    ),
                ),
                (
                    "default_invalidation_flow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dcr_default_invalidation_flow",
                        to="authentik_flows.flow",
                        verbose_name="Default invalidation flow",
                    ),
                ),
                (
                    "default_property_mappings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Scope mappings applied to dynamically registered clients.",
                        to="authentik_providers_oauth2.scopemapping",
                        verbose_name="Default property mappings",
                    ),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dcr_configuration",
                        to="authentik_providers_oauth2.oauth2provider",
                        verbose_name="Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth2 Dynamic Client Registration",
                "verbose_name_plural": "OAuth2 Dynamic Client Registrations",
            },
            bases=("authentik_policies.policybindingmodel", models.Model),
        ),
    ]
