# Generated by Django 5.0.8 on 2024-08-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0015_alter_samlpropertymapping_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlprovider",
            name="sign_assertion",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="samlprovider",
            name="sign_response",
            field=models.BooleanField(default=True),
        ),
    ]
