# Generated by Django 5.1.11 on 2025-07-22 23:08

import authentik.lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0018_alter_samlprovider_acs_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlprovider",
            name="sls_binding",
            field=models.TextField(
                blank=True,
                choices=[("redirect", "Redirect"), ("post", "Post")],
                default="redirect",
                help_text="This determines how authentik sends the logout response back to the Service Provider.",
                verbose_name="SLS Binding",
            ),
        ),
        migrations.AddField(
            model_name="samlprovider",
            name="sls_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Single Logout Service URL where the logout response should be sent.",
                validators=[authentik.lib.models.DomainlessURLValidator(schemes=("http", "https"))],
                verbose_name="SLS URL",
            ),
        ),
    ]
