# Generated by Django 4.1.4 on 2022-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_stages_user_write", "0005_userwritestage_user_path_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwritestage",
            name="can_create_users",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "When set, this stage can create users. If not enabled and no user is"
                    " available, stage will fail."
                ),
            ),
        ),
    ]
