// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/BeryJu/passbook/proxy/pkg/models"
)

// ProvidersSamlCreateReader is a Reader for the ProvidersSamlCreate structure.
type ProvidersSamlCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProvidersSamlCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProvidersSamlCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProvidersSamlCreateCreated creates a ProvidersSamlCreateCreated with default headers values
func NewProvidersSamlCreateCreated() *ProvidersSamlCreateCreated {
	return &ProvidersSamlCreateCreated{}
}

/*ProvidersSamlCreateCreated handles this case with default header values.

ProvidersSamlCreateCreated providers saml create created
*/
type ProvidersSamlCreateCreated struct {
	Payload *models.SAMLProvider
}

func (o *ProvidersSamlCreateCreated) Error() string {
	return fmt.Sprintf("[POST /providers/saml/][%d] providersSamlCreateCreated  %+v", 201, o.Payload)
}

func (o *ProvidersSamlCreateCreated) GetPayload() *models.SAMLProvider {
	return o.Payload
}

func (o *ProvidersSamlCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SAMLProvider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
