# Generated by Django 5.2.17 on 2026-10-09 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_brands", "0016_brand_branding_map_tiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandLocaleCatalog",
            fields=[
                (
                    "binding_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Catalogs for the same locale are applied in ascending order, so when multiple catalogs translate the same message, the catalog with the highest order wins. Catalogs for a more specific locale (`de-AT`) always win over catalogs for the base language (`de`).",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="authentik_brands.brand"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Locale Catalog Binding",
                "verbose_name_plural": "Brand Locale Catalog Bindings",
            },
        ),
        migrations.CreateModel(
            name="LocaleCatalog",
            fields=[
                (
                    "catalog_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("locale", models.TextField(help_text="Locale code, for example `de` or `de-DE`.")),
                ("enabled", models.BooleanField(default=True)),
                ("messages", models.JSONField(blank=True, default=dict)),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True,
                        related_name="locale_catalogs",
                        through="authentik_admin_i18n.BrandLocaleCatalog",
                        to="authentik_brands.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Locale Catalog",
                "verbose_name_plural": "Locale Catalogs",
            },
        ),
        migrations.AddField(
            model_name="brandlocalecatalog",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentik_admin_i18n.localecatalog"
            ),
        ),
        migrations.AddIndex(
            model_name="localecatalog",
            index=models.Index(fields=["locale", "enabled"], name="authentik_a_locale_436736_idx"),
        ),
        migrations.AddIndex(
            model_name="brandlocalecatalog",
            index=models.Index(fields=["brand", "order"], name="authentik_a_brand_i_677465_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="brandlocalecatalog",
            unique_together={("brand", "catalog")},
        ),
    ]
