[[plugins]]
  package = "netlify-plugin-cache"

[plugins.inputs]
  paths = [".docusaurus", ".cache", 'node_modules/.cache']

[[plugins]]
  package = "netlify-plugin-debug-cache"

[build]
  base    = "website"
  package = "integrations"
  command = "npm run build -w integrations"
  publish = "website/integrations/build"

[dev]
  command    = "npm start"
  targetPort = 3000

[context.production.environment]
  NODE_ENV = "production"

[context.dev.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
