// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/BeryJu/passbook/proxy/pkg/models"
)

// PoliciesGroupMembershipPartialUpdateReader is a Reader for the PoliciesGroupMembershipPartialUpdate structure.
type PoliciesGroupMembershipPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PoliciesGroupMembershipPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPoliciesGroupMembershipPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPoliciesGroupMembershipPartialUpdateOK creates a PoliciesGroupMembershipPartialUpdateOK with default headers values
func NewPoliciesGroupMembershipPartialUpdateOK() *PoliciesGroupMembershipPartialUpdateOK {
	return &PoliciesGroupMembershipPartialUpdateOK{}
}

/*PoliciesGroupMembershipPartialUpdateOK handles this case with default header values.

PoliciesGroupMembershipPartialUpdateOK policies group membership partial update o k
*/
type PoliciesGroupMembershipPartialUpdateOK struct {
	Payload *models.GroupMembershipPolicy
}

func (o *PoliciesGroupMembershipPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /policies/group_membership/{policy_uuid}/][%d] policiesGroupMembershipPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PoliciesGroupMembershipPartialUpdateOK) GetPayload() *models.GroupMembershipPolicy {
	return o.Payload
}

func (o *PoliciesGroupMembershipPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupMembershipPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
