# Re-usable workflow for a multi-architecture build
name: Multi-arch container build

on:
  workflow_call:
    inputs: {}
    outputs: {}

jobs:
  build-server-amd64:
    uses: ./.github/workflows/_reusable-docker-build-single.yaml
    with:
      arch: amd64
      runs-on: ubuntu-latest
  build-server-arm64:
    uses: ./.github/workflows/_reusable-docker-build-single.yaml
    with:
      arch: arm64
      runs-on: ubuntu-22.04-arm
  merge-server:
    runs-on: ubuntu-latest
    needs:
      - build-server-amd64
      - build-server-arm64
    steps:
      - name: prepare variables
        uses: ./.github/actions/docker-push-variables
        id: ev
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          image-name: ghcr.io/goauthentik/server,beryju/authentik
      - name: Docker Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          tags: ${{ steps.ev.outputs.imageTags }}
          sources: |
            ghcr.io/goauthentik/server@${{ needs.build-server-amd64.outputs.image-digest }}
            ghcr.io/goauthentik/server@${{ needs.build-server-amd64.outputs.image-digest }}
