name: Build-Authentik_testing

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select the Environment for Building the Image
        required: true
        options:
          - dev2
          - test
          - production
        type: choice
      with-sbom:
        type: boolean
        default: true
        description: Build with SBOM?
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:
  Build-Authentik:
    name: Build Authentik Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.SCRIBE2_GITHUB_ROLE }}
      #     role-session-name: Github
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2
      #   with:
      #     mask-password: 'true'

      - name: Build, Tag and Push Authentik Image to Amazon ECR
        id: build-image
        run: |
          echo "Hello"

  Update-Environment-Variable:
    if: ${{ always() && (needs.Build-Authentik.result == 'success') }}
    name: Update Environment Variable with Docker Image Tag
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [Build-Authentik]
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      
      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Update Docker Image Tag Environment Variable
        run: gh secret set AUTHENTIK_TAG_TEST --body "${{ github.sha }}" --repo scribe-security/scribe2
