name: authentik-ci-website

on:
  push:
    branches:
      - main
      - next
      - version-*
  pull_request:
    branches:
      - main
      - version-*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: |
          npm run lint:prettier:check
          npm run lint:lockfile -w @goauthentik/docs
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./package.json
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: test
        run: |
          npm run test -w @goauthentik/docs
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./package.json
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build -w @goauthentik/docs
  ci-website-mark:
    if: always()
    needs:
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
