# Generated by Django 5.0 on 2023-12-27 15:37

import uuid

import django.db.models.deletion
from django.db import migrations, models

import authentik.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentik_core", "0032_group_roles"),
        ("authentik_policies", "0011_policybinding_failure_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RACPropertyMapping",
            fields=[
                (
                    "propertymapping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.propertymapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAC Property Mapping",
                "verbose_name_plural": "RAC Property Mappings",
            },
            bases=("authentik_core.propertymapping",),
        ),
        migrations.CreateModel(
            name="RACProvider",
            fields=[
                (
                    "provider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.provider",
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                (
                    "auth_mode",
                    models.TextField(choices=[("static", "Static"), ("prompt", "Prompt")]),
                ),
            ],
            options={
                "verbose_name": "RAC Provider",
                "verbose_name_plural": "RAC Providers",
            },
            bases=("authentik_core.provider",),
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "policybindingmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_policies.policybindingmodel",
                    ),
                ),
                ("name", models.TextField()),
                ("host", models.TextField()),
                (
                    "protocol",
                    models.TextField(choices=[("rdp", "Rdp"), ("vnc", "Vnc"), ("ssh", "Ssh")]),
                ),
                ("settings", models.JSONField(default=dict)),
                (
                    "auth_mode",
                    models.TextField(choices=[("static", "Static"), ("prompt", "Prompt")]),
                ),
                (
                    "property_mappings",
                    models.ManyToManyField(
                        blank=True, default=None, to="authentik_core.propertymapping"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_rac.racprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAC Endpoint",
                "verbose_name_plural": "RAC Endpoints",
            },
            bases=("authentik_policies.policybindingmodel", models.Model),
        ),
        migrations.CreateModel(
            name="ConnectionToken",
            fields=[
                (
                    "expires",
                    models.DateTimeField(default=authentik.core.models.default_token_duration),
                ),
                ("expiring", models.BooleanField(default=True)),
                (
                    "connection_token_uuid",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ("token", models.TextField(default=authentik.core.models.default_token_key)),
                ("settings", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_core.authenticatedsession",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_rac.endpoint",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_rac.racprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
