module.exports = {
    pipeline: {
        "extract-locales": [],
        "build-locales": [],
        "build-locales:build": [],
        "build-locales:repair": [],
        "rollup:build": [],
        "rollup:build-proxy": [],
        "rollup:watch": [],
        "build": [],
        "build-proxy": [],
        "watch": [],
        "lint": [],
        "lint:precommit": [],
        "lint:spelling": [],
        "lit-analyse": [],
        "precommit": [],
        "prequick": [],
        "prettier-check": [],
        "prettier": [],
        "pseudolocalize:build-extract-script": [],
        "pseudolocalize:extract": [],
        "pseudolocalize": [],
        "tsc:execute": [],
        "tsc": [],
        "storybook": [],
        "storybook:build": [],
        "storybook:build-import-map": [],
        "storybook:build-import-map-script": [],
        "storybook:run-import-map-script": [],
    },
};
