module.exports = {
    // Basic syntax: just run these tasks all the packages. There is only one package at the moment.
    pipeline: {
        "extract-locales": ["^extract-locales"],
        "build-locales": ["^build-locales"],
        "build-locales:build": ["^build-locales:build"],
        "build-locales:repair": ["^build-locales:repair"],
        "rollup:build": ["^rollup:build"],
        "rollup:build-proxy": ["^rollup:build-proxy"],
        "rollup:watch": ["^rollup:watch"],
        "build": ["^build"],
        "build-proxy": ["^build-proxy"],
        "watch": ["^watch"],
        "lint": ["^lint"],
        "lint:precommit": ["^lint:precommit"],
        "lint:spelling": ["^lint:spelling"],
        "lit-analyse": ["^lit-analyse"],
        "precommit": ["^precommit"],
        "prequick": ["^prequick"],
        "prettier-check": ["^prettier-check"],
        "prettier": ["^prettier"],
        "pseudolocalize:build-extract-script": ["^pseudolocalize:build-extract-script"],
        "pseudolocalize:extract": ["^pseudolocalize:extract"],
        "pseudolocalize": ["^pseudolocalize"],
        "tsc:execute": ["^tsc:execute"],
        "tsc": ["^tsc"],
        "storybook": ["^storybook"],
        "storybook:build": ["^storybook:build"],
        "storybook:build-import-map": ["^storybook:build-import-map"],
        "storybook:build-import-map-script": ["^storybook:build-import-map-script"],
        "storybook:run-import-map-script": ["^storybook:run-import-map-script"],
    },
};
